<p>Desde que la industria discográfica certificara  su propia defunción, allá por el advenimiento de internet, la cantidad de  novedades musicales se fue multiplicando al ritmo de los panes y los peces.  Para explicar este proceso en apariencia contradictorio podrían esgrimirse una  multitud de motivos: la conversión del oyente en usuario, el final del culto al  objeto-disco, la simple y llana piratería vikinga o la bipolaridad de una  industria que se afana por explotar todas las ventajas (propias) de la red de redes  a la vez que censura todas las ventajas (ajenas) de la red de redes. Sea como  fuere, no nos toca valorar esta realidad compleja y sí exprimir en pocas líneas  las beldades y algunas de las fealdades de estos discos crujientes como  milonguitas recién salidas del horno. Prick up your ears!</p>
<p><strong>Sinéad  O'Connor:</strong> <em>I'm Not  Bossy, I'm The Boss </em>(Nettwerk, 2014)<br />
  Experta en no conformar a todos por igual, la  irlandesa Sinéad O&rsquo;Connor ha estado más asociada a novedades extramusicales que  a alguno de los buenos discos que publicó en sus más de veinte años de carrera.  Los flirteos religiosos, las confesiones sexuales y cierto vaivén en su imagen  personal le han emparejado con esos escándalos de los que tan bien viven  quienes recogen las migas que se les caen a los demás. <em>I'm Not Bossy, I'm The Boss</em> llega con la intención de correr el  foco desde el chisme a unas composiciones que, bordeando lo autobiográfico,  oscilan entre el pop más simplón y el estertor desgarrado. La escucha comienza  sumergiéndonos de golpe en lo previsible (&ldquo;How I About…&rdquo;), con temas que lo han  dicho todo en los primeros veinte segundos. Pero mediada la placa las piedras  de lo radiable dejan paso a &ldquo;The Voice of my Doctor&rdquo;, &ldquo;Harbour&rdquo; &ldquo;James Brown&rdquo; y  &ldquo;8 Good Reasons&rdquo;, cuatro canciones consecutivas que equilibran la balanza y  que, al final, dejan a todo el mundo con buen sabor de boca. Por fin, Sinéad lo  hizo.</p>
<p>
  <iframe width="770" height="433" src="//www.youtube.com/embed/jMzY_KQIKjU?rel=0" frameborder="0" allowfullscreen></iframe>
</p>
<p><strong>&nbsp;</strong></p>
<p><strong>Morrissey: </strong><em>World  Peace Is None Of Your Business</em> (Harvest Records, 2014)<br />
  La publicación de un nuevo disco de Morrissey  suele constituir una noticia de lo más estimulante para esa inmensa minoría que  permanece atenta a los pasos del músico británico. Buenas canciones, una  performance vocal impecable, salpicones de crítica y sarcasmo: algo de esto  está asegurado ante cada lanzamiento. El caso de <em>World Peace Is None Of Your Business</em> es una confirmación múltiple a  esta regla. Temas como el que da título al álbum, la hipnótica &ldquo;Neal Cassady  Drops Dead&rdquo;, &ldquo;Kiss Me A Lot&rdquo; (con su aroma a The Smiths) o los bonus  &ldquo;Art-Hounds&rdquo; y &ldquo;Scandinavia&rdquo; admiten más de una escucha, en parte gracias a los  característicos giros vocales de Mozz. Los toques latinos o directamente  hispanos son más que notorios y hacen cumbre en &ldquo;The Bullfighter Dies&rdquo;, donde  el garrote que se llevan España y la tauromaquia es de los notables. Pero como  suele ocurrir cuando se trata de Morrissey, la vida de sus discos continúa más  allá de su circunferencia. En este caso, a los pocos días del estreno de <em>World Peace</em>… la discográfica Harvest ha  anunciado la ruptura de relaciones con su representado a raíz de las críticas  de este a aquella por no haber producido videoclips promocionales. Todo empezó  cuando Morrissey elogió el esfuerzo de algunos fans por elaborar caseros y  apreciados montajes de imágenes, uno de los cuales pueden ver a continuación.</p>
<p>
<iframe width="770" height="433" src="//www.youtube.com/embed/uBCg28Pxc0Q?rel=0" frameborder="0" allowfullscreen></iframe></p>
<p><strong>&nbsp;</strong></p>
<p><strong>Bugge  Wesseltoft:</strong> <em>OK World</em> (Jazzland Recordings, 2014)<br />
  Si de algo ha dado muestras el pianista noruego  Bugge Wesseltoft a lo largo de su ya dilatada carrera es de versatilidad.  Inscrito originalmente en el magma jazzístico e inclinado más tarde hacia el <em>nu</em> jazz, no tarda en entregarse por fin  a un sonido propio que es reconocible desde la primera nota y al que no le  faltan trazas de <em>ambient</em> y  electrónica. En su nuevo proyecto, OK World, consigue el más difícil todavía:  abarcar y apretar con la misma fuerza. Acá aparece como timonel de un arca en  el que se acompaña de músicos de tres continentes y seis nacionalidades. El  resultado son vientos de flamenco, letanías orientales y bases latinas que,  junto a otras deliciosas especias musicales, conforman un disco que es un <em>cross</em> directo a la mandíbula de quienes  banalizan la <em>world music</em> con un meneo  de caderas.</p>
<p>
  <iframe width="770" height="433" src="//www.youtube.com/embed/1yfjyrRVgXw?rel=0" frameborder="0" allowfullscreen></iframe>
</p>
<p><strong>&nbsp;</strong></p>
<p><strong>Karma To  Burn:</strong> <em>Arch  Stanton</em> (FABA/Deepdive Records, 2014)<br />
  El sexto álbum en estudio del trío  estadounidense de rock <em>stoner</em> serviría perfectamente para ilustrar la definición de &ldquo;continuismo&rdquo;: potentes  temas instrumentales que crecen a la sombra de ese enorme baobab llamado Kyuss, <em>riffs</em> hipnóticos que miran de reojo a  la psicodelia, carretillas de entrega y esa costumbre babilónica de numerar los  temas según una lógica no siempre al alcance del oyente. Si lo que se busca es  la sorpresa, la exploración sonora y la sublimación del matiz, esta no es tu  fiesta. Si, por el contrario, lo que se necesita es cambiar el rumbo de esa mañana  anodina y salir a asustar por las calles bacheadas, la banda de West Virginia  acaba de preparar un manjar con tu nombre. ¡Marchando una de karma flambeado!<br />
  <br />
  <iframe width="770" height="433" src="//www.youtube.com/embed/De-zrgA3o0g?rel=0" frameborder="0" allowfullscreen></iframe>
</p>
<p><strong>&nbsp;</strong></p>
<p><strong>Peter  Murphy:</strong> <em>Lion</em> (Nettwerk, 2014)<br />
  Pocos vocalistas hay en este zoo del rock que  ofrezcan lo que el exBauhaus Peter Murphy. Sus graves antológicos y una  potencia casi primigenia se enroscan como hiedra al durmiente con la textura de  unos temas que han dejado atrás lo más exhibicionista del joven gótico para  pisar fuerte en una madurez ya adentrada en la sabiduría. Prácticamente todas  las composiciones que integran su nuevo <em>Lion</em> destilan esta embriaguez. La espesura del primer tema (&ldquo;Hang Up&rdquo;) amenaza con  un disco que tiene mucho de circular, como metafóricamente preanuncia la  calesita del videoclip. Queda claro que lo que oímos después nos gusta. &ldquo;Low  Tar Stars&rdquo; nos devuelve acelerado aquel tempo obsesivo de &ldquo;Bela Lugosi's Dead&rdquo;,  mientras &ldquo;Compression&rdquo; y &ldquo;Holy Clown&rdquo; se suceden en intensidad y la más  promocional &ldquo;Eliza&rdquo; comienza a despedir un disco que se cierra con la  perturbadora &ldquo;Lion&rdquo;. La eufórica desazón que queda tras el silencio final corre  por cuenta y gasto del oyente. </p>
<p>
<iframe width="770" height="433" src="//www.youtube.com/embed/lymd7efDvIk?rel=0" frameborder="0" allowfullscreen></iframe></p>
