<p><span class="image_cen1"><img src="images/1101.jpg"></span>En el año 1971, el ahora dominante rock nacional argentino era apenas  un puñado de manifestaciones esporádicas con epicentro en la siempre movida  ciudad de Buenos Aires. Desde los barrios del sur del conurbano bonaerense  llegó Vox Dei, uno de los tríos que cambiaría para siempre el rumbo y que  ayudaría a cuajar la dispersión en movimiento. En ese año, impulsados por las  apuestas de alto riesgo del sello Mandioca, al mando de Jorge Álvarez, el power  trío grabaría su segundo disco, <em>La Biblia</em>, uno de los  grandes mitos/hitos del rock en español. &ldquo;Cristo y Nacimiento&rdquo; es un tema  instrumental, de los más cortos del álbum doble, que acompaña en el lado C a  &ldquo;Libros sapienciales&rdquo;.<br /><br />

<audio id="audio" controls="controls" preload="none" style="background-color:black">
	<source src="./musica/1101.mp3" type="audio/mp3">
</audio></p><br /><br />
<p><span class="image_cen1"><img src="images/1102.jpg"></span>Basada en la figura de Elvis Presley, &ldquo;Personal Jesus&rdquo; es uno de los  más grandes éxitos de la banda inglesa Depeche Mode. Con flamantes 25 años en  surcos de vinilo y soportes ópticos, el tema encara la figura del nazareno como  una metáfora de la amistad, de quien está allí cuando uno necesita a alguien  que le dé soporte, en carne y hueso, a través del teléfono, el saber que hay  alguien que se interesa por nuestro devenir. Por fuera de la versión original,  Johnny Cash la incluyó en su disco &ldquo;Man Comes Around&rdquo;, de 2002, un año antes de  pasar a la inmortalidad. Dijo sobre la canción: &quot;No teníamos mayores  objeciones sobre esta canción. Había escuchado que algunas personas la habían  grabado, el autor me dijo que la escuchara, lo hice y la amé&quot;.<br /><br />
<audio id="audio" controls="controls"  preload="none" style="background-color:black">
	<source src="./musica/1102.mp3" type="audio/mp3">
</audio></p><br /><br />
<p><span class="image_cen1"><img src="images/1103.jpg"></span>&ldquo;Tremor Christ&rdquo; es el cuarto tema del tercer disco de esa estupenda  banda de Seattle llamada Pearl Jam. Editada como sencillo en 1993, al año  siguiente fue parte de <em>Vitalogy</em>, un  álbum que salió y arrasó con todo. Guitarra machacona, sonido áspero, clima  oscuro, la inconfundible voz de Eddie Vedder y Brendan O&rsquo;Brien en las perillas  son los ingredientes de este tema en el que las previas a la salida del  marinero al mar, los rezos y la música del órgano parroquial se mezclan con las  lágrimas saladas. Imágenes de pequeños pueblos y grandes infiernos, o al decir  de Vedder y los suyos: &ldquo;Aun los océanos más pequeños tienen grandes, grandes  olas&rdquo;.<br /><br />
<audio id="audio" controls="controls"  preload="none" style="background-color:black">
	<source src="./musica/1103.mp3" type="audio/mp3">
</audio></p><br /><br />
<p><span class="image_cen1"><img src="images/1104.jpg"></span>Poseedor del privilegio de haber vendido más de 120 millones de discos  a lo largo de una vasta trayectoria en las lides del cantar, Roberto Carlos es  el autor de &ldquo;Jesus Cristo&rdquo;, de esta selección la más pegada al formato y decir  de una plegaria; lo que no impidió (incluso quizá lo haya favorecido) que se  convirtiera en una de sus composiciones más populares y conocidas. La imagen de  la nube blanca que va pasando y la multitud que camina sin saber adónde va  seguramente está grabada en la memoria de millones. El chiste fácil sería que  suena lógico el éxito de esta canción para un sujeto nacido en el estado de  Espíritu Santo, Brasil, que milagrosamente se salvó de la muerte al ser  arrollado por una locomotora cuando tenía tan sólo 6 años.<br /><br />
<audio id="audio" controls="controls"  preload="none" style="background-color:black">
	<source src="./musica/1104.mp3" type="audio/mp3">
</audio></p><br /><br />
<p><span class="image_cen1"><img src="images/1105.jpg"></span>Sería exagerado decir que el cuarto álbum de Wilco, <em>Yankee Hotel Foxtrot</em>, pasó por un  calvario antes de ser editado por el sello Nonesuch en 2002, pero tal  exageración le viene como anillo al dedo a esta breve reseña de &ldquo;Jesus, etc.&rdquo;,  una canción estupenda, formalmente made in Wilco, candidata a ser la favorita  de los que escuchan el disco. Grabado originalmente entre finales de 2000 y  principios de 2001, la placa fue rechazada por la Warner, los derechos  comprados por los mismos Wilco (ironías y cinismos del capitalismo) y lanzado  gratuitamente vía Internet en septiembre de 2001, pocos días después del  atentado a las Torres Gemelas, abriendo la duda de si fue consecuencia o  coincidencia el comienzo de la segunda estrofa: &ldquo;Los altos edificios se  tambalean / Las voces se escapan cantando tristes, tristes canciones&rdquo;.<br /><br />
<audio id="audio" controls="controls"  preload="none" style="background-color:black">
	<source src="./musica/1105.mp3" type="audio/mp3">
</audio></p><br /><br />
<p><span class="image_cen1"><img src="images/1106.jpg"></span>Si esta reseña comenzó con el nacimiento de Cristo, lo lógico es  cerrarlo con esa joya que en 1973 Pescado Rabioso como canto del cisne: &ldquo;Post  Crucifixión&rdquo;, un sencillo del año 1973 que en su cara B tenía otro clásico:  &ldquo;Despiértate, nena&rdquo;. Estos temas fueron agregados, en ediciones posteriores a  la original, al disco <em>Desatormentándonos</em>,  el primero de los dos de estudio de una de las bandas insignia del rock  argentino. La letra, aunque breve, es una contundente metáfora que de los  dolores que, ya en la cruz del cotidiano, atenaza de angustia a cualquier  sujeto: &ldquo;Abrázame madre del dolor / Nunca estuve tan lejos de mi cuerpo&rdquo;.<br /><br />
<audio id="audio" controls="controls"  preload="none" style="background-color:black">
	<source src="./musica/1106.mp3" type="audio/mp3">
</audio></p><br /><br />
