<p>Ir a la populosa ciudad balnearia de Mar del Plata fuera de la  temporada estival no sólo garantiza unos relajados paseos por la costa  atlántica sino también el disfrute de una ciudad carente del empuje turístico  que convierte las playas en lo más parecido a un hormiguero que la Argentina puede dar. Si  la ocasión coincide con el deshoje del invierno, nada mejor que darse unas  vueltitas por algunos de los tantos y tantos restaurantes y bares que ofrecen  una gastronomía tan variada, en tipo y calidad, como las miles y miles de  personas que la habitan circunstancialmente.</p>
<p><span class="image_cen1"><img src="images/2701.jpg"></span><strong>Chill Out Café</strong><br />
  Alte. Brown esquina H. Yrigoyen<br />
  Teléfono: (0223) 493-5699<br />
Ideal para el desayuno y el almuerzo, este bonito café propone una acotada  carta de platos que no por breve deja de ser una muy buena opción a la hora de  comer. Delicadamente ambientado, pulcro, con sillones cómodos y buena luz  natural, se destacan los llamados woks, sean de pollo, lomo o verduras y la  provisión de los famosos menús infantiles que, sin escaparle a la clásica  oferta para niños, son elaborados con buena materia prima, como todos los  demás. Los platos llegan con una decoración bien cuidada que, a la dimensión  del buen sabor, le agrega la de ser agradables y tentadores a la vista. Y para  el oído, la música chill out que anticipa su nombre, a un volumen bajo que  permite que la charla de los comensales discurra sin interrupciones.</p>
<p><span class="image_cen1"><img src="images/2702.jpg"></span><strong>Zafarrancho</strong><br />
  Belgrano 2361<br />
  Teléfono: (0223) 494 7342<br />
La gastronomía marplatense, ¿sería lo que es sin estos restaurantes  pensados y diseñados para albergar centenares de comensales? Aunque la  respuesta debe empezar a buscarse haciendo la prueba de ponerle el cuerpo a los  tantos que brotan en las calles céntricas, anticipamos que nada sería lo que es  sin estos megacomedores, entre los que se destaca Zafarrancho por apostar,  dentro de los límites de lo multitudinario, a cierta cuota esperanzada de  intimidad en su distribución de mesas, separadas por paneles de madera y vidrio  y a una estética alejada del bodegón familiar o de las otrora famosas cantinas  del barrio de La Boca. La  comida alcanza unos niveles que superan cualquier expectativa considerando la  masividad de los comensales, sean las rabas a la romana, un salmón con salsa de  camarones o unos raviolones de espinaca en salsa de calabaza.</p>
<p><span class="image_cen1"><img src="images/2703.jpg"></span><strong>Las Barcas</strong><br />
  Alem 4221<br />
  Teléfono: (0223) 414-0003<br />
Con ventanales que dan sobre la vieja cancha del Mar del Plata Golf  Club y con vista al mar, Las Barcas, el restaurante que se ubica dentro del  hotel de la cadena Sheraton, es un lugar ideal para una buena cena y una charla  distendida. Desde su cuidada decoración marina, acorde con el paisaje y el  nombre, hasta la comodidad superior de su mobiliario, el restaurante está  pensado para quienes gustan de comer a un <em>tempo</em> distendido y sin apuros. Como es de prever, la carta ofrece un amplio abanico  de delicias que refrendan en el plato lo que prometen en la carta; apoyados en  una oferta de vinos que no deja rango de gusto por cubrir. Quienes disfruten de  la buena compañía, el buen comer y el buen beber, encontrarán en Las Barcas un  restaurante a la altura de las circunstancias y, apostamos doble contra  sencillo, con la promesa de volver a seguir dejándose llevar por exquisitos  sabores.</p>
