<p>En el recomendable <em>Aquí América Latina. Una especulación</em>,  Josefina Ludmer narra un paseo por el Jardín Botánico junto a la poeta Tamara  Kamenszain. ¿El tema? La poesía actual. En cierto momento, Kamenszain comenta,  en relación a la poesía argentina que empezó a publicarse a partir de mediados  de los 90, que &ldquo;… a estos pibes solo parece interesarles perforar con un  taladro la realidad, para dejarla clavada, detenida&rdquo;. Kamenszain habla de  cierta estética orientada al minimalismo, la cotidianidad, cierta crudeza  visual, que prefiguró o cohabitó la escena <em>blogger</em> y luego, tal vez, el devenir de las redes sociales, por trazar algunos  paralelos con la era digital. </p>
<p>Empecé a leer poesía contemporánea  mientras intentaba escribir poesía contemporánea. En aquel momento, la  plataforma <em>Las afinidades electivas / Las  elecciones afectivas </em>funcionó, para mí, como un gran muestrario, un paneo  arbóreo e incompleto –aunque con voluntad de totalidad– del amplio espectro  poético nacional. Años después, cuando el impulso de las <em>Afinidades</em> decayó, apareció, en un gesto de continuidad pero  también de superación, Malón Malón. Curaduría web. Antología descentralizada.  Muestrario de poesía con resonancias pictóricas. Malón Malón es, entre otras  posibles definiciones, algo así: una plataforma craneada por los poetas Tom  Maver y Patricio Foglia que reúne una selección de piezas de un poeta  contemporáneo con un ilustrador y un crítico que interviene sobre el texto.</p>
<p><strong>Malón  Malón ya ha publicado casi una veintena de autores, acompañados por una  intervención crítica y una ilustración. ¿Hay algún balance del proyecto?  ¿Sienten que de alguna manera están oficiando de editores, aun sin  proponérselo?</strong><br />
  A lo largo de este tiempo conocimos  poetas e ilustradores muy interesantes, y también muy distintos entre sí.  Descubrimos o confirmamos algo: un montón de gente allá afuera está indagándose  respecto de su propia escritura, es decir, a lo largo de todo el país hay gente  construyendo su propio universo y su propia voz, más allá de la rectoría de  cualquier programa estético. </p>
<p>Nuestro trabajo no es tanto de edición,  que es algo más arduo y detallista en algún punto. La idea es más sencilla, y  parte de la pregunta: &ldquo;¿Qué poeta podría conectar con qué lectores?&rdquo;. Entonces  hacemos circular los poemas, primero hacia quien comenta y hacia quien ilustra.  Y después, ya con la entrada lista, para todos los lectores del blog. </p>
<p><strong>Creo  que es muy interesante, porque de alguna manera complejiza esta relación de  obra e intervención crítica, la presencia de los ilustradores. ¿Cuál ha sido el <em>feedback</em> con ellos?&nbsp;</strong><strong>¿Les parece que hay una relación armónica entre  estos tres elementos?</strong><br />
  Los ilustradores, con su mirada y su  trabajo, aportan algo que a la vez está y no está en cada serie de poemas. Se  trata de una lectura, o de una traducción, que funciona desde otro lenguaje y  expande la potencialidad de los textos, poniéndolos a jugar en un escenario  distinto. Deleuze decía que la alegría consistía en colmar una potencialidad, en la realización de lo impensado.</p>
<p>Con los ilustradores empezamos  convocando a amigos, que después a su vez nos recomendaron a otros  ilustradores, y después se sumaron otros y otros más. Las entradas a veces  armonizan y otras veces entran en tensión y discuten, pero siempre está  presente esa alegría deleuziana. </p>
<p><strong>¿Por  dónde pasa la convocatoria de los poetas? ¿Es efecto bola de nieve, a partir de  recomendaciones, o hay algún corte estético?</strong><br />
  Es algo muy parecido a lo que pasa  con los ilustradores. Es como una buena fiesta, la noche está hermosa, hace  calor y está la luna, y va cayendo la gente y ya nadie sabe cómo y por quién  llegó. </p>
<p>Nosotros no editamos los poemas, ni  sugerimos ningún tipo específico de comentario ni de ilustración. De todas  formas, es cierto que hay un recorte estético, aunque sea mínimo, a la hora de  elegir qué poemas pueden generar ese cruce que es cada entrada. Pero no  responde a los rigores de un proyecto estético. No defendemos una estética  particular ni somos militantes de ningún tipo de poesía. Aunque nos gusten más  ciertas propuestas –a cada cual las suyas– tratamos de ser lectores curiosos, y  mantener abierto ese juego.<strong></strong></p>
<p><strong>Hace  ya una década, la expansión de la cultura <em>blogger</em> abrió espacios y portales para que muchos poetas mostraran sus obras. En el  medio, apareció un sitio como <em>Las  elecciones afectivas</em>, que de alguna manera se convirtió en un gran  muestrario <em>on-line</em> de la poesía  contemporánea argentina. ¿Hubo algo de ese flujo que marcó el proyecto que hoy  encaran?</strong><br />
  Sí. Sitios como <em>Las elecciones afectivas</em>, <em>Otra  Iglesia es imposible</em>, <em>El placard,  Emma Gunst </em>o los blogs de Irene Gruss y Osvaldo Bossi son referencias  ineludibles; lo que buscamos, de alguna forma fue armar una plataforma de  encuentro y difusión, y darle una vuelta de tuerca al contenido y a la forma  que venían presentando esos espacios virtuales. Por eso, pensamos en sumar un  comentario y una ilustración, como modo de generar un diálogo, y una  escenografía que describa en parte esa ausencia de programa; de ahí la idea del  malón. Después, sumamos nuestras notas y las entrevistas, para romper el enclaustramiento  que podía generarse si sólo funcionase como el blog de una generación  específica. </p>
<p><strong>¿Cómo  ven el circuito –de distribución, de lectura, de consumo– de la poesía, hoy por  hoy?</strong><br />
  Hoy la poesía circula mucho a través  de internet, pero también en los talleres, en las lecturas, en las  presentaciones, en las ferias de libros independientes. Realmente es un género  en movimiento constante, que al mismo tiempo se mantiene un poco al margen del  mercado. A lo mejor es como dice Diana Bellessi, que en el capitalismo todo lo  que se muestra se compra y vende, y falta un poco de eso aunque el <em>under</em> también tiene su encanto.</p>
<p><strong>Para  los que no conocen, me gustaría que recomendaran una entrada de Malón Malón, es  decir, un poeta, con la correspondiente intervención e ilustración.</strong><br />
  Cada  entrada es especial, y por eso la subimos. Por eso, de hecho, hacemos el blog.  De todas formas, la entrada de Daniel Oblitas es, tal vez, la más relevante hasta acá,  porque fue aquella a la que pusimos mayor dedicación. Es un amigo y un poeta  que ya no está, y sentimos la necesidad de expandir su potencialidad, por todos  los medios posibles, para que siga escribiendo a través de otras lecturas.  Resultó algo absolutamente necesario para nosotros, y también una enorme  alegría.</p>
  
<p><strong>Malón Malón:  http://malonmalon.blogspot.com.ar</strong></p>
