<p><strong>Ketil Bjørnstad</strong> es uno de esos particulares talentos que desparraman sus haceres en diversas  disciplinas, más cercanas al concepto renacentista del artista que del  contemporáneo en una realidad que pulsa por acotar y especializar. Prolífico en  sus manifestaciones, tiene un currículo vita que incluye más de media centena  de discos y más de veinte libros, entre novelas, ensayos y poemas, traducidos a  varias otras lenguas distintas su lengua noruega materna. 
  Nacido en Oslo en 1950, se formó como un pianista clásico  que a los 16 años de edad deslumbraba a los oyentes interpretando a Béla Bartók.  No transcurriría mucho tiempo para que emprendiera sus travesías por las  turbulentas aguas del jazz y el rock, patinadas con los brillos del pop; vetas  musicales que adoptó y adaptó a sus necesidades expresivas, haciendo uso de  una, otra y ambas para componer discos que son un verdadero hallazgo.<br />
  <br />
  <strong>Seafarer’s songs</strong> (Canciones de marineros) es uno de ellos. No sólo porque en su transcurrir  logra hacernos viajar por paisajes sonoros que tienen su eco en la esencia  acústica del mar, ese tema que se ha vuelto recurrente en sus composiciones de  los últimos años, sino porque entrama jazz, rock y textos de Emily Dickinson(<em>I Had Been Hungry, All the Years </em>y <em>I Many Times Thought Peace Had Come</em>),  Oscar Wilde (<em>Her Voice</em>), William  Shakespeare (<em>Ung Forelsket Kvinne</em>) y  Rudyard Kipling (<em>The Exile's Line</em>);  de algún modo, una topología de sonidos y palabras que lo ponen de manifiesto.<br />
  <br />
  Si en los inicios de su trayectoria musical reunió en torno  a su piano a los que hoy son considerados los popes del jazz noruego; en este  disco de 2004 logra, con otra formación tan exquisita como la otra, pero más  cercana al rock, deslumbrar con un sonido compacto; pleno de texturas,  distorsiones y sonoridades que se solapan y cuelan para urdir 17 temas que  pintan con precisión y pasión, las aguas que se rinden tranquilas y plácidas a  la quilla del barco; las tormentas; la angustia de la pequeñez en la inmensidad  oceánica y, claro está, las plegarias de los marineros frente al nuevo día.<br />
  <br />
  La esencia de <strong>Seafarer’s  songs</strong> se expone desde el comienzo mismo del disco. Comenzando por el tema  instrumental que le da nombre al disco y engarzando con <em>He Struggled to the Surface</em>, con letra del propio <strong>Bjørnstad</strong>, donde aparece la maravillosa  y ronca voz de esa belleza nórdica y pelirroja llamada Kristin Asbjørnsen; que  se pone a pleno con las arrolladoras guitarras de Eivind Aarset; y la impecable  solidez de la base del bajo de Bjørn Kjellemyr y la batería de Per Lindvall.<br />
  <br />
  Lejos del horizonte habitual de sus grabaciones para el  sello ECM, vagando por la estela de las melodías del romanticismo, <strong>Ketil Bjørnstad</strong> nos regala un disco de  límites imprecisos, borrosos, amplios, como los de los mares más lejanos.</p>
