<p><span class="image_cen1"><img src="images/301.jpg"></span>Si el nazismo fuera el centro de una elipse, <strong>Flechas de Plata</strong> no sería el trazado  que lo circunda sino el campo entre ambos; la superficie en la que se dirimen  los límites del ser, el pertenecer, el estar y el excluirse. <strong>Walter Kappacher</strong> envía a un joven  periodista deportivo, cuya vida sentimental con su novia japonesa está  derrapando hacia la ruptura disfrazado de distancia, a entrevistar a Paul  Windisch, un ingeniero de la industria automotriz que trabajó para la compañía  alemana Auto Union en el desarrollo de los Flecha de Plata, automóviles de  carrera construidos con el fin de batir récords mundiales de velocidad. El  desarrollo de estos autos acompañó históricamente al ascenso de Hitler al  poder, entre 1934 y 1939, manifestando su interés en el desarrollo de esa  industria; entramados entre poder y nombres que quedaron en la historia del  automovilismo como Ferdinand Porsche y Hans Stuck, y a los que <strong>Kappacher</strong> manipula de un modo casi  quirúrgico para contar el nazismo desde un <em>casi  dentro</em>; más o menos cercano en coincidencias ideológicas con el régimen;  más o menos comprometido con sus fines invasores y genocidas; amparado, en todo  caso, en la distorsión que la guerra puede introducir en la lectura de la  realidad. El devenir de su trabajo como ingeniero en el desarrollo de los  cohetes V2 le imprime una marca definitiva al asunto: un desafío personal por  sobre las consecuencias a futuro. El nazismo se dice sin ser declamado, se  recorta en los bordes que el propio Windisch está dispuesto a ponerle; y aun  así exuda por los poros de la historia que se cuenta, hediondo a pesar de los  intentos de ocultarlo. Todo sostenido en varias historias que, si no paralelas  en el tiempo, sí lo son en el relato; en lo que resulta la vida personal del  periodista, en sus planes y sus frustraciones; en la vida de Windisch en un  geriátrico del cual no termina de fugarse. Un viejo lisiado, manojo de  recuerdos de una época más nefastas de la historia, que nunca queda contra las  sogas, dejando en el lector el sabor amargo de las tragedias.<br />
  <strong>Flechas de Plata<br />
Walter Kappacher<br />
Traducción de Claudia Baricco<br />
2014</strong></p>
<p><span class="image_cen1"><img src="images/302.jpg"></span>La realidad política de Brasil a finales de la década del  sesenta no se escapó a la lógica que, años después, dominaría el mapa de  Sudamérica: dictadura militar, guerrillas de izquierda, torturas,  desapariciones, simulacros de enfrentamientos para encubrir ejecuciones  sumarias. En ese caldo de cultivo se cuecen las historias de Cirilo y Geraldo  Rego Castro; el primero, omnipresente; el segundo, narrado e intermitente.  Cirilo, el menor, es un estudiante de medicina por mandato familiar cuyos  inicios en la novela están ligados a Leonardo y Paula, quienes conforman un  trío amoroso que huye del <em>ménage à trois</em>,  y cuya ley de compartir a la mujer en el lecho se dirime por el que toma la  iniciativa cada vez. Geraldo, el mayor, es un militante estudiantil, perseguido  por la policía que ha pasado por la cárcel y se mueve en una estricta  clandestinidad. Hijos de una poderosa familia caída en desgracia, van tejiendo  sus historias en Recife; invisibles uno para el otro, atravesada la relación  entre ambos por los sentimientos contradictorios y explosivos de Cirilo. Lo  busca, a pedido de sus padres y a su pesar; y así como su enojo se troca en  orgullo de ser hermano de Geraldo cuando descubre el respeto que se le tiene en  la militancia juvenil y contracultural, refluye por los canales de la más  íntima indignación. El más joven de los Rego Castro exhibe su sociedad a través  de sus angustias, sus dudas, de su temor de ser señuelo para encontrar el  paradero de su hermano, de ser detenido y torturado para que confiese lo que no  sabe en absoluto. Las pocas cartas que cruzan con su madre terminan de armar la  fotografía familiar diseminada en las entrañas del norte brasileño. El coqueteo  de ambos con la muerte, el concepto de Lo Revolucionario, la intensidad con que  ambos viven su vida son apenas algunos de los rasgos de una novela que atrapa  la tensión al tiempo que pinta un fresco de un pasado que bien vale la pena no  olvidar ni repetir; de un momento al que nunca alcanzará el perdón.<br />
  <strong>Estuve allá afuera<br />
    Ronaldo Correia de Brito<br />
    Traducción de Claudia Solans<br />
    2014</strong></p>
