<p align="right">&ldquo;Con bestial dulzura rouge<br />
  y risas de Barón B&rdquo;.</p>
<p align="right">Indio Solari, <em>El arte del buen comer</em></p>
<p><span class="image_cen1"><img src="images/6.jpg"></span>Raúl Barón Biza es un escritor argentino nacido en Buenos Aires, en el  año 1899. Desde temprana edad incursionó en política y en la praxis literaria,  publicando, en 1924, su primer trabajo, titulado <em>Risas, lágrimas y sedas</em>. Apoyó a Yrigoyen y ulteriormente a su  opositor Uriburu. No obstante, desde su férrea militancia, combatió la llamada  Década Infame; un acto que le valió el encarcelamiento. Desde la prisión,  escribió la novela que abordaremos en el presente artículo: <em>El derecho de matar</em>. Contrajo dos matrimonios. El primero, con la  sueca Myriam Stefford y el segundo, con la argentina Rosa Clotilde Sabattini.  Esta última relación estuvo sesgada por el tormento y la sepulcral desolación.  Tal es así que, en 1964, se produjo una reunión entre los ya por entonces  excónyuges, con el propósito de poner punto final a los trámites de divorcio y,  tras una severa discusión, el novelista arrojó un vaso de whisky a su pretérita  esposa, el cual contenía ácido sulfúrico. Barón Biza huyó del lugar. Al día  siguiente, la policía allanó su residencia y encontró el cadáver del escritor  con una bala en la sien disparada por su propia mano. En años posteriores,  Clotilde Sabattini y uno de los hijos del autor, Jorge, se unieron a la senda  suicida del brillante, marginado e imponente escritor de las letras malditas  hispanoamericanas.<br />
  <br />
  La literatura del autor que nos convoca bien podría  encuadrarse bajo numerosos epítetos —transgresora, &ldquo;derechosa&rdquo;, lúgubre,  misógina—; empero, ninguno de ellos encuentra su justificación más exacta en el  anacrónico nominativo, otrora determinante —y determinista— de escritor<em> maldito</em>. <em>Outsider</em>, <em>outlaw</em>,  marginal: enmarcado en tal fuelle naufraga la escritura de Barón Biza. Se trata  del primer narrador argentino en introducir una seudopornografía y en hacer uso  de la violencia —discursiva y explícita— como su carta de presentación: &ldquo;¡Tú  eres un espermatozoide inútil en la vagina de la humanidad!&rdquo; (Barón Biza, 1933:57);  así lo desafía, impune, Sergio a Jorge Morganti, un antiguo amigo de la  infancia del protagonista de <em>El derecho  de matar</em>. El narrador no tolera semejante desatino y bajeza y opta por acabar  con la vida de aquel bajo una brillante descripción recubierta de un vuelo  poético que despierta el mayor de los goces estéticos: &ldquo;… Y mis dedos modelaron  en la carne de su garganta una estatua de justicia&rdquo; (<em>Ibídem</em>).<br />
  <br />
  Lo viril se erige como eje central  vehiculizante de la novela que nos ocupa. Cuando  ésta salió a la luz, en 1933, fue inmediatamente secuestrada por el gobierno de  facto y su autor puesto tras las rejas por motivos mayormente políticos que  literarios. Barón Biza, como protesta por el altercado, llevó a término lo que  su abogado defensor tildó como una &ldquo;protesta viril&rdquo; (pág. 9), a saber: una  huelga de hambre. Otra clara alusión fálica, encontrada asimismo en la biografía  del autor en cuestión, es el monumento —de 82 metros, mayor que el Obelisco—  con el que Barón Biza conmemoró a su amada Myriam Stefford, la aviadora sueca, que  se encuentra alojado geográficamente en Alta Gracia, provincia de Córdoba.<br />
  <br />
  El abogado del autor, Néstor I. Aparicio, defiende  la autonomía de la obra alegando la discutida tesis de que el texto se trata,  en realidad, de una &ldquo;defensa de los humildes&rdquo; (pág. 6), y que aquel lleva a  término una &ldquo;reproducción de escenas reales&rdquo; (pág. 7), enmarcándose en una  presunta tradición romántica que dictamina que el arte imita a la naturaleza.  Es en ese sentido en que <em>El derecho de  matar</em> pregona un verosímil de la cotidianidad; presenta una &ldquo;verdad&rdquo;. De  manera tal que la novela se postula a sí misma como obra realista. Lejos de  traer a Auerbach a colación con el propósito de discutir de qué se trata el  realismo literario, sí se puede esbozar, no obstante, la presumible tesis de  que la novela refleja de forma patente y cabal el primigenio subjetivismo  poético de su autor; lo que podría resumirse bajo la proposición de &ldquo;la poética  ideologizante de Barón Biza&rdquo;.<br />
  <br />
  A la manera baudelariana, tras la carta abierta  al Papa, el autor le habla al lector: &ldquo;No necesito tu aplauso, no temo tu  brazo, ni me hace falta tu dinero&rdquo;; &ldquo;[Este libro] Está hecho para los  haraposos, para los hijos de nadie, para los &lsquo;malnacidos&rsquo;, para los que tienen  por cabecera el tarro de basura, para los que no tienen Dios, ni hembra…&rdquo; (pp.  27-28). En el antepenúltimo párrafo, la prístina exhortación exclama: &ldquo;He  nacido rebelde, revolucionario, como otros nacen proxenetas o cornudos&rdquo; (pág.  29).<br />
  La madre, al igual que los cuadros pictóricos  de la Edad Media, que ilustraban a la Virgen María con un halo que la separaba  de los mortales, con los pies flotando en el aire es, en la novela, &ldquo;una  sublimidad virginal… muy lejana, remotamente lejana a todo lo que es terrestre,  a todo lo que es humano, a todo lo que es <em>mujer</em>&rdquo;  (pág. 32) (bastardilla nuestra). El padre de Morganti remata: &ldquo;La madre es  santidad… La mujer, delito…&rdquo; (<em>Ibídem</em>).  Se podría agregar: la madre es divinidad; la mujer, secularidad pecaminosa. La  mujer, entonces, aparece cosificada, como un objeto de presa: &ldquo;El acercamiento  más perfecto a la animalidad en donde la hembra, como el macho, reviviendo sus  instintos, pide, el uno al otro, ser humillada, esclavizada, martirizada…&rdquo; (pág.  44). Más adelante, dentro de una metáfora narcotizante, el narrador condena a  la &ldquo;hembra&rdquo;: &ldquo;Bajo la influencia del brillante polvo blanco, había llegado a  compenetrarse con su propia carne…&rdquo; (<em>Ibídem</em>).  De un ente cosificado deviene la animalización: &ldquo;Mujeres, impúberes algunas,  que en el acto procedían en idéntica forma que habían observado en los  animales&rdquo; (<em>Ibídem</em>).</p>
<p><br />
  En boca de Irma, la hermana menor del  protagonista, la religión es puesta en jaque: &ldquo;Madre, la religión la crearon  los hombres cuando, en sus cavernas, quisieron explicarse lo que es el rayo, el  brote de las flores o el mismo misterio de la vida. Era debilidad, cobardía,  ignorancia… Pueden haberse equivocado&rdquo;. A lo que la madre replica: &ldquo;No, porque  en el nombre de ese Dios enseñaron amor a los hijos, fidelidad al esposo,  resignación y piedad…&rdquo;. El diálogo cierra, naturalmente, con la chocante palabra  de la prematura hija rebelde: &ldquo;Los salvajes, las bestias mismas, sin conocer al  Dios que tú invocas, practican los mismos preceptos&rdquo; (pág. 37). Es decir, se  alude al pasaje del mito al logos, en donde la razón, el sentido, la palabra,  termina imponiéndose por sobre el precientificismo de la explicación sobrenatural,  explicación mágico-religiosa, del origen (<em>arché</em>)  del cosmos (orden); del origen del mundo, enmarcada, claro está, dentro de la  insoslayable división dicotómica: civilización-barbarie. A este respecto,  ulteriormente, y en consonancia con el fortísimo evolucionismo social profesado  por la eterna figura sarmientina, Morganti afirma, concluyente: &ldquo;Barbarie y  civilización: principio y fin de la existencia humana&rdquo; (pág. 58).</p>
<p><br />
  En lo concerniente de manera exclusiva a la  forma de la novela, habría que decir que, al igual que el contemporáneo Roberto  Arlt, Barón Biza hace uso de cierto lunfardo, estableciendo siempre, no obstante,  un distanciamiento, en el caso del segundo, feroz; de manera tal que  expresiones cotidianas como la de ser &ldquo;un buen partido&rdquo; o estar &ldquo;alzado&rdquo; por  una mujer, aparecen encomilladas. Sin embargo, a diferencia del canónico Arlt,  el desplazado Barón B. se encuentra más próximo a Borges en su elevado uso  lingüístico, el cual no parece dejar nada librado al azar. Por el contrario,  cada signo semeja estar meticulosa y laboriosamente premeditado.</p>
<p><br />
  En su fúnebre estilo sepulcral, el autor narra  el camino del héroe. Éste, el héroe, o mejor: el antihéroe, huye de la casa de  sus padres a muy temprana edad, se compromete con un personaje —femenino—  central en la obra: Cleo vivencia la más acérrima pobreza y luego, tras la  caída, revive de sus cenizas a través de la traición. Se relata, entonces, el  camino de un antihéroe: descenso y deshonra, seguida de un ascenso triunfal,  narrada a través de una especie de sistema aforístico: &ldquo;La humanidad no es  quizá sino la podredumbre de la tierra&rdquo; (pág. 46); &ldquo;La muerte individual  significa para la colectividad en general un beneficio&rdquo; (pág. 60); &ldquo;Has tenido  tu parte en el festín de la vida&rdquo; (pág. 61); &ldquo;La razón de vivir es la más fuerte  de todas las razones&rdquo; (pág. 64).</p>
<p><br />
  Abocándonos de forma exclusiva a la temática  sexual, tópico que, como la violencia —la muerte— se postula como principio y  fin de la obra toda, cabe señalar cierta ambigüedad que pareciera torturar al  autor/narrador. Dicha tensión puede, sin más, ilustrarse con un largo y  confidente pasaje: &ldquo;La humanidad está equivocada y lo peor es que sabe que está  equivocada. Usted, señora que me lee, confiéselo: ¡Cuántas noches de tortura en  su cama solitaria de soltera! ¡Cuántas ideas endemoniadas, cuántos coitos  fantásticos! ¡Cuántas veces ha abierto usted sus piernas vanamente!... Pero al  día siguiente, con sus nervios rotos, sombreadas trágicamente sus ojeras, se  sentirá fuerte ante su Cristo… ¡Basta ya!&rdquo; (pág. 48). El sexo, entonces, como  reivindicación ensombrecida por el infranqueable tabú que atraviesa la  retorcida mente eyaculadora de nuestro promiscuo personaje misógino. Con  respecto al matrimonio, apunta Morganti: &ldquo;Para vosotras [las casadas] no habrá  liberación: os ha condenado la iglesia y los hombres…&rdquo; (<em>Ibídem</em>). El hombre es un animal pulsional; la mujer, su perdición en  celos. </p>
<p><br />
  Aquí nos adentramos de lleno a la tesis central  del libro: aquello que nos diferencia de los animales, lo único que nos pone un  escalafón por encima de nuestros ancestros salvajes es el suicidio: el derecho  a matar.</p>
<p><br />
  Al reencontrarse con su hermana Irma, una  inocente y brillante joven devenida prostituta, Morganti se hace cargo de  aquélla y la lleva a vivir junto a él y a su prometida Cleo. Lo inevitable,  según la poética ideologizante de Barón Biza analizada hasta aquí, sucede: Irma  y Cleo se enamoran. Morganti cae presa de un delirio irrefrenable: &ldquo;debe&rdquo; matar  a las &ldquo;perras&rdquo;. Empero, el derecho de matar, como se vio en el párrafo  precedente, encuentra su humano origen arbóreo en el derecho al suicidio: &ldquo;Soy  más fuerte que Dios, voy a destruir, destruyéndome, esta agrupación de  espermatozoides desarrollados… Mi sola tristeza está en que no tendré ya  imbéciles que me ataquen…&rdquo; (pág. 75). La muerte suicida se abre camino y  Morganti, al igual que su creador, encuentra su fin en su mano armada que, tras  cruzar un proceloso y arduo camino, atestado de la tempestad más ominosa,  sella, de una vez y para siempre, su corrosiva mirada.</p>
<p><br />
  Por lo expuesto hasta aquí, puede afirmarse  categóricamente que Raúl Barón Biza es el imponente de su irreductible voluntad  de poder, el desafiante, el criminal: el gran maldito argentino.</p>
<p>&nbsp;</p>
