<div id=\"editorial\"> 

  <p>¡Que le corten la cabeza! La amenaza proferida por la Reina  de Corazones en las ocasiones más diversas, cotidianas e inverosímiles es a la  vez crítica al despotismo y exageración de los rasgos del poder, tanto como una  puesta en escena del desgaste de la orden que, finalmente, nunca es cumplida.  Si bien la amenaza, por sí misma, logra causar pavor en varios de los lacayos  que la rodean, otros bien saben de los mecanismos subterráneos de la  construcción del poder, los que desactivan la posibilidad de que la orden se  convierta en una ejecución real. Y un poco más allá: es otra de las formas que  el diácono Charles Dodgson, quien pasó a la historia con el seudónimo de Lewis  Carroll, usó para dimensionar el verdadero &ldquo;perder la cabeza&rdquo; de su clásico  Alicia en el País de las Maravillas. <br />
    <br />
    Si bien es el delirio onírico, rayano con el surrealismo más  combativo, de la (des)organización del mundo bajo la superficie terrestre lo  que pone contra las cuerdas a la niña Alicia, haciéndole sentir que ha perdido  la razón, la superposición de acontecimientos hará que la prepúber se deje  llevar por una lógica que por descabellada no deja de ser implacable. El  Sombrerero Loco y La Liebre de Marzo son dos de los más radicalizados miembros  de una sociedad en la que la locura sigue siendo un motivo de exclusión; un  &ldquo;encerrados afuera&rdquo; en esa campiña en la que celebran, día a día, los felices no-cumpleaños  de uno y otro; incluso de los visitantes que, como Alicia, llegan allí de  manera casi casual.<br />
    <br />
    Es que el poder, en la novela de Carroll, es parte de un  mecanismo inexplicable racionalmente; sus efectos, nocivos o no, no son el  punto en cuestión, están por fuera de la sencillez que exigen los personajes  que mueven los engranajes de la sociedad. Al punto de que el poder no deja de  llevar una vida paralela a lo que sucede en sus ámbitos de aplicación,  trasvasando órdenes, premios y castigos; llevando la batuta de la Justicia;  tomando las decisiones que afectarán el destino de todos y en el que la gran  mayoría de ese todo acata, convirtiéndose en el espectador de su propio  destino.<br />
    <br />
  Si tomamos como referencia segunda la versión libre de Tim  Burton, con el regreso de Alicia a ese país subterráneo que cree haber soñado,  parece ser necesaria la intervención de un Otro para desbancar a la caprichosa  Reina Roja. Podría ser un dato no menor: el extranjero que llega, libera y  repone en el poder a quien considera un gobernante más justo y deja a suerte y  verdad a aquellos a quienes liberó no deja de tener en nuestros días un fuerte  eco a la política exterior del Imperio Americano que ha dado paso a su  modalidad de <em>vengo, bombardeo y me voy</em>...  Y así es como el gestor de las últimas invasiones armadas detenta el premio  Nobel de la Paz. Cuestiones que nos hablan de un mundo realmente descabellado  en el que la amenaza de la Reina de Corazones aún se sigue correspondiendo con  las más abyectas guerras modernas.</p>
<p>&nbsp;</p>
</div>