<p>En varias conversaciones entre los  que hacemos ENEUR ha aparecido el enriquecimiento que produce la lectura de  libros, ficcionales o no, que narren lugares lejanos, geografías inhóspitas,  tiempos inaccesibles para la experiencia propia, en el pasado así como en el  futuro. <strong>Gentlemen</strong>, el volumen de  Mardulce que recopila los que presenta como los mejores escritos del dandismo  inglés es una ocasión para sumergirse en aguas   cuyos desbordes han penetrado todas las edades estéticas de su por venir.  Es, a la vez, continuidad y novedad; pues prosigue /complementa/completa al  libro del dandismo francés que la misma editorial publicara tiempo atrás, a la  vez que abre la lectura de textos pocos recorridos por el idioma español.</p>
 <p> Uno de los aciertos de la edición  es la inclusión de dos desconocidos para la mayoría del público lector, William  Hazlitt y William M. Thackeray, cuyos textos cargados de una fina ironía y un  punzante humor se dan estocadas con las disertaciones de Oscar Wilde sobre la  decoración del hogar y los modelos de Londres y la fineza narrativa con la que  Virginia Woolf pone en palabras la fineza estructural de Beau Brummel, el bello  dandi que cuya figura es el molde prototípico de todo dandismo. Transitar las  páginas de este libro es ir abriendo textos en los que estas características  emergen para construir narrativas frescas y reveladoras de un mundo.</p>
<p>El libro abre con los textos de  William Hazlitt sobre la falta de dinero, la lectura de libros nuevos y la  gente desagradable; en los que disecciona con la habilidad de un entomólogo  rasgos que por corrientes no dejan de ser un hallazgo. Y pone contra las  cuerdas algunos de los mecanismos superficiales del <em>modus vivendi </em>de su época, aunque la talla de sus palabras  permanezcan vigentes en la corteza del presente. Esa habilidad para la  supervivencia de la textualidad que suele ser tan (a)preciada:</p>
<blockquote>
  <p>  <em>No puedo comprender el afán que muestran los  lectores de este mundo por leer libros nuevos. Si el público hubiese leído todo  lo anterior, podría entender que no deseara leer dos veces la misma obra; pero  cuando pienso en los innumerables volúmenes que permanecen sin abrirse,  mirarse, leerse y reflexionarse, no puedo compartir las quejas patéticas que  oigo: que Sir Walter no escribe más; que las imprentas son ociosas; que Lord  Byron ha muerto. Si no he leído un libro antes, este es, para todos nuestros  propósitos, un libro nuevo para mí, sea que haya sido editado ayer o hace  trescientos años.</em></p>
</blockquote>
<p>  Y como si hubiera podido asomarse a  la aparición de la casi extinta fiebre blogger, arriesga:</p>
<blockquote>
  <p><em>Si con la difusión del conocimiento no  obtenemos más vastedad y elevación de miras, ¿de qué nos sirve? Si al separar  los nombres de las cosas no dejamos ni siquiera el nombre o la sombra de  excelencia, más valdrá dejarlos como están; pues es mejor tener algo que  admirar que nada: nombres, si no cosas; sombras, si no substancia; oropel, si  no oro. Ahora todos pueden leer y escribir por igual; y se presume, por tanto,  que con la misma destreza. </em></p>
</blockquote>
<p>Y acude a una particular forma de la  oración:</p>
<blockquote>
  <p>  <em>Recobra, pues, oh, cultura, tu túnica  pontificia; viste de orgullo y púrpura; une lo sagrado a lo profano; ejerce tu  autoridad sobre ambos mundos; en vez de trivialidades y revistas para  mecánicos, emite burlas y decretos; no pidas que se haga la luz, sino que se  manifiesten las tinieblas; cubre con una venda los ojos de los ignorantes y los  iletrados; amenaza con los terrores de la superstición y el despotismo; y por  tus dolores te bendecirán: los niños se descubrirán a tu paso, las mujeres te cortejarán,  los viejos se frotarán las barbas y tú gobernarás con mano de hierro a la  servidumbre, los payasos y los nobles.</em></p>
</blockquote>
<p>En la misma línea narrativa se  encuentran las palabras del otro William de la compilación; Thackeray quien en  1848 publicó el <em>Libro de los Snobs</em> y  que revuelve el avispero de la simulación que disfraza la insatisfacción de  darle importancia a aquello que no lo tiene; escarba en la mimética de la  imitación; expone las llagas de la &ldquo;necesidad&rdquo; de ser lo que no se es: el hueco  donde calza el puño de la publicidad moderna, entre otras cosas.  Concluye, en su apartado sobre los snobs de  la realeza, tomando como modelo a un joven noble:</p>
  <blockquote>
    <p><em>Supongamos que es un idiota: a  pesar de ello, gracias a la gloriosa Constitución, es bastante bueno para gobernarnos.  Supongamos que es un caballero honrado y de alma superior: tanto mejor para él.  Pero puede ser un asno y, sin embargo, será respetado; o un rufián y, sin  embargo, será extraordinariamente popular; o un pícaro y, sin embargo, se  encontrarán excusas para él. Los snobs lo adorarán todavía. Los snobs lo  honrarán y las snobs lo mirarán cariñosamente, por muy repugnante que sea.</em></p>
  </blockquote>
<p>En el tramo final, dos conferencias  de Oscar Wilde que son una buena oportunidad para entregarse, a su discurrir  sobre la estética por fuera del registro ficcional. En la primera, <em>Decoración del hogar</em>, se dirige al  público estadounidense y abre con una tajante conclusión sobre el arte que  necesitan los Estados Unidos:</p>
  <blockquote>
    <p><em>Cuando me presenté antes ustedes en la  ocasión anterior, aún n había visto nada del arte estadounidense, salvo las  columnas dóricas y las chimeneas corintias visibles en la Quinta Avenida y en  Broadway. Desde entonces, he recorrido el país; he estado, creo, en cincuenta o  sesenta ciudades diferentes. Me parece que lo que su pueblo necesita no es un  arte demasiado imaginativo, sino uno que santifique los floreros de uso diario.</em></p>
  </blockquote>
<p>    Lejos de pintar el mundo a través  de su aldea, Wilde encaja su posición en el lugar donde no le es precisa una  metáfora del mundo, sino que disecciona los tejidos más finos de su tiempo  histórico. Su texto <em>Modelos de Londres</em> es un recorrido por las estructuras subjetivas y sociales de quienes se ganan  la vida modelando para pintores, para desembocar; justo en el momento de la  profesionalización del estar posando. </p>
  <blockquote>
    <p><em>Los modelos profesionales son una invención  moderna. Para los griegos, por ejemplo, era algo desconocido. (…) De hecho, el  modelo, tal como lo entendemos en la actualidad, es una creación directa de las  escuelas académicas.</em></p>
  </blockquote>
<p>    Trazando a grandes rasgos a los  modelos de un puñado de nacionalidades, desemboca en la peculiaridad de los  modelos ingleses del victorianismo tardío:</p>
  <blockquote>
    <p><em>Por lo general, la modelo de hoy en día es  una joven bonita, de entre doce y veinticinco años, que nada sabe de arte, que  le importa aún menos, y que simplemente está ávida por ganar siete u ocho  chelines al día sin demasiados problemas. Cuando están cansadas, el artista  sensato les da un respiro. Entonces ellas se sientan en una silla y leen  horrores de a un penique, hasta que son sacadas de la tragedia de la literatura  para retomar nuevamente su lugar en la tragedia del arte. </em></p>
  </blockquote>
<p>    El cierre de la compilación es el  exquisito texto de Virginia Woolf, <em>Beau  Brummel (o el arte de hacer la corbata llevado a su perfección)</em>, cuyo eje  es la vida del dandi más dandi de todos los tiempos. Un texto breve que es una  semblanza precisa, ajustada, que parece no dejar nada de lo importante fuera.  La prosa de Woolf pone al dandismo en la cresta de su propia ola; con la  delicadeza, el cuidado y la prolijidad que ciñen, en cualquiera de sus  vestiduras, los filos de lo real.</p>
  <blockquote>
    <p><em>Y a menos que ese mundo cayera en ruinas, su  reino parecía asegurado. Apuesto, sin corazón y cínico, el Bello Brummel  parecía invulnerable. Su gusto era impecable, su salud admirable y su silueta  más bella que nunca. Su reinado había durado muchos años y sobrevivido a  numerosas vicisitudes. La Revolución Francesa le pasó por encima de la cabeza  sin desordenarle ni uno solo de los cabellos. Había aparecido y desaparecido  imperios mientras él experimentaba con el pliegue de un fular y criticaba el  corte de un abrigo. Ahora acababan de batirse en Waterloo y volvía la paz. La  guerra lo había dejado intacto: fue la paz la que lo derrotó.</em></p>
  </blockquote>
  </p>
