<p>Es general. Esta es nuestra era. La posmodernidad aterradora. La manivela de la  hecatombe. El tinte excéntrico de la pantomima. Esta es la era que nos toca vivir,  ¿y? Apocalípticos e integrados dijeron por ahí. ¿Apocalípticos o integrados?, me  pregunto yo. Pero siempre fue así. Ana dice que ahora el mundo está por llegar  a algún tipo de bisagra, ¿qué puede saber? Es joven, demasiado joven. Yo decía  lo mismo a su edad. Y tampoco creía en Dios. Pero ¿qué me iba a quedar por  decir a mí? ¿Qué me quedaba por creer? Descarriada por parte de padre,  prostituta por parte de hermano. De la madre mejor ni hablar. </p>
<p>Es así. La  sensación de inminencia, dice Ana. La sensación de que todo se está yendo a la  misma mierda en cualquier momento. Las dos actuamos en los teatritos de acá  mientras el mundo se cae a pedazos. Mientras las putas siguen siendo putas, los  pajeros siguen siendo pajeros, las esposas siguen siendo imbéciles. </p>
<p>Apocalíptica:  el mundo es una mierda. </p>
<p>Integrada:  el mundo es una mierda. </p>
<p>¿Quieren que  les cuente? No es una cuestión de cuándo empezás, sino de con quién. Quién es  el pajerito atomatado e insufrible que te coge. Fabricio se llama. Mi hermano.  No me cogió, eh. Cinco minutos me hizo esperar hasta que contestó el teléfono y  me escuchó del otro lado preguntándole qué carajo era todo. ¿A dónde mierda iba  la cuestión? El otro pelotudo me esperaba sentado en su silla de magnate  precoito, precoz, precavido, premorbo. Yo, al teléfono. No sé. 16 años casi. <em>Fabricio  cicatrizando su homosexualidad en alguna pieza de hotel. Fabricio derrochando  su alegría, su audacia en su risa fraternal y expectante. Tal vez hasta algo  papeado. Fabricio vendiendo, comprando, usando</em>. Mi papá siempre quiso un  varón en la familia. Lástima que nunca lo tuvo. </p>
<p>Apocalípticos  e integrados. Sillones de cuero, limusinas, fiestas, olor a sexo, intriga.  &ldquo;¿Qué te pensás, nena? Eso es el mundo. Despertate&rdquo;, cuando finalmente atendió  el teléfono. Y siguió en su bomba de tiempo contra la desidia y la depresión.  Homo hasta la masmédula, en literatura. Puto descuidado. Así murió: un &ldquo;cliché&rdquo;  se dice en el barrio de las esposas que siguen siendo imbéciles. </p>
<p>Apocalípticos.  Pero me gusta. Virgen hasta el primer magnate. Virgen hasta que el puto me dio  cobijo. Hasta que el puto sentenció: &ldquo;Esto es el mundo, nena, o ¿qué te  pensabas?&rdquo;. Esto es el mundo. No le quise decir que yo fui el único hombre de  la familia. Pero me gusta. A la segunda vuelta le tomás el gustito. Es como  chupársela a alguien con leche rancia. Primero no sabés si escupir o vomitar.  Si largarte a llorar o quedar paralizada. Después lo rancio es dulce. Y lo  dulce se hace único. Integrada.</p>
<p>Pero el  mundo te golpea y quedás en la calle Pinzón, varada con un saco de muerte y una  foto en blanco y negro. Quedás sumergida en las tinieblas de La Boca y el  bolichín del Blues, donde ahora escuchan a Chayanne. Cogés y te cogen. Este no  es el mundo, Fabricio. Este sos vos y yo. De puta casualidad conocés a alguien  que dice que te ama. Ah..., el mundo ahora es una incoherencia. Un cínico en  patineta. Esa no me la avisaste Fabri. </p>
<p>Pero me  gusta. Me gusta el desenfreno de la miseria. Lo prefiero a las que me dicen que  lo hacen por sus hijos, o porque no tienen otra opción. En el fondo no les  creo. Y me gusta cómo juzgan, cómo el mundo les mete en la cabeza el escopetazo  hacia el otro. Me gusta cómo ríen y lloran. Como dijo un dramaturgo: &ldquo;qué  rápido se pasa del pavo real a la cucaracha&rdquo;. Apocalíptica. </p>
<p>Este es el  mundo. El que se va a la mierda. El que siempre está por irse a la mierda y,  como venganza (¿divina?), sólo dobla la esquina y se expande, se amplía,  intoxica. Ana no tiene razón. No es un tiempo de bisagra. Es la grieta eterna,  la puta reventada que nunca revienta, la esposa miserable que nunca llora, los  engaños y los engañados que se la bancan, el amor de los que dicen que se aman  y mienten, la soledad satánica como la espada de Damocles sobre las cabezas, el  budismo repentino. </p>
<p>¿Apocalípticos o integrados? Ni uno ni lo otro. Mierda. </p>
