<p>La editorial Mármol Izquierdo nos presenta el tercer  libro de la serie Territorios referidos al trabajo de traducción de los  manuscritos de Freud. Luego de &ldquo;<em>El Yo y  el Ello</em>&rdquo; y &ldquo;<em>Das Unheimliche</em>&rdquo;, es  el turno ahora de &ldquo;<em>Más allá del principio  de</em> <em>placer</em>&rdquo;, tal vez el texto más  importante dentro de la historia del psicoanálisis. El trabajo de revisión,  presentación, articulación, comparación de textos y comentarios de Juan Carlos  Cosentino nos brinda una edición de casi 900 páginas en donde nos encontramos en  forma directa con la letra de Freud, su modo de trabajo, la construcción de su  teoría, pero también sus vacilaciones, sus especulaciones y fundamentalmente su  estilo. El mismo Cosentino nos cuenta en la presentación<em>: </em></p>
<blockquote>
  <p><em>Abordamos nuevamente la construcción que realiza Freud de Jenseists des Lustprinzips. En esta  oportunidad partimos de los manuscritos conservados, es decir, de las dos  versiones alternativas y los comparamos con los textos finalmente publicados.</em><em>La difícil  travesía por el texto manuscrito consistió, primero, en examinar el texto en  alemán de la segunda versión escrita a máquina cotejándolo con el escrito  publicado y, posteriormente, en establecer el texto en alemán de la versión  manuscrita con tipografía &ldquo;gótica&rdquo; comparándolo con la versión a máquina. </em><br />
    <em>Acto seguido,  siguiendo la nueva traducción que habíamos realizado en 2003 del texto  publicado de Jenseits, Susana  Goldmann preparó la traducción al castellano de ambas manuscritos. Por mi  parte, intervine en su revisión, articulaciones, comentarios, en la comparación  entre las tres versiones con sus reediciones y en las notas introductorias.</em><br />
    <em>Al recorrer sus  múltiples versiones -los dos documentos del manuscrito, un texto publicado y  tres reeditados- se descubren las dificultades que enfrenta para sostener un  punto de inflexión en su teoría que suele situarse en torno a un texto y a una  fecha: &ldquo;Más allá del principio de  placer, el giro de 1920&rdquo;.  Lo que me permitió revisar los ejes de cada capítulo en el Anexo de esta  publicación.</em><br />
    <em>La primera  versión escrita a mano consta de 34 páginas y sólo tiene seis capítulos  señalados con números romanos. Aún no existe el nuevo capítulo VI de la versión  impresa que añadirá con el documento mecanografiado. Razón por la cual, sin el  eje del ensayo, el manuscrito escrito a mano no puede considerarse un  &ldquo;borrador&rdquo;. Es, más bien, una versión alternativa que luego le resultó  insuficiente.</em><br />
    <em>La segunda está  encuadernada en rústica, tiene tapas duras y lleva el apellido del autor y el  título inscripto en el lomo en letras doradas. Se trata del manuscrito que le  regalara a Max Eitingon quien lo había hecho encuadernar. Se compone, en su  mayor parte, de hojas escritas a máquina que presentan múltiples correcciones.  La principal diferencia consiste en la composición de un nuevo capítulo de 27  páginas escritas a mano (el capítulo VI de la versión impresa) que es  constitutivo para la estructura del ensayo y acarrea importantes modificaciones  en el antiguo capítulo VI, transformado en VII.</em><br />
    <em>De la primera  versión el último dato que se tiene es de fines de septiembre de 1919. Luego,  durante un tiempo, no se habla más de la suerte del manuscrito. Recién el 25 de  mayo de 1920 -a principios de ese año habían fallecido su hija Sophie inesperadamente  y su amigo Anton von Freund- Freud mencionó que estaba trabajando de nuevo en  la obra. Parece tratarse de la segunda versión. Y el 18 de julio anunció que el  Más allá estaba terminado.</em><br />
    <em>Las dos  versiones preparatorias deben ser leídas como documentación de un proceso de  reflexión en curso cuyas modificaciones prosiguen durante la corrección de las  pruebas de galera y no se detienen, ni siquiera, con la primera publicación en  1920: continúan en las reediciones de 1921, 1923 y 1925.</em></p>
</blockquote>
<p>Una  edición fundamental e insoslayable para quien pretenda estudiar con seriedad la  obra de Freud y sus formulaciones en estado naciente, en donde nos encontramos  con la marca de pensamientos urgidos por lo real del psicoanálisis. La edición  crítica bilingüe que nos presenta Juan Carlos Cosentino es una joya que nos  transmite que la  obra de Freud está más  viva que nunca. </p>
