<p>Las golosinas son una buena y rica costumbre. Y si son literarias, además de no poder ser acusadas de causar caries, le abren a nuestros niños mundos para recorrer, conocer y reinventar. Para el número 36, nuestra más pequeña colaboradora se puso bajo el brazo tres títulos de su más reciente cosecha como lectora y escribió, con sus propias palabras y manitas, estas breves reseñas para que sean leídas por pares y padres.</p>

<div class="breves"><div class="image_cen3"><img src="images/601.jpg"></div><strong>Cuentos exactamente así</strong>, de Rudyard Kipling ¬ Diada, 2014<br /> 

Rudyard Kipling escribió estos cuentos para su hija Josephine que estaba enferma de gripe. La gran mayoría de las historias tienen como protagonistas a animales y, en general, explican alguna característica de esos animales como, por ejemplo, por qué el leopardo tiene manchas; de dónde salió la joroba del camello; por qué el elefante tiene trompa larga. Algunos cuentos terminan con una enseñanza o poesía. En el cuento del alfabeto los personajes son un padre y una hija que inventan el alfabeto para que no haya confusiones cuando tienen que pedirle algo a alguien. </div>

<div class="breves"><div class="image_cen3"><img src="images/602.jpg"></div><strong> Excesos y Exageraciones</strong>, de Pablo Bernasconi ¬ Sudamericana, 2013<br />
En estos cuentos excesivamente exagerados, el autor cuenta historias disparatadas en las que presenta personajes divertidos y locos a los que le suceden cosas extrañas. Entre las que más me gustaron están: "La corneta emancipada" en la que un músico tiene 125 trompetas unidas, de diferentes calidades, sumando un total de 412 metros de conducto; y el “Multiple choice”, un robot que te da opciones para marcar. Yo elegi éstas:<br />
Hacer un café(cargadito); lavar sábanas de fantasmas; peinar erizos; servir platos voladores; disolver miedos; contar hormigas rojas; desenredar pulpos; guardar olores; amaestrar corazones; convertir pelotas en dados; curar el hipo; grabar pesadillas; ganar sorteos; servir el desayuno; viajar en el tiempo; hacer pelucas; pesar nubes; pintar mariposas y responder cuestionarios.</div>

<div class="breves"><div class="image_cen3"><img src="images/603.jpg"></div><strong>De familia en familia</strong>, de José Nesis y Paula Szuster ¬ iamiqué, 2015<br />
Este bello libro de cuentos de José Nesis y Paula Szuster trata de diferentes familias y al mismo tiempo iguales. ¿Qué se cuenta? En estas historias se cuenta la vida de sus personajes por ejemplo “Carola, la ayudante de maestra, que es una fan absoluta de Madonna” o “Santiago que vive con sus abuelos porque sus padres viajan por todo el mundo”. A mí las vidas que más me gustan son la de Julia, a la que cuida Isabel, la misma que cuidó a su mamá cuando era chica; Javier, que pasa algunos días con su mamá y otros con su papá; Camila, que tiene las pecas de su mamá y los rulos de su papá; Zoe, que vive con su mamá, su iguana y su gata; y Sol, que pasa los fines de semana en pijama.</div>
