<p>De carácter apocado, de una extrema simpleza intelectual basada  en una férrea creencia en Dios y una propensión al &ldquo;sí-bwanismo&rdquo; fácil, Anton  Bruckner (Austria, 1824-1896) fue un gran compositor romántico que quedó  diluido en las sombras de monstruos como su amado maestro Richard Wagner,  Johannes Brahms, Frantz Liszt y su propio alumno de armonía, Gustav Mahler. Fue  esa misma forma de andar por el mundo, tímida y anacrónica, la que también  propició que reescribiera en varias ocasiones las que han sido sus obras más  personales: sus ocho sinfonías completas y la novena, pospuesta e inconclusa al  momento de su muerte, en pos de los retoques que le fueron &ldquo;exigidos&rdquo; para las  anteriores.<br />
  <br />
  Nacido en una familia campesina de Austria, su padre era maestro  de escuela y organista en la iglesia local y fue el primer contacto del niño  Anton con la música, la que abordó de forma autodidacta; aunque luego accedió a  los estudios formales que sostuvo hasta sus cuarenta años. Si bien la música y  la docencia le fueron transmitidas al punto de hacerlas propias, sus refinadas  creaciones sinfónicas, misas y motetes religiosos le hicieron ganarse lugares  que ningún otro de sus colegas más descollantes lograron, como el reconocimiento  académico y la silenciosa adjudicación de haber sido el responsable de pulir definitivamente  la sinfonía como composición.<br />
  <br />
  En un ambiente musical en que las tensiones entre los  románticos ponían a los compositores en lo alto del podio o en la picota,  Bruckner llevó todas las de perder. Objeto de burlas por su forma de ser,  cuando los románticos aumentaron la brecha poniendo de un lado a Wagner y del  otro a Brahms, el buen Anton le dedicó su estupenda Tercera Sinfonía al creador  del concepto &ldquo;obra de arte total&rdquo;, ganándose los ataques más feroces y  demoledores de la crítica antiwagneriana que encontraba en él un blanco fácil.<br />
  <br />
  Su obra sinfónica le aportó a la teoría musical la  reformulación definitiva de la forma sonata, empleada habitualmente en los  primeros movimientos sinfónicos, que fueron introducidos por Wolfgang Amadeus  Mozart y Jospeh Haydn, para ser desarrollados <em>in extremis</em> por Ludwig van Beethoven, de gran influencia estética y  musical en la obra de Bruckner. La diversidad de familias de instrumentos  usados en sus orquestaciones, la torsión de la armonía romántica, sus tiempos  laxos y dilatados en conjunción con explosivos clímax, el uso virtuoso del  contrapunto y la belleza melódica de su música son razones más que válidas para  sumergirse en un recorrido que proponemos sea hecho en forma diacrónica para  poder capturar el continuo crecimiento composicional y la creciente amplitud tímbrica  de un creador único.</p>
 
<p>
  Anton Bruckner "Symphony No. 3"  <br />
	Berliner Philharmoniker, 1980 <br />
    Director: Herbert von Karajan
</p>