<p>Hace un rato llegué de la celebración  del día del tango en la plaza de Lomas. Tocaron varias orquestas y hubo milonga  en la calle, además de la feria de las colectividades con sus artesanías y sus  comidas típicas.&nbsp;<br />
  <br />
  Tengo por hábito escuchar al menos un  tango al día. Como una suerte de píldora que me hubiera recetado algún doctor  canyengue. Pero una cosa es la soledad de mi madriguera y otra muy diferente  cuando a uno le toca presenciar la comunión del vecino con su prójimo a través  de la música, bailando en el medio de la calle, siendo la música, siendo  quienes deberíamos ser.&nbsp;<br />
  <br />
  En lo personal debo decir que cualquier  tipo de danza me resulta inexpugnable, soy un patadura desde la adolescencia y  no reniego de mi condición. El tango me ayudó a descubrir otro tipo de belleza,  otra faceta creativa: un lenguaje que antes ignoraba por completo, un lirismo  que me llenó de asombro la niñez.&nbsp;<br />
  <br />
  En mi casa, había un disco que me  volvía loco; allí desfilaban cantores y orquestas y se escuchaban versos como  &quot;tus tangos son criaturas abandonadas que cruzan por el barro del  callejón&quot; o &quot;tu piel, magnolia que mojó la luna&quot;, cosas así, una  locura. Yo empezaba a darme cuenta que el relator de fútbol de la radio, el  carnicero que se quería chamuyar a una clienta o mi tía que escuchaba a Palito  Ortega no hablaban así. Confusamente sentía que en esas canciones había  &quot;otra cosa&quot;.Tenía 6 o 7 años y en la escuela me decían que existía  algo que se llamaba poesía pero no lo identificaba con lo que sonaba en aquel  disco de mi papá. Y es que seguramente, el tango es el legado más grande que me  dejó mi viejo. Por eso, hace un rato, mientras la gente bailaba en plena calle  me acordé de las fiestas en casa, cuando él y mi vieja y también mis abuelos se  lanzaban al patio a &quot;sacarle viruta al piso&quot; con La Yumba o Bahía  Blanca. Por eso me acordé de mi abuela cantando &quot;Desde el alma&quot;  mientras lavaba la ropa sobre la tabla con un ladrillo de jabón Federal, o de  mi mamá preparando el tuco del domingo y canturreando &quot;Los cosos de al  lao&quot;. Qué sé yo, hoy es el día del tango porque algunos sostienen que debe  haber un día para todo pero para mí el tango es un misterio que está siempre  presente. De lunes a lunes.<br />
  <br />
  Los últimos años con mi viejo fueron  imposibles; ya estaba rechiflao en su tristeza y por obra y gracia (?) de  extrañas alquimias, esa tristeza se transfiguró en frustraciones y enojos que  apuraba de un trago en un repetido vaso de licor. Fueron tiempos muy peliagudos.<br />
  <br />
  Sin embargo, prefiero volver al patio  con las parejas bailando bajo la glicina, bajo las estrellas de la orquesta de  Caló, bajo la mirada de un Dios que toca el fueye universal y cierra los ojos,  así como Pichuco.<br />
  <br />
  Una tarde, mi padre me contó que  aquellas canciones las había escrito un señor con el alma en orsai, que se  llamaba Homero Manzi, que había vivido en Pompeya, que se había enamorado  locamente de una cantante muy famosa. Después uno crece y se olvida de todo,  hasta que una noche, por ejemplo, en la plaza de Lomas (en el mismo lugar donde  lo vi a Pugliese a fines de la década del ochenta) la gente baila y se  divierte, y viene mi sobrinita de 3 años a pedirme que baile con ella, que ella  me enseña, y me dice que me muevo como un mono y los dos nos reímos, y mi  viejo, que anda por ahí, deja el escabio por un rato y me vuelve a explicar  quien fue Manzi para intentar saber quién soy yo.</p>
<p>&nbsp;</p> 
<?php
	include('11player.php');
?>