<p align="right"><em>Nada tenemos  que hacer con tus cánones, </em><br />
  <em>índex, pecados,  confesionarios, clerigalla; </em><br />
  <em>pensamos en  otra guerra, en una guerra </em><br />
  <em>contra ti,  Papa, perro.</em><br />
  Antonin Artaud</p>
<p align="right">&nbsp;</p>
<p><strong>Restauración y  gobierno de los corazones</strong><br />
  Un sacerdote cumple primordialmente una función mediadora. Es  el vínculo que intenta mantener unidos a la divinidad y sus fieles, es la pieza  que pretende articular una relación posible entre el hombre y su creador. El  sumo sacerdote de la iglesia católica lleva inscripto este significado en su  nombre: Pontífice o <em>Pontifex</em>, el que  construye puentes. Más allá de los excepcionales momentos en que la divinidad  se comunica directamente con aquellos a quienes ha castigado, su todopoderosa  presencia se manifiesta como palpable ausencia. La relación posible con el  salvador es, para la iglesia católica, necesariamente intermediada y la figura  papal es la encarnación máxima de esa mediación sacerdotal. <br />
  <br />
  Tengamos  presente la profunda crisis de legitimidad que la iglesia católica estaba  sufriendo antes de que nuestro Jorge Bergoglio deviniera el Papa Francisco. Esa  crisis incluía iglesias vacías, éxodo de fieles hacia otras ofertas religiosas,  fuertes críticas por los sistemáticos abusos de menores (y su sistemático ocultamiento),  corrupción económica y un largo etcétera. Sabemos también que Joseph Ratzinger  no era una figura que pudiera mejorar ese problema y que, por el contrario, lo  agravaba. La histórica jugada por la cual Ratzinger renuncia y asume Bergoglio resultó  un enorme éxito, su objetivo: restaurar la función pastoral. Para cumplir esta  importante misión, sólo hubo que mostrar que la cabeza de la iglesia es  coherente con los valores del amor compasivo que el cristianismo pregona. <br />
  <br />
  No  queremos discutir en este punto si esa coherencia es tal o simplemente se trata  de una cuestión de gestos, algo así como una gran operación de prensa (que  incluye esta vez Twitter y toda la parafernalia mediática contemporánea que  usan las grandes empresas); después de todo, lo simbólico puede ser aún más  fuerte que lo material respecto a la propagación de valores morales. Pero lo  que nos importa subrayar es que, más allá del contenido de estos valores, lo  que se restaura es un tipo de dominación.<br />
  <br />
  Afirma  León Rozitchner en <em>Freud y el problema  del poder</em>: &quot;Cada sujeto, en las instituciones, que son para Freud  masas artificiales, está primero sometido a una relación de dependencia  individual, uno a Uno, con su jefe, general, sacerdote o Cristo. Porque los  prototipos de masas artificiales que Freud describe son la iglesia y el  ejército. Y porque primero están sometidos uno a Uno al jefe, están luego, en  un segundo momento, reconocidos entre sí como igualmente sometidos. La relación  de sometimiento individual es el fundamento de la forma colectiva en la masa  artificial&quot;.<br />
  <br />
  No  es necesario leer a Freud o a Rozitchner para dar cuenta de esto, para  cualquier cristiano tiene que estar muy claro: el amor divino es el garante del  amor al prójimo. De un modo cuasi platónico (por algo dijo Nietzsche que  &quot;el cristianismo es platonismo para el pueblo&quot;) participamos del amor  divino cada vez que amamos a nuestro prójimo y, en ese sentido, no hacemos más  que afirmar la relación de dominio. Ese amor divino es previo y fundante  respecto al amor fraterno. El amor del Padre es condición de posibilidad del  amor entre hermanos. Para decirlo de otra manera, la relación fraterna supone  al Padre y pasa siempre a través de él. No hay puente que se pueda construir en  la horizontalidad sin que sea un ramal subsidiario del gran puente que lleva al  ápice de la autoridad máxima.<br />
  <br />
  Cualquier  relación fraterna, solidaria, caritativa, cualquier &quot;buena&quot; acción  respecto al prójimo aceita los caminos de sumisión respecto al Padre y cancela  a un tiempo otras posibilidades de solidaridad, de fraternidad, de vínculo no  mediado por el Padre. Las ovejas del rebaño se cuidan unas a otras. ¿De qué? De  seguir siendo ovejas en un rebaño, de no descarriarse, de seguir al pastor, de  seguir al Padre. Esta estructura de dominación no cambia si el Papa se viste de  blanco en lugar de vestirse de dorado, por el contrario, se refuerza la iglesia  católica, una institución jerárquica que se caracteriza por decidir en pequeños  conciliábulos lo que dará de comer en forma de papilla predigerida a millones  de fieles.<br />
  <br />
  La  restauración de la función pastoral es la restauración del vínculo de  dominación y, como tal, no puede ser nunca liberadora, no importa el contenido  con el que se presente. Tampoco puede ser &quot;buena&quot; en tanto la función  de dominación se oculta en el modo del &quot;amor&quot; y la  &quot;salvación&quot;. No queremos festejar que el Padre ahora es  &quot;bueno&quot;, queremos dejar de depender del Padre para pensar, actuar y  relacionarnos, y esto es mucho más difícil si todos (católicos y no tanto)  festejan como huérfanos reintegrados a la familia: &quot;¡Papá es bueno! ¡Papá  es bueno!&quot;. Preferimos la orfandad sin Salvador. La orfandad de valores  (el nihilismo) no obliga a aceptar al primer &quot;padre bueno&quot; que  aparezca a ofrecernos su nutritiva papilla predigerida. Queremos más bien cocinar  nuestro propio puchero y tener estómagos fuertes para incorporar el mundo a lo  que somos, de acuerdo a nuestra propia corporalidad. <br />
  <br />
  ¿Cómo  realiza Francisco este trabajo de restauración de su poder? Se muestra como un  buen cristiano: humilde, amoroso, débil (&quot;recen por mí&quot;) y, emulando  lejanamente las conductas de los santos, realiza una serie de gestos rituales  mediante los que se distingue de gran parte de la curia y, por supuesto, de los  fieles. Visita a los presos, come con los indigentes, renuncia a parte del  lujoso ornato vaticano, se acerca de este modo al gesto que dios mismo realizó  al descender como su hijo a los hombres para sufrir con ellos y, en última  instancia, por ellos.<br />
  <br />
  La  autoridad de la iglesia pretende funcionar con asiento en el corazón de los  hombres. Y el momento propicio parece ser el &ldquo;vacío de valores&rdquo; propio del  capitalismo contemporáneo. Francisco se ha vuelto un abanderado de la crítica  al avance de las desigualdades y el frívolo exhibicionismo de los lujos  generados por el actual entramado de producción y finanzas. Intentando hacerse  de esos corazones huérfanos, entregados a la explotación directa o a la  competencia consigo mismos en el mundo del emprendedorismo neoliberal, la  iglesia ordena y neutraliza así otras posibilidades de experimentación para  esos corazones. <br />
  <strong><br />
  <br />

   <span class="image_cen1"><img src="images/201.jpg"></span> Recepción y política  local</strong><br />
  La  nueva figura papal no solamente sedujo a los fieles de su iglesia. Después de  todo, además de la genuina alegría que deben sentir muchos católicos por contar  con un líder de estas características, Francisco les ha resuelto un enorme  problema personal que muchos sufrían sinceramente: la contradicción de  pertenecer a una institución que predica el amor entre los hombres pero está  manchada hasta sus entrañas de odio, mentiras y violencia física y simbólica.  El giro &quot;progresista&quot; del nuevo pontífice parece disolver para muchos  este inconveniente y, borrando de un plumazo una historia que nunca tuvieron  mucha intención de investigar o recordar, pueden ahora reconocerse sin  remordimientos como miembros de esa organización. Cuando alguien es tan  bienvenido como Francisco, debemos sospechar que viene a solucionar una tensión  que era demasiado fuerte, de tal modo que cuando el personaje llega, la  incondicionalidad del apoyo es proporcional al alivio manifestado.<br />
  <br />
  Aun  los que no pertenecen a esta institución, pueden ahora callar, transigir o  tolerar con menos culpa los avances y las intromisiones de la iglesia católica,  que utiliza su renovado poder para imponer concepciones sobre la vida, la  moral, la política y la educación, mucho más allá de las fronteras de su  incumbencia doctrinaria. Este&nbsp;<em>modus operandi</em>&nbsp;puede verse  seguramente en otros países, pero la influencia local se acentúa aún más al  tratarse del Papa argentino con el que todas las facciones políticas quieren  tener buenas relaciones.<br />
  <br />
  Sin  embargo, la primera recepción fervorosa de la comunidad católica argentina  comenzó a fragmentarse cada vez más, a medida que Francisco dejaba en claro que  muchos de quienes festejaban su nombramiento llevaban vidas más cercanas a la  de los &ldquo;mercaderes del templo&rdquo; que a la de Jesús. Particularmente agudo fue el  golpe para un ala conservadora del catolicismo local, que comenzó a tildar a Francisco  de &ldquo;Papa populista&rdquo; o &ldquo;Papa peronista&rdquo;. La prédica de una iglesia pobre para  los pobres no condecía con el rol que jugó la cúpula de la iglesia local y su  connivencia con las páginas más tristes y sangrientas de nuestra historia. Por  otro lado, el intento de controlar los excesos del capitalismo para darle &ldquo;un  rostro humano&rdquo; pero sin discutir sus fundamentos ni alentar otro tipo de  construcciones políticas, acercó las posiciones de la iglesia con algunos  sectores del peronismo, quienes hoy cuentan con un apoyo explícito de su  santidad para con varias de sus políticas y candidatos.<br />
  <br />
  ¿Habrán  comprendido así los sectores más conservadores del catolicismo local que todo  Papa es político? ¿Habrán comprendido los sectores más progresistas del  peronismo cuánto de paternalismo salvífico atraviesa sus propias prácticas  políticas? No creemos que esta experiencia alcance para que se arribe a esta  conclusión, siempre es más cómodo suponer que el caso que no conviene a nuestra  posición es una excepción y no una regla. ¿Habremos comprendido que si no  creamos nuestras propias formas de vincularnos y ser con los otros, algunos se  arrogarán la función de hacer esos puentes por nosotros? </p>
