<p>A metros de la    Casa Rosada, junto a la estatua de Juan de  Garay, Buenos Aires ostenta desde 1919 un retoño del más que secular Árbol de  Guernica, emblema sagrado de las libertades vascas. Anterior incluso a la  existencia de España como estado nación, a partir de Isabel y Fernando los  reyes acostumbraban jurar bajo su sombra venerable respetar los fueros de  Euzkadi.</p>
<p>  Acentuando  su fuerte simbolismo, ese magnífico roble sobrevivió, en medio de un hito  legendario, la Guerra Civil española (1936-1939), a otro hecho de trágica  resonancia. El 26 de abril de 1937 la vieja villa de Guernica fue literalmente  reducida a polvo, junto con buena parte de su población, por los flamantes aviones  nazis de la Legión Cóndor.<br />
  <br />
  Porque  el 18 de julio de 1936, militares conducidos por Francisco Franco se sublevan  contra la legítima República española. Controlados y muchas veces vencidos por  el pueblo en armas, los milicianos recuperaron en Madrid su principal reducto,  el Cuartel de la Montaña. Así  comenzó la última guerra de hombres, y la primera contra el fascismo. Contra  los fascismos, que reaccionaron de inmediato.<br />
  <br />
  Del  principio al fin, Hitler y Mussolini cooperaron con la rebelión enviando sus  mejores tropas y modernos adelantos bélicos, decisivos para la victoria  franquista. Goering probó allí su naciente Luftwafe, y más de 700 pilotos  alemanes cuidadosamente elegidos volaron para Franco. Ensayaron bombardeo de  ciudades, <em>blitzkrieg</em> o guerra  relámpago, terror sobre poblaciones civiles, ataques aéreos en picada y táctica  de apoyo directo a las tropas de tierra. Sin olvidar los tristemente célebres  tanques Panzer I.<br />
  <br />
  Esas crueles experiencias  fueron invalorables, al estallar casi de inmediato la Segunda Guerra Mundial  (1939-1945), para los primeros éxitos nazis en toda Europa. La misma Europa que  abandonó a los republicanos españoles. Que solo contaron con la ayuda, sobre  todo inicial, de la URSS  y el apoyo permanente del México de Lázaro Cárdenas, sin olvidar las heroicas e  indomables Brigadas Internacionales.<br />
  <br />
  El  23 de abril de 1937, el jefe de la Legión   Cóndor, Wolfram von Richthoffen, primo del famoso as de la  aviación alemana en la primera guerra, anota en su diario: &ldquo;¿Qué se puede  hacer? La Legión Cóndor  se retira. No se puede dirigir a una infantería incapaz de atacar posiciones  débiles&rdquo;. Y al día siguiente: &ldquo;¿Conseguiremos destruir Bilbao?&rdquo;.<br />
  <br />
  El  26 de abril, a las 14,30 la campana mayor de Guernica repicó alertando sobre un  ataque aéreo. Era día de mercado. Se corrió a los sótanos. Un solitario  bombardero Heinkel 111 de la Legión Cóndor  arrojó su carga letal en el centro y desapareció. La gente dejó sus refugios  para socorrer heridos. Quince minutos después, la escuadrilla completa de la  élite aérea nazi sobrevuela Guernica. Cierto número de cazas italianos Fiat  CR-32 y Fiat-Ansaldo participaron también. Hubo una estampida para huir al  campo, pero cazas Heinkel 51 ametrallaron sin piedad hombres, mujeres, niños. Sin  embargo, faltaba lo peor.<br />
  <br />
  A  las 17,15 cuarenta bombarderos Junker 52 arrasan minuciosamente la ciudad, en  pasadas de 20 minutos durante dos horas y media. Arrojaron desde bombas  medianas o pequeñas hasta de 250   kg, antipersonales e incendiarias. Los testigos describen  escenas apocalípticas. Familias enterradas por escombros de sus casas o aplastadas  en refugios. Vacas y ovejas ardiendo por la termita y el fósforo blanco,  enloquecidas hasta morir entre ruinas en llamas. Salvo la Casa de Juntas y el roble  milenario, no alcanzados por hallarse fuera del corredor aéreo que los pilotos  alemanes siguieron disciplinadamente, Guernica era una pira de fuego, humo y  terror.<br />
  <br />
  El  gobierno vasco sostuvo que un tercio de la población (1645 muertos y 889  heridos) sufrió en carne propia el bombardeo. Al día siguiente, 27 de abril, la  prensa británica anuncia la destrucción de Guernica, y el 28 tanto el <em>Times</em> como el <em>New York Times</em> publican el célebre artículo de George L. Steer. La  indignación mundial es inmensa e inmediata. El 29 de abril el cuartel general  de Franco emite un comunicado, donde intenta adjudicar la responsabilidad a  &ldquo;las hordas rojas al servicio del perverso criminal Aguirre&rdquo;, presidente de  Euzkadi.<br />
  <br />
  La  mayoría de los vascos eran católicos y moderados o conservadores. Se unieron al  Frente Popular en defensa de sus fueros seculares. A diferencia de la Iglesia española, que  apoyó vivamente la &ldquo;Cruzada&rdquo;, fueron acompañados por sus sacerdotes. Yo mismo  recuerdo una foto en la cárcel franquista, donde cien curas vascos rodean al  dirigente socialista Julián Besteiro.<br />
  <br />
  Solo  tras morir Franco (1975), como exigió su autor, el cuadro más renombrado de  Picasso, pintado frenéticamente entre mayo y junio de 1937, pudo exhibirse en  España. Quizá no todos quienes acuden al Museo Reina Sofía saben, hoy, a qué  alude su sobrio título: <em>Guenica</em>. Durante  la ocupación de Francia, al preguntarle ante la misma obra un oficial nazi: &ldquo;¿Usted  hizo esto?&rdquo;, Picasso contestó simplemente: &ldquo;No, esto lo hicieron ustedes&rdquo;.<br />
  <br />
  Como  prueba, baste lo declarado por Goering en el juicio de Nüremberg (1945-1946) a  criminales de guerra nazis: &ldquo;Cuando estalló en España la guerra civil, Franco  pidió auxilio a Alemania, y en especial apoyo aéreo. El Führer vacilaba, y yo  le aconsejé con energía que bajo cualquier circunstancia otorgase ese apoyo: en  primer lugar, para impedir la extensión del comunismo en esa zona, pero también  para poner a prueba mis nacientes Fuerzas Aéreas en una serie de detalles  técnicos. Con autorización del Führer envié gran parte de nuestra flota de  transporte y numerosos cazas y bombarderos, así como cañones antiaéreos. Pude  comprobar en condiciones de combate si el material era eficiente. Para que el  personal adquiriese además experiencia práctica organicé una rotación continua  mandando constantemente unidades nuevas y repatriando las anteriores.&rdquo;<br />
  <br />
  Esa  fría pero precisa enumeración, de por sí escalofriante, se hace estremecedora  si la contraponemos con las imágenes concretas y a la vez inimaginables del  horroroso genocidio sufrido por Guernica. Nadie lo rozó tan hondamente como un  íntimo amigo de Picasso, el gran poeta francés Paul Éluard, en su indeleble  poema &ldquo;La victoria de Guernica&rdquo;: &ldquo;Os han hecho pagar el pan / El cielo la  tierra el agua el sueño / Y la miseria / De vuestra vida // Las mujeres los  niños tienen igual tesoro / En los ojos / Todos muestran su sangre // El miedo  y el coraje de vivir y de morir / La muerte tan difícil y tan fácil // Parias  la muerte la tierra y la fealdad / De nuestros enemigos tienen el color /  Monótono de nuestra noche / Daremos cuenta de ellos&rdquo;.</p>
