<p><strong>Los Pasionistas</strong><br />
  Mi primera infancia  acompañó la militancia joven de mis padres, durante los oscuros años de la  dictadura cívico militar en nuestro país, de la mano de los curas pasionistas  en la Iglesia de la Santa Cruz. Me paseaba por entre los bancos de la iglesia,  por la sacristía, el altar, la casa de Nazareth, cual si fuera mi casa.  Conversaba con las cocineras mientras las ollas humeantes calentaban la sopa  comunitaria que se degustaría más tarde; participaba de retiros, encuentros,  juntadas de juguetes para las festividades; embolsaba, ponía moños y, lo más  trascendental, donaba algunos tesoros preciados para algunos niños y niñas que  no tenían &ldquo;mi suerte&rdquo; de tener tantos juguetes.</p>
<p><strong>Angelelli, un  nombre propio</strong><br />
  El regreso de la  democracia encontró a mis viejos &ldquo;hermanados&rdquo; con quienes se convirtieron en unos  entrañables amigos. Un ex sacerdote riojano y una ex aspirante monja de las  azules, una pareja que se había ido a vivir al norte formoseño, a trabajar con  las comunidades wichí. El monte tiene un calor potente y entre vino en  jarra, entrañas a la parrilla y tardes de tereré  escuché  por  primera vez nombrar a Monseñor Enrique Angelell; quien en el año 1968, acuñó su máximo epítome, &ldquo;con un oído en el pueblo y  otro en el Evangelio&rdquo;. En los llanos riojanos planteó luchar por la dignidad  del hombre, se propuso estar con el hombre concreto y con las mujeres desde la  fe cristiana; asumiendo  la condición de pobre de ese pueblo minifundista,  reconociendo la necesidad de una Reforma Agraria y la idea de que la propiedad de  la tierra es de quienes la trabajan.
Angelelli no era un  libre pensador, era un Obispo que comulgaba con las ideas libertarias; por ello y por perseguir memoria, verdad  y justicia en relación a los asesinatos de los curas Carlos de Dios Murias y  Gabriel Longueville y el del laico Wenceslao Pedernera, fue asesinado el 04 de agosto de 1976. Asesinato que la justicia argentina demoró en juzgar y quiso hacer  pasar como un &ldquo;accidente automovilístico&rdquo;. Para mí, Angelelli  no es sino en relación a la persona de Arturo Pinto, el sacerdote que fuera su  acompañante el día del asesinato y sobreviviente de aquellos hechos; el primero que el Monseñor ordenó en La Rioja, en una parroquia de Villa  Unión. Tal como él mismo me ha relatado &ldquo;los siete años de trabajo, los hice  con él, a su lado. Casi desaparecimos juntos. Más cercano, imposible&rdquo;.  Después al asesinato de Angelelli, Arturo afirmó que no quería ser cómplice y  puso fin a su vida ministerial. </p>
<p><strong>El Fraile  Capuchino</strong><br />
Entre rondas de  encuentros de jóvenes matrimonios con hijos, promediando la mitad de los años  ´80, la figura de un fraile capuchino comenzó a hacerse frecuente. Iba a los  asados, compartíamos  almuerzos y a la tarde al pan con el habíamos hecho los choripanes, lo convertía en &ldquo;el  cuerpo de Cristo&rdquo;. Por aquella época, mi mamá y mi papá, me daban  catequesis los sábados a la mañana, a mí sola y en mi casa, con la ayuda de unos libros que parecían por  demás amigables. Tomé mi Primera Comunión en la capilla de Nazareth, parte de  la Iglesia de la Santa Cruz. El cura Federico José, un amigo de la familia, me  ungió con ese sacramento fundamental para los cristianos, el 28 de  diciembre de 1985,  día de los Santos Inocentes. Años después, en  las últimas vacaciones con mi viejo, hicimos  escala en casa de amigos, en Santa Fe. A la hora de la siesta, me tiré en una  cama a leer una revista de actualidad y una noticia atrapó mi atención: el MTP y su participación en la toma del cuartel de La Tablada. El nombre de  aquel fraile capuchino, aparecía en esa nota.</p>
<p><strong>El Papa Juan  Pablo II  </strong><br />
Las primeras  conversaciones con quien fuera mi pareja, nos encontraron discutiendo sobre la figura de  Karol Józef Wojtyla. Era 1998 y en una nota de un matutino de circulación masiva  anunciaban la preocupación del Papa por los Derechos Humanos en el mundo.  Fueron los años en  los que podría decir que no sólo me valió la inocencia sino también esa supina  ignorancia de-constitutiva de la especia humana. Si el  ser humano se constituye como tal a través del lenguaje, durante aquellos años  hice ausente lo presente. Con el tiempo, registré que ese vaciamiento era  negacionista y que ese negacionismo es co-constitutivo del accionar del aparato  eclesiástico; partícipe del terror, el dolor, la  desaparición, la tortura y la muerte de nuestro país. Como si todo lo  vivido hubiera sido encriptado y reducido a su mínima expresión, recuerdo,  casi como un slogan, que se nos llamaba a &ldquo;vaciarse de uno para amar al otro&rdquo;. </p>
<p><strong>San Cayetano:  mucho más que Paz, Pan y Trabajo</strong><br />
Durante la mitad de los años &lsquo;90   cursé la Licenciatura en Trabajo Social y  semanalmente hacía mis prácticas en el comedor nocturno para  personas en situación de calle que la Iglesia de San Cayetano ofrecía como  parte de su Servicio Social. Allí se podía registrar de cerca el sufrimiento  cotidiano de la gente, el hambre, la pobreza, el frío, la desocupación, la  marginalidad. Como cada 7 de agosto, día del Santo, filas interminables de los  feligreses pedían Paz, Pan y Trabajo. Mi formación universitaria empezó a  discutir tímidamente con mi creencia de fe; la idea del voluntariado y del  amor al prójimo, quedaba demasiado desnutrida. Un día, llevé un artículo  periodístico para debatir con mi referente de práctica que me  discutió hasta el cansancio la preocupación  papal por los Derechos Humanos no era tal; que los derechos de algunos humanos  se estaban disputaban diariamente en las medidas neoliberales del gobierno de turno y que la Iglesia si no los abalaba, al menos no los discutía.</p>
<p><strong>Semblante, Posición y Disposición: un trastocamiento ¿posible?</strong><br />
¿Es posible conjugar/conjurar  la posición del cura con la posición militante? Algunos tramos de lo dicho aquí  asegurarían que es posible hacerlo. La notoriedad de ser curas no viene dada  necesariamente por el ejercicio activo de su profesión sino por lo que   esa investidura les ha permitido decir, callar, organizar, participar,  silenciar o ser silenciados. Una imagen que  lejos de &ldquo;oficiar de Dioses en la tierra&rdquo;, los convierte en seres terrenales,  osados, mediocres, activos lúcidos, oprobiosos despreciables, pero por sobre  todas las cosas, personas de carne y hueso. Porque de la sotana, el altar, el púlpito y algunos poderes ministeriales, puede decirse que así como instituyen a un cura, también lo destituyen. El cura se ha instaurado como verdad, como una revelación que sólo en algunos casos ha podido trastocarse en rebeldía.</p>
