<p>La sopa, en el imaginario argentino de los mayores de 40  años, ha quedado inevitablemente ubicada como una de las tantas líneas  divisorias del gusto. Llevada al extremo de una causa casi política en las  tiras cómicas por Mafalda, los que quedamos del lado sopero nos plantamos, como  su hermanito Guille, cuchara en mano, para hacerle frente al invierno con  nuestro plato humeante en la mesa familiar. Sopas de verduras, caldos varios  con hueso, caldos concentrados que albergaban sémolas, fideos y arroces, fueron  nuestro bastión inexpugnable. Municiones, cabellos de ángel, letras y números,  caracolitos de colores, todos ellos nos acompañaron hasta el borde del juego  cuando, sentados, los pies no nos llegaban al suelo. Se sabe que el tiempo  pasa, que nos vamos poniendo viejos y que la diversificación gastronómica ha  borrado aquellas viejas líneas divisorias, así que ponemos a consideración de  nuestros lectores estas tres variantes que experimentamos con placer y éxito.</p>
<p><strong>Sopa de calabaza</strong><br />
Rehogar una cebolla en manteca. Cuando esté transparente, agregar un kilo de  calabaza y dos papas, todo cortado en cubos pequeños. Salpimentar y añadir  medio litro de caldo de verduras. Bajar el fuego y cocinar hasta que los cubos  estén blandos, lo que suele suceder alrededor de los 20 minutos de cocción. Retirar  del fuego y licuar/mixear. Añadir 200 ml de crema de leche, volver al fuego,  revolver hasta integrar y calentar sin que llegue a romper el hervor. Para  servirlo se le puede agregar una cucharadita de queso crema, perejil o cilantro  picados, un poco de pimentón o un chorrito de crema líquida para decorar.</p>
<p><strong>Sopa de papas y puerro</strong><br />
Rehogar 4 puerros y una cebolla en una cucharada de manteca. Cuando estén  transparentes, agregar dos papas cortadas en cubos y un litro de caldo de  verduras; cocinar a fuego medio. Cuando la papa esté tierna, retirar y mixear.  Como en la receta anterior, agregar 200 ml de crema de leche, salpimentar y  agregar una pizca (o no tan pizca) de nuez moscada. Imbatible.</p>
<p><strong>Quinua y pollo</strong><br />
  La quinua es uno de los pseudocereales andinos que se han constituido en uno de  los descubrimientos más explorados de la amplia gama alimentaria del imperio  Inca. Aprovechando el envión, lavamos 250 gramos de quinua (recomendamos  cambiar el agua varias veces hasta que salga limpia) y la dejamos en remojo.  Mientras tanto, cortamos un par de presas de pollo (usamos patas y muslo por su  consistencia y humedad) en trozos pequeños y los doramos unos 5 minutos en  manteca. Cuando ha tomado color a cocido, le agregamos uno o dos dientes de  ajo, dos zanahorias picadas y una cebolla, todo picado pequeño mas no diminuto.  Cocinamos durante diez minutos agregando un poco de agua de ser necesario para  que no se pegue. Agregamos la quinua remojada, dos papas cortadas en cubos  pequeños y un litro de agua a temperatura ambiente. Condimentamos con sal,  pimienta, una pizca de ají molido y comino, lo que le darán típico aroma a  cocina peruana. Cocinamos durante 20 minutos y nos disponemos a disfrutar un  plato que se llevará el frío en un par de cucharadas.<br />
Para finalizar la nota de este terceto anti frío invernal,  algunas de las mejores tiras de la pequeña Mafalda y su cruzada antisopa.</p>

<p><img src="images/mafalda01.jpg" width="100%"/></p>

<p><img src="images/mafalda02.jpg" width="100%"/></p>

<p><img src="images/mafalda03.jpg" width="100%"/></p>

<p><img src="images/mafalda04.jpg" width="100%" /></p>
