<p>Aristóteles  decía que la poesía tiene su origen en dos causas, ambas naturales: la  imitación es propia de los hombres desde la infancia; todos gozan con la  imitación. Ser capaz de imitar y adquirir conocimientos por imitación es lo que  diferencia a los hombres de los otros seres vivientes.</p>
<p>¿Por  qué sería natural para los hombres imitar la naturaleza? Una explicación  hermosa, por lo sencilla, es la esgrimida por Augusto Boal en su Teatro del  Oprimido. Hasta donde sabemos, el hombre es el único ser vivo que tiene  conciencia de lo que hace: un perro no sabe que su cola es su cola y se la  persigue; un gato ve en su reflejo en el espejo a otro gato. En cambio, el  hombre es capaz de verse a sí mismo en acción, reconocer sus partes, captar sus  movimiento en el espacio, escuchar su voz sabiéndola propia, es decir, reconocerse  en el espejo. Y es, por todo esto, espectador y actor de su propia vida,  permanentemente, aun cuando sueña. El hombre es un creador innato, que  improvisa y crea cada acto de su hacer cotidiano, sabiéndose visto por los  otros y por sí mismo. Esta dicotomía, en la que el hombre, además de accionar,  tiene una mirada externa de ese accionar propio, lo deviene actor, y la vida se  convierte en su gran teatro, espectáculo o poema. Su puesta en escena.</p>
<p>Para  Aristóteles el arte imita, copia la naturaleza: mímesis. &ldquo;El hombre adquiere  conocimiento por imitación&rdquo; y &ldquo;el poeta imita no solo cómo son las cosas, sino  también cómo dicen o parecen que son las cosas o cómo deberían ser&rdquo;, elaborando  casi una idea de utopía. Porque para Aristóteles, el arte genera conocimiento,  pero ¿cómo se establece esa relación entre arte y conocimiento?</p>
<p>Alain Badiou plantea que en este vínculo, desde Platón hasta Heidegger,  hay un vuelco completo: &ldquo;Para Platón, el pensamiento tiene que tener como  modelo la pureza ideal de los objetos matemáticos y desviarse de la fuerza  sensible del poema. Para Heidegger es exactamente lo contrario. La matemática  es un cálculo ciego al servicio de la violencia de la técnica. En cambio, el  poema es lo que deja aparecer la presencia del ser&rdquo;. En este análisis, el  teatro –el espectáculo– desempeña un papel decisivo. El teatro es el arte de la  imitación y de la actuación; es aquello que critica el principio de identidad; todo  es otra cosa distinta de lo que es. El teatro plantea una verdad, que no existe  en ningún lugar que no sea en el teatro. El teatro es la virtualidad de una idea  que baja a la actualidad perecedera del escenario. Es el arribo de una idea: acontecimiento;  una composición temporal pública de un encuentro sensible con la idea, que es  experimental, político y aclara nuestra situación en la historia. Teatro es,  entonces, <strong>eternidad </strong>de sus figuras poéticas, <strong>singularidad</strong> del instante y <strong>universalidad</strong> del público, que siempre  es la humanidad. Si clásicamente la filosofía es búsqueda de la verdad (en  tanto eterna, singular y universal) el teatro es, bajo estas condiciones, la  presentación de una verdad. </p>
<p>Si aceptamos que el imitar es natural a los hombres y convenimos que, aun  desde las distintas corrientes del pensamiento filosófico, el arte genera  conocimiento, se presenta otra pregunta: ¿qué es imitar?</p>

<br />

<p><strong>Siempre comenzando</strong><br />
Valiéndonos de <em>Diferencia y  repetición</em>,de Gilles Deleuze,  tomemos imitación como repetición. Repetición no es generalidad sino lo  contrario de semejanza. &ldquo;Lo que nos cuenta Homero no es un pasado fechable y,  en rigor, ni siquiera es pasado: es una categoría temporal que flota, por  decirlo así, sobre el tiempo, con avidez siempre de presente. Es algo que  vuelve a acontecer apenas unos labios pronuncian los viejos hexámetros, algo  que siempre está comenzando y que no cesa de manifestarse&rdquo; (Octavio Paz).</p>
<p>Repetición es  universalidad de lo particular, que es lo contrario de generalidad de lo particular.  La repetición expresa una <strong>singularidad </strong>en contra de generalidad, la <strong>universalidad</strong> frente a lo particular, una <strong>instantaneidad</strong> en contra de variación; <strong>eternidad</strong> <em>versus</em> permanencia.  La repetición es transgresión. Pone en cuestión la ley; denuncia su carácter  nominal y general que no permite sacarle provecho a una realidad más artística  y profunda. </p>
<p>Convertir  la repetición en algo nuevo, vincularla a una prueba, significa actuar. Se  trata de convertir la repetición como tal en una novedad, es decir, en una  libertad y en una tarea de libertad. Nietzsche afirma: &ldquo;Liberar la voluntad de  todo lo que la encadena, convirtiendo la repetición en el objeto mismo de la  voluntad&rdquo;. Sin duda, la repetición es ya lo que encadena, pero si uno muere a  causa de la repetición, esta también lo cura y lo salva, en primer lugar, de  otra repetición, pues en la repetición se manifiesta el doble juego místico de  la perdición y de la salvación: el reto teatral de la vida y de la muerte.</p>
<p>Para  Deleuze el teatro es el movimiento real y en todas las artes que utiliza extrae  el movimiento real, la esencia y la interioridad del movimiento, es decir, la  repetición. Reprocha a Hegel por permanecer en el falso movimiento, en el  movimiento lógico abstracto, en la representación. Nos dice: &ldquo;Hegel representa  conceptos en lugar de dramatizar ideas&rdquo;. En cambio, propone poner la metafísica  en actividad, pasarla al acto, a los actos inmediatos.</p>
<p>Rescata  en Marx una idea, esencialmente teatral: en tanto que la historia es un teatro,  la repetición, lo trágico y lo cómico de la repetición forman una condición del  movimiento bajo la cual los actores o protagonistas producen en la historia  algo efectivamente nuevo. &ldquo;En el teatro el protagonista repite, precisamente,  porque está separado de un saber esencial infinito. Este saber está en él, en  él está inmerso y actúa pero actúa como una cosa oculta, como una  representación bloqueada. El problema práctico consiste en que &lsquo;este saber no  sabido&rsquo; debe ser representado bañando toda la escena, impregnando todos los  elementos de la obra, comprendiendo en sí todos los poderes de la naturaleza y  del espíritu, pero al mismo tiempo el protagonista no debe <em>representárselo,</em> debe, al contrario, transformarlo en acto,  desempeñarlo, repetirlo. Hasta el momento extremo en que Aristóteles lo llama reconocimiento,  en el que la <em>repetición</em> y la <em>representación</em> se mezclan, se enfrentan  sin confundir, sin embargo, sus niveles: el saber está reconocido como el  mismo, en tanto que está representado en la escena y repetido por el actor&rdquo;. </p>
<p>Es  decir, Deleuze impulsa un teatro de la repetición donde se experimentan fuerzas  puras, trazados dinámicos en el espacio, que actúan sobre el espíritu sin  intermediario y lo unen directamente a la naturaleza y a la historia, un  lenguaje que habla antes de las palabras, gestos que elaboran antes que los  cuerpos organizados, máscaras antes que los rostros, espectros y fantasmas,  antes que los personajes. La repetición expresa un poder propio de lo  existente, una testarudez de lo existente en la intuición, que se resiste a cualquier  especificación por el concepto, por lejos que se lance.</p>
<p>Somos  poema, repetición transgresora, acontecimiento, potencia, estar en el mundo, reminiscencia  y gozo: teatro de nuestra humanidad.</p>
