<p>Estaba en la cola del banco odiando a una señora que se  demoraba en su charla con el cajero cuando en una distracción me invadió una  idea para un cuento. Por su andar parecía buena, y me hizo olvidar por completo  del fastidio y el lugar. La idea era elegante y resuelta, me miraba desde un  rincón como si nos conociéramos de otra parte o como si siempre hubiera estado  en mí. Me abordó con tanta naturalidad que me sentí un poco intimidado y me  hice el interesante, confiado de que no se iba a escapar. Pero el llamado del  cajero me succionó de la escena y tuve que apurarme con mis cuentas impagas.</p>
<p>Cuando regresé a su encuentro ya se había ido, no  quedaba ni el perfume de su pelo recién lavado, pero no me preocupé demasiado,  era una idea muy potente y además ideas como esa no se someten al olvido así  nomás.</p>
<p>Pasó ese día, y varias noches y mi idea no volvía, por  más que me esforzaba en recuperarla, su forma –mas bien mi recuerdo de su  forma– se desdibujaba sin que pudiera hacer nada más que añorarla. Por costumbre  me baño por la mañana, pero en esos días me duchaba cada noche con un jabón de  lavanda con la ilusión de que nos encontráramos entre sueños. En la mesa de  luz, a un manotazo de distancia, tenía preparadas una libreta y una lapicera.  Lo peor de su ausencia era que no podía pensar en ninguna otra idea; cuanto más  pensaba en su regreso más hueco soplaba el viento.</p>
<p>Una mañana en que me quedé sin yerba decidí que lo  mejor era sacármela de la cabeza, no iba a ser mi primer ni mi ultimo duelo,  además si no había vuelto era por que no sería más importante que cualquier  otra proyección de mis divagues.</p>
<p>Pero una tarde, en plena mediación de divorcio con mi  exmujer y sus abogados, me pareció reconocer su sombra fugaz a través de la  única ventana de aquella oficina tan beige. Creo que nadie notó cómo me  sobresalté e intenté mantener cierta presencia, pero estaba tan pendiente de  darle caza a la fugitiva que, para ser sinceros, no comprendí una palabra más  de lo que estaban diciendo. Me puse muy ansioso, e inventé una excusa para  salir decidido a retenerla de alguna manera, pero cuando llegué al pasillo solo  quedaban unas pisadas de tacos que la alfombra nueva iba evaporando. Volví tan  decepcionado a la sala que ni escuché que la mediación había fracasado debido a  mi falta de interés. Mi ex masculló algo acerca de mis capacidades de siempre y  que no quedaba más alternativa que ir a juicio. Su abogado y el mío parecían  finalmente coincidir en algo.</p>
<p>Salí del edificio, grumos de gente se cruzaban delante  de mis ojos, y yo en mi doble derrota no sabía para qué lado moverme. Lo  primero que pude pensar era si se sentiría así un nocaut. Necesitaba alguna  certeza y, caminé Corrientes a contramano hacia una pizzería amiga, porque en  momentos de duda no hay nada más seguro que una porción de pizza de parado en  Guerrín.</p>
<p>El queso de la pizza se alargó en varios pingüinos del  vino de la casa y charlas con desconocidos. Todos parecíamos añorar alguna idea  perdida entre la resignación y la borrachera triste.</p>
<p>Cuando me di cuenta de que ya estaba bien de  autocompasión, me fui a tanguear mi viernes en las librerías de usados. Entre  los LP de Almendra y un póster del Polaco, me sonríe ahora un papa argentino.  Amenazado por la resaca que asomaba me puse a hojear las Radiolandia con la  ilusión de idearla desde alguna foto, o al menos de olvidarla para siempre.  Seguí Corrientes arriba y cuando cruzaba Callao, en el medio de la avenida  aflora, con la naturalidad de alguien que salió a comprar otra botella de vino  y volvió. Me quedé pasmado, parecía que nunca estaría para recibirla. Una  bocina de colectivo me violó los oídos y de un impulso aterricé en la vereda.  Ella seguía ahí, mirando por detrás del hombro, y esta vez parecía dispuesta a  quedarse conmigo. Para no asustarla disimulé mi ansiedad de retenerla y busqué  mi libreta en los bolsillos, pero solo encontré un puñado de billetes  arrugados. Al menos la borrachera no me había arruinado económicamente. A mi  alrededor todos los locales estaban cerrados o sus empleados baldeaban las veredas.  Cada vez que nos encontrábamos el universo parecía una cornisa. Confundido  llamé a un taxi agitando el brazo, y pensé que ya tenía todos los movimientos  de un viejo. Los vidrios estaban empañados, menos el de adelante, que el  taxista insistía en limpiar con una franela que dejaba un camino de pelusas  amarillas. Con apuro, para que ella no se moje, le pedí al taxista un papel y  una birome. </p>
<p>Me puse a garabatear en la oscuridad las líneas de la  idea, siendo fiel a esa figura que me miraba como a través del humo, pero la  birome tosió dos hilos de tinta y se secó a traición, como el agua caliente que  se acaba en plena ducha. Sentí que se escurría por el espiral que hace el agua  en un lavatorio, pero antes de que se fuera hendí un garabato con la punta seca  de la birome en el papel.</p>
<p>Llegué a casa, me caí en la cama desecha y me quedé  dormido con las zapatillas puestas, empapado pero con la tranquilidad de que en  el bolsillo de mi campera había quedado la huella de mi conquista.</p>
<p>Cuando me despertó el sol en la cara, la resaca ya  había tomado un control total de la situación y mi estado de ánimo. Busqué a  tientas mi campera entre la ropa tirada en el suelo, metí la mano en un  bolsillo y solo había un volante de un cabaret y un ticket de supermercado.  Metí la mano en el otro y allí estaba el papel a rayas doblado como un fuelle.  El alma me volvió al cuerpo.</p>
<p>Me senté en la mesa de la cocina frente al desayuno y  alisé el papel contra el borde de la mesa, pero al abrirlo, en vez de apuntes  encontré tallado sin tinta un número de teléfono. No tenía el 15 delante, por  lo que deduje que era el número de una casa.</p>
<p>Marqué el número, apoyé el auricular en la oreja y lo  escuché sonar. Una, vez, luego otra y otra. Quizás había marcado mal. Me tomé  el mate, estaba frío. Marqué de nuevo. Tuuut, Tuuut, seis veces, siete veces.  Ocho.</p>
<p>Una voz de mujer atiende y me dice con profesionalismo:  &ldquo;El número que ha marcado no corresponde a una idea en servicio&rdquo;.</p>
<p>Otra vez se fue, seguro que no era tan buena.</p>
