<p align="right" style="font-size:15px">                                              <em>…  para quienes vemos en la literatura un instrumento de la  <br />
  liberación nacional y no una vanidad personal…</em><br />
<br />
<em>.. no hay literatura separada de la política.<br />
  J. J. Hernández Arregui</em></p>
<p>Si  reflexionamos sobre el hecho de que toda obra de arte es llevada a cabo por  humanos, y luego agregamos que dichos sujetos poseen algún tipo de ideología  política, no nos es muy difícil y arriesgado concluir que toda obra de arte, de  modo solapado o explícito, lleva grabada una ideología política. En principio,  entiendo la política como el modo en que se desarrollan las relaciones entre  los individuos de una sociedad, donde estos toman posiciones políticas sobre el  modo en que se organizan dichas relaciones sociales: unos oprimen, otros se  rebelan; unos aguantan, otros callan. Porque la pasividad y el silencio también  son hechos políticos. Por eso es necesario subrayar que una obra de arte,  aunque no sea explícitamente política, se torna política en lo que calla. Y  luego, si al lector, espectador, escucha, etc. le quedan dudas, debe considerar  que si dicha obra se hace pública, se vuelve política en el rol social que  cumple dentro de una sociedad determinada, pues los efectos de una obra de arte  son insospechados, indirectos, insondables.</p>
<p>En  este texto nos referiremos a algunas obras literarias creadas en nuestro país  que, de forma explícita, tienen algún tipo de intencionalidad política. El tema  es extenso, por eso elegiremos algunos casos paradigmáticos. </p>
<p>Dentro  del inmenso manantial poético-musical que constituyen los cancioneros del  noroeste argentino, encontramos textos que son el producto del mestizaje que se  desarrolló con la invasión europea y su política colonialista y genocida.  Hombres como Juan Alfonso Carrizo han recopilado en pueblitos de Jujuy, Salta,  Catamarca, Tucumán o La Rioja romances y coplas españolas anónimas, pero  también se ha encontrado en la boca del pueblo de esos lugares coplas quichuas,  sobre todo en Santiago del Estero. Es necesario agregar que dichas tradiciones  populares perduran hasta la actualidad, generalmente en los lugares más  alejados de los centros urbanos. Y justamente en la copla, la forma poética que  se ha vuelto más popular en nuestro país, dando una estructura a bagualas,  vidalas, chacareras, gatos, escondidos, milongas, etc. encontramos textos de un  alto contenido político, como los siguientes:                                </p>
<p>El  pobre quiere y no puede                                                                                                <br />
  gozar  de su libertad, <br />
  que  lo entierren no precisa, <br />
  ya  enterrado en vida está. </p>
<p>Siempre  andan aconsejando <br />
  que  me aguante la pobreza: <br />
  al  que no carga la carga <br />
  le  parece que no pesa.</p>
<p>Dejaremos  de lado a las grandes obras literarias del siglo xix argentino (<em>El</em> <em>Matadero</em> de Echeverría, <em>Facundo</em> de Sarmiento, <em>Martín Fierro</em> de José Hernández, <em>Una</em> <em>excursión  a los indios Ranqueles</em> de Lucio V. Mansilla o <em>Juan Moreira</em> de Eduardo Gutiérrez, textos ya clásicos, aplaudidos y  defenestrados desde distintos enfoques) para centrarnos en la obra de un autor  del siglo pasado: Roberto Arlt. De la circunstancia de que este porteño fuera hijo  de inmigrantes europeos (padre prusiano y madre italiana) resultan dos hechos  biográficos: el origen humilde y los problemas con la lengua que se hablaba en la  Buenos Aires de principios del siglo xx.  Nació en 1900 en el barrio de Flores, donde vivió y creó uno de los más grandes  pintores sociales de nuestro país: Enrique Policastro. Arlt estuvo ligado a un  movimiento artístico social de los años 20, el grupo Boedo, que pregonaba el  arte político y el compromiso del artista con su realidad social. Pero también  fue secretario de Ricardo Güiraldes, mentor del grupo Florida, opuesto al  anterior, y que adhería al arte puro, sin contacto con la realidad política del  momento. Pero Arlt, cuya ideología era comunista, se decidió por lo social y se  unió al Teatro del pueblo, creado por Leónidas Barletta en los años 30, donde  se representaron varias de sus obras teatrales. </p>
<p>El  tema social atraviesa la obra de Arlt. En sus dos novelas más importantes, <em>Los siete locos</em> y <em>Los lanzallamas</em>, un grupo de personajes marginados deambulan por  una ciudad feroz donde habitan, por un lado, los seres más pobres, y por otro las  niñas <em>bien</em>, que Erdosain mira como  una cosa que no está a su alcance mientras busca el batacazo que lo saque de  una situación social desesperada y terrible. Erdosain quiere hacerse rico con  algún invento genial, una salida que también había deseado el autor y frente a la  cual siempre fracasó, mas no sin antes dar a luz cosas tan increíbles como unas  medias femeninas hechas con un material similar al caucho para que no se  rompieran. </p>
<p>Es  en esa ciudad, tan dura como sus edificios, donde aparecen los anarquistas,  hoscos y desconfiados, fabricando bombas para destruir a un sistema que los  oprime día tras día, junto a cafishios, pederastas, sádicos y todo un abanico  de seres prostibularios que forman la fauna ciudadana de Buenos Aires.  </p>
<p>Ahora  sí debemos agregar que el problema social atraviesa la obra y también la vida  de Arlt, ese hombre que tuvo que robar tiempo a su trabajo para escribir obras  literarias geniales mientras la oficina le robaba &ldquo;jirones de vida&rdquo; día tras  día, en una rutina cruel y sin descanso, que se cerraba sobre su alma inquieta  con el peso de la hipocresía asesina de los poderosos. Este escritor tan  porteño y tan universal nos explicó qué opinaba sobre el arte en el magnífico  prólogo a <em>Los lanzallamas</em>, donde  escribe: &ldquo;El futuro es nuestro, por prepotencia de  trabajo. Crearemos nuestra literatura, no conversando continuamente de  literatura, sino escribiendo en orgullosa soledad libros que encierran la  violencia de un <em>cross</em> a la mandíbula.  Sí, un libro tras otro, y «que los eunucos bufen»&rdquo;.</p>
<p>&nbsp;</p>
