<p>A lo largo del tiempo, el subgénero gastronómico de las tortillas (y me  refiero aquí solamente a las de huevo batido y frito) no ha evolucionado  demasiado, si dejamos a un lado los juegos tecnoemocionales de la nueva cocina,  que ha deconstruido la tortilla de patata y la ha colocado en una copa de  cóctel, asimilándola al margarita o al <em>gin-fizz</em>.  Por el contrario, la tortilla ha mantenido a lo largo de los años su vocación  maternal y protectora, su capacidad innata de envolver y arropar a otros  alimentos para ofrecerlos así, enriquecidos por la mezcla y la coincidencia. </p>
<p>Con la referencia siempre puesta en el origen de todo, la triste e infantil <em>omelette</em> o tortilla francesa, podemos decir que casi no hay límites al  relleno. Es obligado empezar por la tortilla de patata o española, a la que  pueden añadirse otros alimentos, dando lugar a la tortilla paisana, cada día  menos vista en la barra de los bares. Prescindiendo de esa base de patata, el  relleno puede cumplir con los requerimientos de la cocina vegetariana menos  estricta, e incluir solamente verduras y hortalizas, o puede envolver carnes,  pescados y mariscos, embutidos y quesos, <em>foie-gras</em>…  Incluso hay tortillas en las que el sabor dulce es el dominante y se reservan  para el momento postrero de la comida. Las posibilidades son muchas, pero da la  impresión de que hay cierta tendencia al olvido, pues cada día es más raro ver  en las casas y en las cartas y menús de los restaurantes de cocina casera (<em>fresh cooking</em>, que dirían los ingleses),  algunas de las tortillas que en otro tiempo fueron habituales. Basta acudir a  la memoria, o a libros de cocina y recetarios de hace unos cuantos años, para  comprobar que la lista de lo que podemos considerar como tortillas en peligro  de extinción es enorme. </p>
<p>Sin ánimo de llevar a cabo una &ldquo;prospección gastrológica&rdquo;, sino únicamente  con la intención de mostrar la riqueza y diversidad que puede ofrecer el huevo  batido y frito, rescato aquí unas cuantas de esas tortillas que podrían ser  platos estelares en los restaurantes-museo que quizá ya existan en algún lugar  del mundo:</p>
<p><strong>Tortilla de judías verdes</strong><br />
  Se pelan y cortan las judías verdes como habitualmente y se hierven. Cuando  están bien escurridas, se rehogan en una sartén con aceite de oliva, sal y  pimienta, añadiéndoles al final unos taquitos pequeños de jamón serrano o  ibérico. Cuando están rehogadas, se escurren bien de aceite, se vierten sobre  el batido de huevos y se cuaja la tortilla en redondo.</p>
<p><strong>Tortilla a la jardinera</strong><br />
  Se fríen unas patatas como para tortilla española y se reservan, dejando  que escurran el aceite. Se hierven guisantes y cabezas de espárragos en  abundante agua. Se baten los huevos, se salpimientan y se añaden las patatas,  los guisantes y los espárragos bien escurridos, un poco de perejil picado, se  mezclan bien los ingredientes sin machacarlos y se cuaja la tortilla con forma  alargada.</p>
<p><strong>Tortilla de habas</strong><br />
  Las habas deben ser tiernas y más bien pequeñas. Se cortan los extremos y,  sin quitarles la vaina, se pican en trozos pequeños. Se lavan en agua y se  ponen a escaldar unos 5 minutos. Cuando están, se escurren y se reservan. En  una sartén con aceite se pone cebolla picada, se deja rehogar un poco, se  añaden luego las habas y se continúa rehogando hasta que estén tiernas. Se  sacan entonces y se escurren bien de aceite. Se baten los huevos, se salan y se  añaden las habas. La tortilla se cuaja en redondo.</p>
<p><strong>Tortilla guisada</strong><br />
  Se hace una tortilla de patata (algo más cuajada que normalmente) y se  reserva partida en cuatro cuartos. En una sartén se pone aceite de oliva y  cuando está caliente, pero sin humear, se añaden unos cascos de cebolla y un  diente de ajo machacado y se rehoga. Luego se añade una o dos hojas de laurel,  un pelín de azafrán y un poco de harina (si queremos la salsa un poco más  espesa); se remueve todo bien, se agrega agua y se deja cociendo unos minutos.  Al rato se añaden los cuartos de tortilla, que deben quedar cubiertos por el  caldo, y se deja cocer otros 10 minutos, añadiendo agua si es preciso.</p>
<p><strong>Tortilla de sesos</strong><br />
  Se cuecen, con ajo, cebolla y perejil los sesos de cordero, que deben haber  estado en remojo con agua fría para blanquearlos. Cuando están cocidos, se  escurren bien y se pican sobre el batido de huevos, se añade sal y se cuaja la  tortilla con forma alargada. Debe quedar bien jugosa.</p>
<p>&nbsp;</p>
