<p align="right" style="font-size:14px"><em>No hay forma de volver.<br />
  Estamos lejos, muy lejos de la  tierra: <br />
  cada vez más lejos de la  especie.</em><br />
  Diego Muzzio</p>
<p>En el año 2002 <em>Plop</em>, la  primera obra de Rafael Pinedo, recibía el Premio de Novela Casa de las Américas.  En una decisión afortunada Interzona decidió recientemente reeditar la novela,  en la Pinedo nos invita a realizar un movimiento que supone  alejarse, pero no mucho, del presente para ubicarnos en un territorio futuro  donde el binomio entre lo familiar y lo extraño –revisando el axioma de Ballard–  desaparece.</p>
<p>Hablar de géneros  literarios implica problematizar, en el plano de la prelectura, de qué manera  activamos nuestra maquinaria interpretativa. Dicho en fácil: no es una novela  que pueda ser encasillada en un género o en otro como si pudiese formar parte  de alguna familia o clase específica. <em>Plop</em> es una novela en la que aparece, se podría decir que provisionalmente, un  sincretismo entre el recorrido del héroe como modelo narrativo, el relato de  iniciación y la ciencia ficción. </p>
<p>El nombre del  personaje principal, y el del texto, compone una biografía en el interior de un  paisaje oxidado con chatarra y restos de plástico multiplicándose por todas  partes. El mundo es un gran baldío donde los hombres buscan refugiarse de las amenazas,  mantenerse en pie y preservarse a sí mismos por encima de su comunidad y de las  necesidades de los otros. </p>
<p>Como héroe, Plop no  recorre un camino feliz sino que contrariamente al modelo original, donde al  final se ejecuta una instancia de autotrascendencia o realización en alguna  dirección, muere bajo el signo de la decadencia. La ciencia ficción se ha  encargado de abordar representaciones acerca del fin de los tiempos. No  obstante, para algunos autores, como Daniel Link, la ciencia ficción es un  relato del futuro narrado en pasado, lo que inmediatamente genera en los  lectores esta pregunta: ¿Desde dónde leemos estas narraciones? El tiempo en el  que ocurren las acciones de <em>Plop</em> no  está tan lejos de nuestro entorno inmediato. </p>
<p>El presente de <em>Plop</em> podría funcionar, en algún punto,  como el nuestro en forma simultánea. Un presente que mira, como en un espejo  retrovisor, hacía un pasado salvaje de la humanidad en el que solamente logran  continuar con vida aquellos que son más aptos. De ahí que Pinedo nos esté planteando  lo borrosa que suele ser esa distinción, o ese perímetro, que aleja, o separa,  a los hombres del resto de los seres vivos o de meros objetos que hacen juego  con las coordenadas en las que les toca posicionarse. En fin, Pinedo nos  traslada a una tierra sin mapas cuya brújula es la intuición en su estado más  descarnado, y en donde la supervivencia se transforma en el único horizonte de  sentidos posible.</p>
<p>&nbsp;</p>
