<p>Ha llegado el momento en el que podemos decir  que el hip-hop se transformó en algo más. Pasó de ser un género cuadrado a  variar y transformarse en distintas formas musicales, mezclando inspiraciones  de sonidos e innovando en sus modos de producción. A lo largo de los años la  evolución ha sido notable, y esto no se ha dado solamente por la nueva  corriente de raperos y músicos jóvenes que se han metido en la industria, sino  también la evolución de artistas que llevan hasta treinta años en el rubro. El  mérito está divido entre las herramientas dadas por los grandes antecesores de  la industria, los cuales continúan sacando artistas de su galera y  produciéndolos, y la nueva camada de músicos que presentan ideas y conceptos  originales, transformando las dimensiones del género convencional. Un claro  ejemplo de lo sucedido es el caso de Kendrick Lamar, una de las revelaciones de  los últimos cinco años. Un joven de Compton, California, que ha estado armando  revuelo en el mundo del hip-hop por su alta producción musical y su destreza  para escribir rimas llenas de reflexión, crítica social y poesía.</p>
<p>El radar detectó a Kendrick como un prometedor  rapero allá por el año 2011, con el lanzamiento de su primer álbum de estudio, <em>Section 80</em>, el cual impresionó de gran  manera pero no marcó una tendencia que hiciera estar alerta a cada paso del  artista. Si bien las expectativas no eran bajas, el foco de atención no llegó realmente  hasta el lanzamiento de su segundo álbum, <em>Good  Kid M.A.A.D City</em>, el cual fue considerado uno de los mejores álbumes de rap  en la última década. Kendrick había entendido que era convertirse en algo más,  hacer algo más, transformando su álbum no solo en un conjunto de canciones sino  en un concepto. El disco trata de contar una historia, no solo en la lírica de  la gran mayoría de sus canciones, sino también en los cortes que hay entre tema  y tema, que ponen luz a la historia de este joven Kendrick que se ve sumido en  un mundo complicado y en cómo su vida está expuesta al crimen; mostrando tanto  su propia situación social como la de su comunidad. El artista toca temas muy  personales, que lo ponen en el centro de todos estos conflictos sociales que  cualquier afroamericano sufre estando dentro del ghetto. Si bien estos temas  han sido abordados por muchos artistas, es la narrativa y su ingenio a la hora  de escribir y componer canciones lo que hizo que Kendrick Lamar se viera en una  situación tan promisoria. Con productores en este disco como Dr. Dre, Pharrel  Williams y Hit-Boy, entre tantos otros, y con participaciones de Drake, Jay  Rock y el legendario Dr. Dre, no sólo produciendo, sino también colaborando en  la canción &ldquo;Compton&rdquo;, con la cual cierra el álbum.</p>
<p>Kendrick supo muy bien con quiénes aliarse y  qué caminos tomar. Tres años en la pendiente y con un par de colaboraciones en  el medio, Lamar anuncia un nuevo álbum titulado <em>To Pimp A Butterfly</em>, el cual cuenta con las colaboraciones –en  producción, composición y participación– de grandes como George Clinton, Boris  Gardiner, Snoop Dogg, Dr. Dre, Pharrell Williams, Flying Lotus y Terrace Martin,  entre otros.</p>
<iframe width="770" height="433" src="https://www.youtube.com/embed/Z-48u_uWMHY?rel=0" frameborder="0" allowfullscreen></iframe>
<p>&nbsp;</p>
<p>Si bien las expectativas se mantuvieron altas  para esta nueva etapa en la carrera de Lamar, cierta incertidumbre prevalecía,  ya que no se esperaba que pudiese superar la vara que había colocado con su  álbum de estudio previo. Hasta el día en que <em>To Pimp A Butterfly</em> salió a la luz. A la hora de hablar del nuevo  álbum de Lamar se puede empezar por expandir sus horizontes con las opiniones  personales o con las del saber popular. Lo cierto es que el álbum alcanzó el  estatus de ser uno de los mejores álbumes del género en años, incluso desde la  creación del rap, sumado a ser considerado uno de los mejores del año 2015 por  fuera del radar del hip-hop.</p>
<p>Kendrick lleva el concepto más allá de una  simple historia, esta vez interrumpiendo el principio o el final de sus  canciones con un fragmento de una poesía, que progresivamente se va  desarrollando a través del álbum, cada vez un poco más allá en la visión de la  sociedad, la comunidad negra, el crimen, los derechos, el despertar y el  ascender. Todo esto crece y crece mientras el álbum progresa, con cada  fragmento de esta poesía frenando en una canción que explaya un poco más el  significado de cada una de estas partes. Finalmente el poema estará completo y  dejará no sólo una reflexión, sino unas palabras de fuerte contenido y  enseñanzas al modo de moralejas.</p>
<p>Sexo, dinero, violencia, abusos, amor son  algunos de los temas centrales de las canciones que se extienden durante 78  minutos de grandes composiciones musicales, que no se quedan en un tributo al  más clásico del hip-hop sino también a otros géneros influyentes en la  comunidad negra, componiendo algunas de las canciones más memorables de los  últimos tiempos.</p>
<p><em>To Pimp A  Butterfly</em> es un disco para ser escuchado de pies a  cabeza y más de una vez para descifrar todas esas pequeñas grandezas que forman  el total de la ecuación y cuyo sentido se va alterando cada vez que la persona  se apropia de las letras y la música.</p>
<p>Si bien Kendrick Lamar ha anunciado que su  próximo álbum saldrá en largo tiempo, uno sólo puede esperar, expectante, para  saber si, una vez, más podrá superarse a sí mismo.</p>
<p align="center"><em>Recuerdo  que estabas conflictuado<br />
  Usando  mal tu influencia<br />
  Algunas  veces hice lo mismo<br />
  Abusando  mi poder, lleno de resentimiento<br />
  Resentimiento  que se convirtió en una profunda depresión<br />
  Me  encontré gritando en un cuarto de hotel<br />
  No me  quería autodestruir<br />
  Los  males de Lucifer estaban alrededor mío<br />
  Así que  corrí buscando respuestas<br />
  Hasta  que llegue a casa<br />
  Pero  eso no freno la culpa del sobreviviente<br />
  Yendo y  viniendo, tratando de convencerme sobre las medallas que gane<br />
  O tal  vez cuan sobresaliente era mi establecimiento<br />
  Pero  mientras mis seres queridos peleaban una continua guerra en la ciudad, yo  entraba en otra.<br />
  Una  Guerra que estaba basada en represión y discriminación<br />
  Dándome  ganas de volver a la ciudad y decirle a mis amigos lo que aprendí<br />
  La  palabra era respeto<br />
  Solo  porque tu banda tenga otros colores que la mía<br />
  No  significa que no pueda respetarte como un hombre negro<br />
  Olvidándose  todo el dolor y sufrimiento que nos causamos unos a los otros en las calles<br />
  Si te  respeto, nos unimos y frenamos al enemigo que trata de matarnos<br />
  Pero no  lo sé, no soy solo un mortal, tal vez solo soy otro negro.</em></p>
<p>&nbsp;</p>
<iframe src="https://vid.me/e/wMYj?tools=1" width="770" height="433" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen scrolling="no"></iframe>