<p>Un montaje despojado y muy  austero caracteriza la exhibición de antiguos dibujos de Jorge Gumier Maier que  presenta la galería Mite. Se reúnen allí un conjunto de piezas de pequeño  formato realizadas en 1978; son témperas y aguadas de tinta sobre papel dispuestas  en dos series ubicadas directamente sobre los muros de la sala, y por otro lado  una pieza particular que porta la leyenda &ldquo;Ser germano y retrato de mi madre&rdquo; que  da título a la muestra. Sin atenuantes ni abalorios, carente de los clásicos  dispositivos exhibicionarios, la exposición apunta directo al estómago.</p>
<p>  Las &ldquo;caruchas&rdquo; de Gumier Maier —como  él las ha nombrado— traen una carga dramática, un concierto de imágenes de  máscaras con rasgos dislocados. Estos trabajos en témpera en blanco y negro —en  ciertos casos, con alguna pincelada de color— son transfiguraciones de un mismo  rostro en expresiones de dolor, tristeza, ironía, ternura, enojo y furia. Son  imágenes que trasuntan el sentido de nuestros propios fantasmas en la opacidad  de las tinieblas. Las figuras monocromas y empastadas de impronta expresionista  conllevan un toque mortífero y lúgubre, matizado con el aire paródico y  grotesco de esos retorcidos rostros humanos.<br />
  <br />
  Denotan un contexto histórico y  un momento particular del artista: el aire represivo impuesto por la dictadura  militar y el mundial de fútbol en sede local que pretendió poner velo a las  atrocidades cometidas en aquel período, donde circulaba el absurdo eslogan &ldquo;los  argentinos somos derechos y humanos&rdquo;. En 1978 Gumier Maier padeció una  enfermedad y, según lo relata en el texto curatorial, &ldquo;en ese clima opresivo y  angustiante fue que compulsivamente retomé la práctica del dibujo en pequeños  papeles y con materiales básicos, lo único que podía hacer desde una cama&rdquo;. En  los años precedentes se había volcado a la militancia política dejando a un  lado la producción artística.<br />
  <br />
  El curador de la muestra,  Sebastián Desbats, que es asistente de Gumier desde hace un tiempo, detectó  estos trabajos inéditos, pensó que &ldquo;era lo mejor que había hecho en toda su  carrera de artista&rdquo; y le propuso exhibirlos. El lugar elegido, una galería de  arte contemporáneo dirigida por Nicolás Barraza y Marina Alessio que funciona en  el local 30 del Patio del Liceo, en los márgenes del circuito principal de  Buenos Aires. La opción curatorial de Desbats es acertada en función del  acercamiento directo con la obra sin mediación alguna.<br />
  <br />
  El hallazgo y la puesta en  exhibición de estas piezas develan una faceta no conocida de este artista, y  pone nuevamente en cuestión las categorizaciones de <em>arte light</em> y <em>arte guarango</em> impuestas tempranamente en torno a los planteos estéticos que tuvieron lugar en  la sala de artes visuales del Centro Rojas bajo la dirección de Gumier Maier en  los años noventa. <br />
  <br />
Aparecen las marcas de un sujeto  sensible y emotivo curtido por los avatares de su existir en este mundo  complejo. Un artista que vuelca en su obra lo luminoso y aquí también lo  oscuro, el ying y el yang. La luz y el color apastelado están presentes en sus  producciones más emblemáticas, las pinturas en soporte de maderas caladas al  modo de rulos o arabescos, donde compone figuras de movimiento ondulado que se  recortan sobre el muro o bien se alzan en el espacio. </p>
<p>Gumier Maier, hombre polifacético  que tuvo una activa participación en la construcción del campo cultural local desde  los años ochenta, en su despliegue como periodista, diseñador, crítico, artista  y curador, imprimió una marca indeleble en el panorama artístico argentino de las  últimas décadas. <br />
  <br />
  Sus escritos, de acento  provocador, alimentaron los debates sobre cuestiones significativas, poniendo  en tela de juicio el sentido común de la época. Los artículos que publicó en la  mítica revista <em>El Porteño</em> interpelan  el discurso hegemónico sobre los límites admisibles en el ejercicio de la  sexualidad y cuestionan la moral victoriana que regía en aquellos años, cuando  emergía la problemática del SIDA como una marca estigmatizante. <br />
  <br />
  En el texto del catálogo <em>El Tao del Arte</em> (1997), publicado a  propósito de la exposición que curó en el Centro Cultural Recoleta, discute  sobre las taxonomías impuestas en el mundo del arte y emprende contra los  discursos curatoriales, esa &ldquo;metástasis discursiva&rdquo;. Reafirma su posición y  reclama, en tono poético, por la &ldquo;necesaria innecesariedad de lo artístico&rdquo;, ya  que &ldquo;todo arte es ficción&rdquo;.<br />
  <br />
  Hoy no quedan dudas sobre el  lugar que ocupa Jorge Gumier Maier en el panorama artístico actual. Sus obras  integran numerosas colecciones particulares y forman parte además del acervo  patrimonial de los más importantes museos del país, incluyendo el MNBA. Se pone  de relevancia su trayectoria de varias décadas como activista protagónico del  arte local.<br />
  <br />
Estos trabajos, que se muestran  por primera vez en la galería Mite, suman un eslabón en su producción como  artista. ¡Bienvenido sea!</p>

<?
	include('maier/index.php');
?>
