
<p><strong>Intensa-Mente</strong>, el último gran éxito de Pixar, vuelve a asombrar por
su atrevimiento y su impecable factura técnica, pero… ¿es lo que podemos
esperar quienes aplaudimos antes sus anteriores obras maestras? ¿Está Pixar en
decadencia?</p>


<p >Poco más se puede decir de la productora  Pixar, la niña bonita de Steve Jobs, que no se haya dicho ya. Como mínimo, que  ha revolucionado tanto la industria cinematográfica enfocada al público  infantil como en su día hizo Disney. Y lo ha hecho desde un punto de vista  desconocido hasta ahora: todas las películas infantiles de todas las épocas han  incluido siempre guiños para el público adulto, pero en las películas de Pixar  éstos son tan evidentes y tan continuos que uno no sabe realmente si su fin  último es divertir a los niños o hacer que los adultos se den codazos en las  butacas.</p>
<p>Probablemente los diez minutos primeros de <em>Up</em>, o incluso la primera parte completa  de <em>Wall-E </em>sean de las mejores piezas  cinematográficas, de eso que llamamos &ldquo;cine en mayúsculas&rdquo;, que se han  producido en los últimos años en todo el mundo. El tempo narrativo es  extraordinario, hasta el punto de que deja en un segundo plano la preciosista  factura técnica, a la que sólo hace sombra su rival directo en los estrenos,  Dreamworks. Nos han acostumbrado ambas a filmes para niños que disfrutamos los  adultos gracias a un modo de narrar único. De hecho, era éste el rasgo  distintivo que las diferenciaba de las películas &ldquo;disney&rdquo;, claramente más  infantiles. Sin embargo, tras varios años en los que la decana de la animación  se rindió al talento de Pixar y comenzó a colaborar con ella, el affaire acabó  (después de alguna que otra disputa) con la compra de Pixar por parte de  Disney.</p>
<p>El hecho de que los adultos fueran a los  estrenos de Pixar igual de nerviosos que los más pequeños cambió con la entrada  de Disney. Y fue poco a poco perceptible, más según se sucedían los estrenos.  Apenas distinguible en títulos como <em>Up</em> o <em>Toy Story 3</em>, ya más apreciable en <em>Cars 2</em>, y definitivamente palpable en la  desigual <em>Brave</em>. Es difícil de  describir, pero poco a poco fue ganando el &ldquo;buenismo&rdquo;. Y aunque los detalles de  desazón y oscuridad (el terrible dejarse ir de los muñecos en el final de <em>Toy Story 3</em>, por ejemplo), por qué no de  ironía y causticidad (el temperamento irascible y misántropo del viejo  Fredricksen en <em>Up</em>) siguen presentes,  es innegable que las nuevas películas son más melifluas, más blandas.</p>
<p>Así llegamos a <strong>Intensa-Mente</strong> (<em>Del revés</em>,  en España), la última superproducción de la casa. Una vez superado el peor producto  de los últimos años, indigno del talento de la productora, el cortometraje <em>Lava</em>, nos adentramos en una película con  el argumento más difícil que contar a un niño pequeño: describir cómo maneja el  cerebro las emociones. Y para ello se recrea el interior de la mente de  cualquier ser (no sólo humanos, también los animales), manejada por la alegría,  la tristeza, el miedo, la ira y el asco. Todo ello recreado en una especie de  cabina de mando desde donde controlan los sentimientos de una niña de diez años,  intentando conseguir recuerdos &ldquo;esenciales&rdquo; que sirvan de sostenimiento de unas  &ldquo;islas&rdquo; que forman su personalidad. Semejante tronco argumental desde luego no  es propio de una película de niños, pero la magia de Pixar consigue crear de  nuevo una simbiosis perfecta entre entretenimiento infantil y asombro para  adultos. Pero…</p>
<p>Dejando a un lado los acostumbrados guiños al  público más mayor, en caso de duda la película se decanta siempre por el lado  más fácil, la parte más simplista. No se vale del típico humor corrosivo, no  corre riesgos, como siempre hizo Pixar. En <em>Up</em>,  por ejemplo, el protagonista es un matrimonio sin hijos, y un niño cuyo padre  le abandonó. En <strong>Intensa-Mente</strong> la  familia no puede ser más tradicional, ni más convencional, sin olvidar el detalle  tan obvio de que el cerebro de la madre lo domine la tristeza y el del padre la  ira; o que él tiene al fútbol siempre en la cabeza y ella se acuerda  constantemente de un amante brasileño que perdió. Y mejor no recordar esa  &ldquo;fábrica&rdquo; de novios imaginarios que ayudan a Alegría; aunque esa &ldquo;nada&rdquo; donde  caen los recuerdos compense tanta hiperglucemia.</p>
<p>Pixar ha hecho de nuevo una gran película,  hermosa y entretenida, pero la senda tomada en los últimos tiempos no augura un  futuro prometedor para aquellos que esperaban de ella mucho más que una simple  productora infantil. El tiempo dirá adónde se dirige.</p>
