<p>En su afán por el  empleo, el hombre, se cree capaz de aceptarlo todo. Madrugadas a la intemperie,  corbatas baratas, ruidos y disfraces; palmadas en la espalda. Lo monetario,  fetiche inalcanzable cuando impone su ausencia o magma entre los dedos las  pocas veces que arde, pasa a un riguroso segundo plano ante la pasión por  creerse capaz. El hombre deja, pues, de categorizar la búsqueda según la  remuneración posible para adentrarse en el siempre pantanoso terreno de agarrar  cualquier cosa. Y aunque lo hace con naturalidad, cabría decir, si estas  palabras no fueran invención todas ellas, que el hombre equivoca desde el  principio su camino; cabría alertarle que a su edad y según sus condiciones  materiales recientes el empleo, lejos de buscarse, se reza. Y que el orgullo  por creer que algo se elige es el punto de no retorno, cuando la derrota no ha  hecho más que empezar a chiflar.</p>
<p>Ignorante del  desenlace, el hombre busca su oportunidad en nichos de negocio donde no se  diría a priori que florecieran las ofertas. Una tarde ligeramente inclinada  hacia la desolación se topa sin embargo con un milagro. Un pequeño cartel en  una pequeña puerta de una tienda pequeña y luminosa. </p>
<p align="center">DOBLADOR BUSCAMOS</p>
<p>Como una leona que  caza en beneficio de su macho, el hombre se lanza sobre el verbo sin detenerse  siquiera en la incógnita del nombre adjetivado. Dos mujeres mayores, casi de su  edad, se adivinan como un matrimonio de uso, acaso hermanas. Ellas y el aire  entalcado alcanzan para distraer al hombre de las bobinas que cubren las  paredes hasta el techo, de las tijeras que cuelgan en los estantes de madera.  La distracción lleva a la confianza. Antes de presentarse, el hombre quiere  quedarse a vivir ahí. Las hermanas hablan pausado. Cuando bajan la cabeza  parecen susurrarse a sí mismas pero nunca se pisan; una recoge con similar  timbre de voz lo que la otra deja en el aire; la sucesión adormece al hombre.  No importa que el trabajo consista en acomodar las telas arrugadas de una  habitación y colocarlas dobladas en el cuarto contiguo. No importa que la paga  sea tan magra como en apariencia sencilla es la tarea. Sentirse en casa no  tiene precio.</p>
<p>La pérdida del sentido  del tiempo comienza casi de inmediato. Si tuviéramos la oportunidad de preguntarle  cómo se desarrollaron los hechos, el hombre sería incapaz de responder más que  con balbuceos. No recordaría cuándo sospechó por primera vez que las telas eran  las mismas cada día, ni que el volumen de negocios del emprendimiento fraternal  no parecía justificar las vueltas al mundo de tela que dobló en los años que le  quedaron de vida. No aceptaría el paso idéntico de las horas, el paso idéntico  de las telas de una habitación a otra. Y menos aún aceptaría la futilidad de  cobrar monedas. El hombre, con la naturalidad que da el saberse vencido, transita  sobre el interés con el desaire del dandi. Ahora es doblador. No interesa más  que el doblar para doblar.</p>
<p>Con el paso de los  años el hombre pierde facultades de forma crecientemente evidente. Cierta  atrofia articular le resta destreza y paciencia; se le alargan los pasos que  separan una sala de otra. Tiene frío todo el día, a pesar del rumor cálido de  las telas. Cuando el temblor comienza a impedirle el ejercicio de su tarea él  sigue creyendo que aún hay tiempo, como si el latido fuera arena. Las hermanas,  en efecto, permanecen incólumes cuales sostenes de partenón a la espera de un  nuevo milenio. Nada menos.</p>
<p>El día llega siendo  como cualquier otra noche. El espectro de lo que fue el hombre acaba de doblar  la última tela. Los cuartos no volverán a llenarse más que de crepúsculo.  Apenas por un instante cruza por su cabeza el preguntarse por qué. Se queda  quieto, queriendo hacer lo que hace, confiando en que la espera sea ganancia.  Con firme amabilidad, las mujeres se alistan.</p>
<p>–Ahora –dice una.<br />
  –Vamos a cerrar  –concluye de inmediato la otra.</p>
