<p>Fundada en 1726, la ciudad de Montevideo,  junto con Buenos Aires, es una de las dos capitales nacionales que tienen sus  orígenes en las orillas del Río de la Plata. Y esa impronta que de algún modo  debería dar cierto criterio de unicidad, no tiene ningún asidero cuando de la  relación con el río de marras se trata. Los montevideanos llaman el mar a ese  río que tiene la particularidad de ser el más ancho del mundo, alcanzando los  220 km de extensión en su boca. La diferencia es notable: la rambla uruguaya  invita al paseo, a la mateada, al disfrute; mientras que la ribera argentina apenas  ofrece una costanera en altos, en la cual muchas familias se ubican a pescar  mientras improvisan un pic-nic. Y si allá la costa está sobre el filo mismo de  la ciudad, aquí hay que recorrer muchas cuadras para asomarse a ver esa enorme  masa acuática. Esa rambla es parte del encanto; uno de los grandes bastiones,  junto a la belleza colonial y una rica arquitectura urbana que hacen de la  capital uruguaya una ciudad grata para conocer y recorrer. Si a eso se le suma  una oferta gastronómica de alta calidad, el visitante tendrá dicha por doquier.  Hace pocas semanas, viajamos por Montevideo y recogimos algunas experiencias  para el paladar que recomendamos con el entusiasmo con que lo hacemos  habitualmente.</p>
<br />
<span class="image_cen1"><img src="images/2901.jpg"></span>
<p>Uno de los paseos obligados para el turista es  el Mercado del Puerto, un enorme galpón construido en Liverpool y que tiene un  inevitable parentesco con las construcciones que los ingleses usaron para los  ferrocarriles en el cono sur. Fundado en 1868 por el español Pedro Sáenz de  Zumarán y un <em>holding</em> de empresarios  locales, es un histórico polo gastronómico a metros del puerto de la ciudad.  Para comenzar, nada como acodarse en la barra de Roldós antes del mediodía y  tomarse un Medio y medio, bebida uruguaya por excelencia, creada por el dueño  del lugar, allá en los albores del 1900, haciendo una mezcla mitad de espumante  dulce, mitad vino blanco seco. Conocemos a quienes han intentado replicarlo sin  éxito y en el mismo bar pueden adquirirse, a muy buen precio, un par de  botellas para disfrutar con amigos y familiares.</p>
<br />

<span class="image_cen1"><img src="images/2902.jpg"></span
><p>A medida que pasan los minutos, el público que  circula en el Mercado se va haciendo cada vez más espeso, atraídos por los  aromas de las parrillas y restaurantes, y las charlas comienzan a tener un  ribete festivo. Para el almuerzo, basta con hacer unos pocos metros y optar por  seguir en la onda barra o sentarse a una de las mesas de El Palenque donde el  comensal puede elegir entre una amplia variedad de platos. Si bien predomina la  parrilla, ubicada a la vista en el corazón del lugar, recomendamos aprovechar  la ocasión para clavarle el diente a un exquisito Pulpo a feira, que es algo  así como pulpo a la gallega, con suave oliva y rico pimentón, que hará las  delicias de quien lo coma. Para después de esa entrada, la merluza negra y el  atún rojo son dos buenos complementos para un paseo por la mesa marina.</p>
<br />

<span class="image_cen1"><img src="images/2903.jpg"></span>
<p>Después de no privarse de almorzar tupido,  viene más que bien un paseo por la Ciudad Vieja, a pocas cuadras de allí, donde  el visitante tendrá la oportunidad de visitar museos variados, cafés notables  y, por ejemplo, ponerse a charlar con Gabriel Monteverde, el dueño de La Vieja  Telita, un local/centro de cultura, donde el lutier expone unos instrumentos  tan impactantes como poco convencionales en una casa, propiedad de su abuelo,  en la que habría vivido el mismísimo José de Artigas. Luego de un largo rato de  charla, sugerimos pasar por Volverás a mí, una boutique de chocolate en la que  los amantes del cacao estarán de parabienes. Tabletas rellenas con café,  naranja o pasas de uva; láminas de cacao amargo con cristales de sal marina,  pimienta de Cayena o jengibre; bombas de chocolate y bombones varios son los  puntos altos de la oferta para todos los paladares. Artesanales, bien servidos  y mejor presentados, ofrecen chocolates hechos con cacao seleccionado de  distintas zonas de América: Ecuador, Brasil, Venezuela, Costa Rica, Perú y  sigue la lista. Como a un amigo de la casa le gusta el chocolate de alto  porcentaje, nos trajimos unas bombas de caco ecuatoriano al 96% que combinan de  maravillas con vinos dulces para postre como el Malamado, de bodegas Zuccardi,  que fue el elegido para la ocasión de compartir una experiencia chocolatística  que no es del cotidiano…</p>
<br />

<span class="image_cen1"><img src="images/2904.jpg"></span>
<p>Todo paseo tiene una pausa necesaria. Para  sentarse unos ratos y compartir charla, uno de los bares históricos de la zona  del puerto es el Café Brasilero, aquel que solía frecuentar el escritor Eduardo  Galeano. Típico bar con muchos años de historia, hace pie en los exquisitos  cafés express y unas tortas entre las que se destaca el crumble de peras.  Luego, para ayudar a procesar la explosión de sabor, recomendamos un paseo por  la rambla, hacia la zona de Punta carretas donde se yergue el faro de la  ciudad, anunciando su península más prominente, previo paso por el Museo Torres  García, para luego subir una de las tantas lomas que Montevideo ofrece y llegar  a hacer un alto en el Parque Rodó. Los más dispuestos, podrán alquilar  bicicletas acuáticas para pasear por el lago artificial; los más holgazanes,  sentarse a ver el sol que cae sobre las tupidas copas de los árboles.</p>
<p><br />
  
  <span class="image_cen1"><img src="images/2905.jpg"></span></p>
<p>Ya por la noche, recomendamos acercarse al  restaurante Francis, en pleno corazón del barrio de Punta Carretas. Fundado en  2002 con la premisa de ofrecer una carta cuidada y platos elaborados con  materia prima de alta calidad, con el paso del tiempo fue afianzándose como uno  de los referentes gastronómicos de la ciudad. Lindo, limpio, tranquilo y  acogedor, lo que se sirve está acorde a la idea con la que fue fundado y a las  ganas de los comensales de pasarla bien y comer rico. La oferta incluye  parrilla, pastas, risottos, pescados y carnes, destacándose por su sabor las  mollejitas de corazón al champagne y el cordero confitado en reducción de  Tannat. Con amplia variedad de vinos locales, argentinos y chilenos para  acompañar la comida, es una apuesta a ganador que la gente se irá contenta,  satisfecha y con la convicción de que en alguna otra visita, volverá a por más.</p>
