<p>Como él anticipó  en un poema memorable. &ldquo;Piedra negra sobre una piedra blanca&rdquo;, falleció en  París pero sin aguacero, y no un jueves sino un viernes santo. A las 9 y 20  horas del 15 de abril de 1938 se produjo su muerte. Y sin embargo, cuánta vida  nos ha seguido dando. Mi descubrimiento personal, hondo e íntimo, de César Vallejo  me resultó un hecho extraordinario. No sólo porque ocurrió a los 15 años sino,  también, porque mi primera percepción de su enorme, profundísima poesía fue absolutamente  inocente, inesperada (algo similar me aconteció, contemporáneamente, con  Roberto Arlt).</p>
<p>Había allí algo  encarnado en lenguaje que iba más allá del lenguaje. Y el sentimiento se  contagiaba sin posibilidad alguna de retórica, latente en su palabra, viva. Y  se dio entrañablemente vinculado con dos acontecimientos que también se me  hicieron legendarios: la Guerra Civil española, con aquellos humildes  milicianos, los voluntarios que defendieron a la República, y el hecho de  que en su sangre se mezclaran –todavía de manera inconsciente para mí– lo  celtíbero y lo indígena.</p>
<p>La madre de César  Vallejo se llamó María de los Santos Mendonza Gurrionero (&ldquo;de pecho en pecho  hacia la madre unánime&rdquo;), y era hija del sacerdote gallego Joaquín de Mendonza  y la india chimú Natividad Gurrionero. Pero no sólo eso. También su padre,  Francisco de Paula Vallejo Benítes (&ldquo;Mi padre, apenas, / en la mañana pajarina,  pone / sus setentiocho años, sus setentiocho / ramos de invierno a solear&rdquo;), no  sólo era hijo de otro sacerdote gallego, José Rufo Vallejo, sino que su propia  madre también era otra india chimú, Justa Benites.</p>
<p>Y eso no es todo.  César Vallejo nació el 16 de marzo de 1892 en una Compostela indoamericana, la  peruanísima Santlago de Chuco. Y en su sangre conviven, se confunden, se  unifican, la <em>morriña </em>dolida del  gallego trasplantado con la melancolía sangrante del indio sometido. Y los  entresijos de la mitología católico-cristiana, ineludiblemente entrelazados con  verdaderas, auténticas historias de amor, junto con todo lo que arrastra haber  nacido de sangre indígena en el mismísimo meollo del Perú de los Incas.</p>
<p>¿De dónde sale  sino la &ldquo;Dulce hebrea&quot; de <em>Los  heraldos negros</em> (1918) a la cual se le pide &ldquo;Desclávame mis clavos oh nueva  madre mía!&rdquo;, de dónde la amada que se ha &ldquo;crucificado / sobre los dos maderos  curvados de mi beso&rdquo;? ¿O, incluso, &ldquo;un viernesanto más dulce que ese beso&rdquo;? Por  supuesto que del lenguaje. Pero no sólo del lenguaje. De donde surgió también  ese magnífico <em>TriIce</em> que, desde  Trujillo, en 1922, agota de antemano muchas de las futuras experiencias de las  vanguardias europeas. O aquel que a mí me parece el libro más hondo y tocante –y  logrado– que haya producido la guerra civil: <em>España, aparta de mí este cáliz</em>, mucho más que póstumo, y no por  casualidad escrito por un hijo de América (&ldquo;¡Niños del mundo, está / la madre  España con su vientre a cuestas!&rdquo;). </p>
<p>Y alrededor del  cual la misma agonía del poeta, casi enhebrada en la lumbre del mito, vueltos  uno solo destino personal y momento histórico, se vuelve asimismo luminosa  evidencia, verbo hecho aliento.             (Según  otro poeta, su amigo Juan Larrea, las últimas palabras de Vallejo fueron: &ldquo;Me  voy a España&rdquo;. Es decir, a la   España republicana, que estaba desangrándose también –al  mismo tiempo– en su &ldquo;agonía mundial&rdquo;. En la Clínica Arago, donde  falleció, los médicos no atinaban a explicar la verdadera causa de su muerte.  Pero al año siguiente, 1939, al editarse por fin sus indelebles <em>Poemas humanos</em>, escritos probablemente  entre 1930 y 1937, pudieron conocerse estas otras palabras tan suyas, no sólo  premonitorias: &ldquo;En suma, no poseo para expresar mi vida sino mi muerte&rdquo;).</p>
<p>¿De dónde surge,  digo, algo así, de tal calibre? De la lengua humana, empapada de vida y también  fuente de vida, vida ella misma, instintiva y orgánica, cargada de los humus  nutricios de la pequeña historia y de la gran historia, pero también de los  instintos y los sueños, de las ansiedades y los deseos de los hombres. De un  hombre capaz de ser, a la vez, él mismo y todo lo humano, lo más humano de lo  humano, de ser único y general, al mismo tiempo, entre todos los hombres, junto  a todos los hombres. La de César Vallejo no es una voz unánime, sino prójima,  íntimamente próxima. (Qué otro, sino un gran poeta, podía habernos dejado esa  sucinta clase –magistral– de economía política: &ldquo;la cantidad enorme de dinero  que cuesta el ser pobre...&quot;).</p>
<p>Me enorgullezco limpiamente de saber que el primer  hombre que me hizo descubrirme latinoamericano llevó en sus venas la sangre de  mis antepasados labradores gallegos, y también la noble sangre de los primeros  hijos de la América  primera, la aborigen, la indígena. Como la lengua, como la vida, toda sangre es  espléndidamente mestiza. Sólo la muerte es pura.</p>
<p>¿Me será permitido insistir, con modesta firmeza,  que no puedo dejar de percibir a César Vallejo como el más grande poeta de la  lengua castellana, y hasta quizás no sólo en el siglo veinte?</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<h3>Vallejo, César</h3>
<p>Nadie estuvo más hondo<br />
  ni más cerca.<br />
  Nadie llegó tan lejos<br />
  más temprano.<br />
  Nadie fue más ninguno<br />
  y menos Nadie.</p>
<h4>Rodolfo Alonso</h4>
