<p>1.<br />
  Cuando Esteban comenzó a enfermarse, yo  planeaba en secreto mi primera mudanza a un pequeño departamento de la capital  y mi hermano, que se había independizado de mis padres hacía pocos meses, se  enfrentaba a un vendaval de problemas domésticos. Quizás yo no pensaba como el  resto de la humanidad o al menos como mi familia, pero me resultaba perturbador  que, mientras la psicosis y la debacle física arrinconaban a mi tío como una  manada de yaguaretés, a Tute y a mis padres solo les preocupara encontrar un  albañil barato y eficiente para las innumerables tareas de refacción que la  casa pedía  a gritos.<br />
  Se trataba de una vieja propiedad de  Tute: un chalecito de tres ambientes, bastante venido a menos ya que a nadie le  había interesado mantenerlo en forma, con un jardín luminoso, un galpón de  chapa que antes había funcionado como un gallinero y, finalmente, un garaje  cubierto de papeles, boletas, un extraño salvavidas y cuadernos viejos. Me  gustaba especialmente el jardín, lleno de plantas y árboles frutales, y sentía  envidia que Esteban y de alguna manera mis padres hubieran cedido esa casa hermosa  a Tute y no a mí. </p>
<p>2.<br />
Para el futuro departamento compré una  pecera alargada y algunos peces de colores radiantes. Si no podía tener un jardín,  pensé, necesitaba algo que me hipnotizara por las noches. Pero todavía faltaba  bastante para tener mi propio espacio, muchas cuentas por cerrar, decisiones  que postergaba y tiempo, con lo cual permanecía en mi cuarto hasta muy tarde,  imaginando la pecera sobre una mesa de madera centrada en la oscuridad. Los  peces daban vueltas y yo mojaba el dedo y lo hacía girar en el agua helada. Sin  dudas, era una tontería. ¿A qué clase de obsesivo se le podía ocurrir comprar  mascotas silenciosas para una casa que aun no tenía? </p>
<p>3.<br />
  Un viernes de mayo Tute y su novia Ludmila  se mudaron. Una semana después organizaron un asado para festejar la  inauguración. El domingo estaba esplendido, hacía fresco a la sombra pero el  sol calentaba mucho y uno sentía como la piel se energizaba en contacto con la  luz. Al entrar en la casa, recordé las veces en que había visto a Esteban  trabajando en esa misma cocina, pasando números de quiniela por teléfono,  escuchando música y tomando tragos largos de ron con cola. La cocina, ahora,  estaba muchísimo más limpia y ordenada, había repasadores nuevos, bandejas de  cristal y copas trabajadas dispuestas sobre la mesa. En el garaje, en lugar de  cajas, había otras cajas más grandes llenas de ropa y muebles apilados, un  televisor roto, una máquina de fax y algunas llantas de auto llenas de polvo y  moho. Más allá, una mesa larguísima de tablones, donde unas horas más tarde nos  sentaríamos a almorzar. <br />
  Lo primero que me dijo Tute al verme fue que se habían quedado sin hielo  para las bebidas, lo que representaba un gran problema. Le respondí que yo me  ocupaba. Media hora después volví cargado con tres bolsas y las manos congeladas.   <br />
  – ¡Por fin! – me dijo Ludmila. <br />
  La felicité por la casa y atravesamos el living hasta un gran barril  lleno de agua y cervezas. Corté una de las bolsas, esparcí los bloques de hielo  y coloqué las otras bolsas encima. Después echamos sal gruesa. <br />
  – Esto conserva mejor el frío – expliqué, mientras abanicaba el paquete.<br />
  El jardín estaba lleno de gente, entre amigos de Tute, la familia de  Ludmila, chicos y un perro atado a la manija de una puerta que no paraba de  ladrar. También había música, vasos de cerveza y fernet y un aroma fantástico a  carne y achuras. Charlé con mis padres y con algunos conocidos. En algún tiempo  muerto, escuché que mi hermano explicaba:<br />
  – Todavía estamos lidiando con cosas de vivir en una casa de solos,  aunque más allá de las cuentas y los vecinos que no conocemos, todo es super  lindo, todo es positivo. Cuando lo decoremos va a ser tan bueno. <br />
  En la casa de al lado, por el aroma, los vecinos también cocinaban un  asado. Me asomé por la medianera y vi a un hombre canoso que atizaba el fuego.  La carne estaba envuelta en papel celofán y, en contacto con las brasas,  largaba bastante humo. A su lado había una mujer y otro hombre que observaba un  poco envuelto en la sombra, con un vaso en la mano. Cuando el otro se fue, lo  vi moverse y bajar el nivel de la parrilla, lo que me pareció extraño, algo así  como un exceso de confianza ante el asador. <br />
  Más tarde me crucé con mi padre y le pregunté por Esteban; me respondió  que estaba encerrado, que no quería salir y al parecer no atendía nunca el  teléfono. Me lo imaginé durmiendo o sentado inmóvil delante de una pecera igual  a la mía pero con peces más grandes, tan gordos que apenas podían nadar. Después  quise saber porqué no lo iban a buscar y mi padre levantó los hombros. Me  acordé de mi abuelo y de su biblioteca marxista, añejada, con los lomos  descocidos por el tiempo. Marx y Lenin y la teoría política para obreros latinoamericanos  del siglo XX. <br />
Después de comer me senté en un rincón a tomar cerveza y a fumar. Nicolás,  uno de los hermanos de Ludmila, tenía la vista clavada en su notebook. Era  diseñador gráfico y debía hacer unos iconitos para graficar un concepto para la  campaña publicitaria de una empresa de seguros: expectativa de vida digna. Era  algo urgente y estaba desesperado. No pude ayudarlo y recordé un capítulo de  Los Simpsons, donde el papá de Milkhouse tenía que dibujar un sentimiento un  poco abstracto y solo hacía un círculo un poco deforme que nadie conseguía  descifrar. </p>
<p>4.<br />
Le decían el Arquitender, porque tenía  fascinación por la coctelería y se había licenciado en arquitectura hacía  muchos años, tantos que ya no recordaba casi nada sobre el tema. Era productor  de un canal que transmitía documentales y me había encargado preparar los  guiones para un programa sobre flamencos. Entonces empecé a buscar todo la  información que podía recolectar: libros, Internet, youtube. Descubrí que los  flamencos nacen blancos, toman su color rosado o anaranjado por el pigmento del  alimento que consumen y, cuando envejecen y se van acercando al momento de su  muerte, comienzan a decolorarse porque ya no pueden procesar la comida.  Descubrí otra cosa: que los flamencos son hipersensibles. Cuando los molestan,  huyen en manada; si una hembra está incubando, suele alejarse y abandonar para  siempre a sus crías.</p>
<p>5.<br />
Vi un documental de la Nacional  Geographic donde explicaban que los flamencos eligen lugares extremos para  reproducirse. Un ejemplo magnífico son las lagunas que poseen un PH tres o  cuatro veces más alto que el mar. Ellos toleran el ácido y temperaturas  elevadísimas o muy bajas. Puede ocurrir que estén en una laguna de África y que  por la noche el agua se congele y ellos queden atrapados. Así dormitan, hasta  que amanece y logran salir volando. Me pregunté si todos estos datos que  aprendía sobre los flamencos no tendrían alguna incidencia o mensaje secreto en  mi vida. Pensé, al contrario, que si quería comprenderlos, necesitaba vivir a  su ritmo, captar los hilos invisibles que tejen sus acciones.</p>
<p>6.<br />
  Un día mi madre me comentó que tenía varias  cosas que llevarle a Tute y pensé que era una buena excusa para visitar su  casa. Era un jueves por la noche. Tute se sorprendió al verme, me hizo pasar y  descubrí que había colocado un aro de básquet en el jardín. Tenía una pelota un  poco ovalada y, mientras charlábamos, empezamos a ensayar algunos lanzamientos.  Abrimos una cerveza, mientras Ludmila estudiaba en la cocina y nos miraba por  la ventana, inclinándose hacia delante. Hubo un momento extraño en que una  energía extraña se apoderó de nuestros cuerpos, un flash que venía del pasado  para sacarnos la modorra. Entonces apoyamos los vasos en el suelo y decidimos  jugar un partido a diez puntos.<br />
  – ¿Así que vos también pensás mudarte? – preguntó mi hermano.<br />
  – ¿Cómo sabés?<br />
  – Me dijo papá.<br />
  Entonces salté con todas mis fuerzas, bajé un rebote y retrocedí para  atacar el aro. Anoté y mi hermano resopló con furia.  <br />
  – Si, estoy en eso, juntando plata. Buscando, en resumen – respondí. <br />
  Después volví a anotar. Jugué de post y anoté de nuevo. Mi hermano se  puso serio.<br />
  – No es fácil – expliqué.<br />
Tute  encestó algunos puntos y el partido cobró intensidad. Nos empujábamos y ninguno  de los dos regalaba nada. En una jugada la pelota se me escapó de las manos y  corrí para recuperarla. Choqué con Tute, que resbaló y se golpeó contra la  pared. Pegó un grito largo, lleno de saliva. Cuando Ludmila salió al patio, mi  hermano estaba sentado en el piso con las manos cubiertas de una sangre bordó,  que manaba con furia de algún punto impreciso de su cabeza.  </p>
<p>7.<br />
  No volvimos a vernos hasta que Esteban  murió. Fue repentino y algo inesperado. Lo encontró uno de sus amigos, quien,  después de llamarlo durante días, forzó la puerta y descubrió el cuerpo en la  bañadera. Se había suicidado cortándose las venas, como hacían los mafiosos  italianos en las películas. <br />
Hubo una ceremonia triste, a la que asistió poca gente. Esteban era  soltero, no tenía más familia que la nuestra y, en los últimos años, había  puesto una especial dedicación en alejarse de todo el mundo. Mi padre se sentía  culpable por su muerte y Tute, imaginaba, debía de estar feliz e incómodo por  haber heredado la casa. Alguien mencionó que Esteban tenía los primeros  síntomas de la enfermedad de Parkinson y de Alzheimer, los males que habían  carcomido el cuerpo de mi abuela. Parecía lógico: Esteban la había cuidado  hasta el final de su vida y ahora él, como una maldición, heredaba la  enfermedad y la muerte. Aquella noche observé a mi padre como nunca lo había  hecho: tenía los ojos rojos y estaba pálido. El café lo embotaba y se movía  como un fantasma, balbuceando cosas incoherentes. Tenía miedo, un miedo  terrible.  Se había quedado solo.</p>
<p>8. <br />
  En noviembre de ese año viajé a Mar Azul  para visitar inmobiliarias y preparar el alquiler de una de las propiedades que  había dejado Esteban. Mis padres estaban demasiado ocupados, yo no había  conseguido mudarme y me parecía buena idea tomar un descanso y encargarme del  asunto. La casa estaba ubicada en un lote gigantesco, a cuatro cuadras del mar,  entre medanos y pinos altísimos y desgarbados. Tenía cinco habitaciones, dos  baños, un estilo desordenado, con espacios inservibles y algunos problemas de  deterioro, especialmente en el techo y las tuberías. <br />
  Cuando llegué descubrí que habían cortado la electricidad por falta de  pago y, en la oscuridad, la casa me pareció bellísima. Comprendí que yo podía  vivir en ese lugar por algún tiempo, restaurarla con dedicación y amor.<br />
  Trabajé durante algunas semanas: limpié,  ordené, hice cambiar algunos zócalos, hablé con un plomero y un techista que me  informó que, en las tablas de madera, había unos insectos que carcomían el  material. Como era imposible descifrar cuántos eran y en qué proporción se  habían reproducido, lo mejor era remover todas las vigas. Imaginé bichos gordos  y tambaleantes, con pinzas en lugar de dientes, sin antenas y ciegos como topos.   <br />
Comuniqué el problema a mis padres y decidí quedarme para vigilar la  obra. Así pasaron otras dos semanas. Mientras tanto escribía el guión sobre los  flamencos, paseaba por las calles de arena, caminaba hacia el mar, fumaba, volvía  a la casa y pensaba en la vida que podría llevar en la costa, trabajando como  profesor en un colegio secundario o cuidando los jardines inmensos de los  veraneantes. </p>
<p>9.<br />
  Un día caluroso de diciembre conocí a  Lorena. Trabajaba en la oficina de turismo de Mar Azul y fue ella quien me  recomendó al techista que me habló de aquellos insectos gordos y ciegos.  Imaginé que en la costa debía haber muchos hombres y mujeres que vivían en  constante movimiento, yendo de un lado a otro, y, por este motivo, debía ser un  sitio ideal para tener sexo sin compromisos. Algo así le confesé a Lorena después  de varias cervezas, muy tarde, cuando ya habíamos cenado e inaugurado la ex  casa de Tute con un brindis.<br />
  – ¿En serio pensás eso? – preguntó.<br />
Le dije que, al menos, eso era lo que nos imaginábamos los porteños.  </p>
<p>10.<br />
  Lorena tenía manos de nadadora, ásperas y anchas y con aquellas manos  cortaba en rodajas un pepino y un limón, para preparar unos gin tonic. Por las  ventanas de su casa ingresaba una luz acuosa, contaminada de mar, pero blanda,  como si fuera marzo o abril y no diciembre.  Era una luz triste y depresiva que anunciaba  el final de todo, cuando, en realidad, me sentía en la previa de algo  importante, un instante de largada. Pero bebimos los tragos, que estaban  deliciosos, y Lorena me contó que siempre le interesó la coctelería. Recordé  pedazos de mi otra vida, mi hermano, Esteban y los flamencos, mientras ella  enumeraba bebidas, rompía hielos y mezclaba frutas.<br />
  Me pregunté en qué consistía la hiper sensibilidad de los flamencos, si  en realidad no era una excusa para no abordar los problemas con un poco de  inteligencia. Ante aquella luz, en aquel balneario, todo se presentaba un poco  extremo y volátil. Las cosas podían ser de una manera o de otra. Salimos a un  patio sin flores, con vegetales secos.<br />
  – A veces la sal y el viento pudren las plantas – dijo Lorena, mientras  sorbía el gin con tónica y cubría con la mirada el jardín.     <br />
  <br />
11.<br />
Una tarde Lorena me explicó que, si  esperaba que mis cosas salieran bien, era necesario ponerle nombre a la casa.  Comenzaba la temporada, los primeros turistas se acomodaban en sus grandes  casas de veraneo, en los hoteles de Mar Azul, recorrían el centro y tomaban sol  y reían y disfrutaban como si la vida, de pronto, se hubiera convertido en un  flujo interminable de buenos momentos y placeres incoherentes pero hermosos.<br />
  – No  importa si te pensás quedar o no, es para la buena suerte – dijo Lorena.<br />
  Pero había decidido quedarme y no volver  jamás a Buenos Aires. Entonces fuimos al taller de un artesano que tallaba  madera. Era viejo, tenía trenzas en el pelo y vivía en una cabaña construida  con troncos y botellas; mientras fumaba una pipa nos mostró distintos cortes de  madera, tipologías de letras y nos indicó los precios. Me pareció correcto y  prometí volver al día siguiente con una decisión. Aquella noche me desvelé pensando  en como podría llamar aquella casa enorme que se estaba convirtiendo en mi  hogar, en esa casa que había sido de Esteban y ahora pertenecía a mis padres o  a quien la reclamara primero. <br />
  A la mañana siguiente llamé a Lorena.<br />
  – ¿Estás seguro? – me preguntó, conociendo la historia que había detrás  de aquel nombre.<br />
  – Si – respondí. <br />
El día estaba nublado y prometía electricidad. Caminé algunas cuadras,  me metí en un bosque de pinos y me senté debajo de un gran árbol. Estuve un  buen rato, pensando hasta que un escarabajo emergió entre los granos de arena y  la paja, y trepó por mis pantalones. Decidí aplastarlo. Lo hice con paciencia,  presionando de a poco con el pulgar, hasta que el escarabajo hizo un pequeño plop  y estalló, con el sonido que hacen las cosas huecas al quebrarse. </p>
<p>&nbsp;</p>
