<p>Todos creemos que la  radio es un aparato de radiofrecuencias que recibe ondas electromagnéticas, que  viajan por el aire y hasta por el vacío. Nos han metido también en la cabeza  que estas ondas pueden partir de Necochea, subir al espacio, rebotar en un satélite  que flota más allá de la atmosfera y bajar directamente a una computadora en  Singapur para seguir la final del campeonato regional del municipio de la  costa. Es evidente que se trata de un disparate.</p>
<p>La verdad es que  hay una trama invisible de letras que planea sobre nuestras cabezas.  Conversaciones en un colectivo, secretos compartidos por celular, debates y  hasta una gallega que nos indica el camino a través del GPS. Todo flota en esa  capa que, a diferencia de la del ozono, no tiene el más mínimo agujero. Y no  solo eso, no cabe ni una letra más en este tejido. De no ser semitransparente viviríamos  hace miles de años a oscuras. Y si fueran materiales de construcción hace  tiempo que no se podría salir a la calle. A veces me asusta la posibilidad de  que una noche esas palabras se solidifiquen en forma de meteoritos y caigan sobre  nosotros. Sería muy difícil explicarle al seguro que mi auto quedó aplastado  bajo la frase &ldquo;Jodete por soberbio&rdquo;.</p>
<p>Pero es gracias a  este amasijo de letras que existen los libros, las ideas, las preguntas y todas  las respuestas posibles; también los idiomas y los malentendidos. Hay días,  generalmente en primavera, en los que la presión atmosférica hace bajar la  trama hasta el pecho y es en esas tardecitas donde hay altas probabilidades de  romances.</p>
<p>No sabemos bien el  origen de este campo de símbolos, pero de un tiempo a esta parte está en serio  peligro de extinción.</p>
<p>Rápidamente se está  formando sobre ella un toldo de imágenes que le quita transparencia. Fotos  enviadas por celular, recuerdos de la Sagrada Familia colgados en la nube,  pantallas flexibles que transmiten novelas y documentales sobre el origami.  Este techo da una falsa ilusión de seguridad, de refugio de nuestra memoria. Es  sabido que de todos nuestros sentidos, es a la vista a la que le adjudicamos la  mayor certidumbre. &ldquo;Ver para creer&rdquo; es otra de las mentiras que repetimos como  la radiofrecuencia volando hacia la Spika. Creemos que porque conservamos en un  disco rígido las imágenes, podremos revivir esos recuerdos. Sin embargo, lo único  que hacemos es acumular bytes que nunca volvemos a ver. Como el sol naciente,  son los japoneses los que acumulan las mayores reservas de fotos inútiles.</p>
<p>No hay que ser un  genio para comprender que de avanzar esta oscuridad, las palabras, y las ideas,  perderán su nitidez hasta desaparecer.</p>
<p>Sin embargo me ha  llegado el rumor (en realidad los conozco perfectamente, pero prefiero ser  discreto) de que hay una célula rebelde que se junta en una biblioteca de  barrio a resistir el avance de la tormenta de imágenes.</p>
<p>Aferrados al  estandarte de la esperanza, insisten en que es la semitransparencia de la  antigua capa de letras la que nos permite ver no sólo las estrellas, también  ángeles o marcianos. Y también esas historias que no precisan rebotar en ningún  satélite para emocionarnos con la sola mención de una frase de algún libro.</p>
<p>No todo está  perdido.</p>
<p>Letra o muerte.</p>
<p>Venceremos.</p>
<p align="right" style="font-size:15px">&nbsp;</p>
