<p>Marie-Claude  Char me telefonea alborozada: &ldquo;¡Gallimard decidió publicarlo!&rdquo;. Y yo, tan  exaltado como ella, me sentí parte de un milagro.</p>
<p>La célebre  editorial lanza en París la correspondencia, hasta  hoy inédita, que el gran poeta francés René Char (1907-1988) sostuvo entre 1952  y 1982 con nuestro Raúl Gustavo Aguirre (1927-1983), fundador y director de la  revista de vanguardia <em>Poesía Buenos Aires</em>,  que entre 1950 y 1960 lanzó una treintena de números y otros tantos títulos  publicados. </p>
<p>En octubre Marie-Claude vino a Buenos  Aires para rememorar aquel n.º 11-12 (1953) de <em>Poesía Buenos Aires</em>, obra de Aguirre, que constituye la primera versión  de Char al castellano. Ella tenía todas las cartas de Raúl. Me preguntó por las  de Char y me ocupé. Parecía imposible. Pero finalmente se produjo. Primero de a  una y luego en grupos, fui descubriendo copias digitales.</p>
<p>Así como iban apareciendo, las enviaba  a Marie-Claude. Ella estaba tan conmovida como yo. Gracias a su fidelidad y  devoción, Gallimard ya prepara la primera edición de esa correspondencia  invalorable, a la cual me pidieron que prologara, y que será presentada en el  Salón del Libro de París, del 21 al 24 de marzo, dedicado a la Argentina.</p>
<p>Quien sepa aprovechar la escrupulosa  bibliografía que culmina las <em>Obras  completas</em> de René Char, bellamente editadas por Gallimard para su  Bibliothèque de la Pléiade,  acaso encuentre llamativo advertir que su primera traducción al castellano es  del argentino Raúl Gustavo Aguirre, en el nº 11-12 (1953) de su revista <em>Poesía Buenos Aires</em>. Menos sorpresivo es  que, tras figurar apenas en una selección colectiva de Madrid, el primer libro  individual de Char en nuestro idioma también fuera traducido por Aguirre (1968).</p>
<p>Para mí, en cambio, los nombres de  Raúl Gustavo Aguirre y de <em>Poesía Buenos  Aires</em>, junto al de René Char, son algo muy personal, se unen directamente  con mi vida ya que, en plena adolescencia, me vi convertido en el miembro más  joven de la publicación.</p>
<p><em>Poesía Buenos Aires</em> mantuvo su criterio  central: &ldquo;La abierta rebelión contra los supuestos formales de la poesía,  contra las maneras tenidas por prestigiosas, contra las convenciones literarias&rdquo; pero sin incurrir en nuevos dogmas.  Al cerrar el n,º 25 (1957), Aguirre reitera: &ldquo;Ninguna  fórmula, ninguna receta, en conclusión, queda de todos estos años. Una vez más  hay que decirlo: <em>no sabemos qué es la  poesía </em>y, mucho menos, <em>cómo se</em> <em>hace un poema</em>&rdquo;.</p>
<p>Característica esencial de <em>Poesía Buenos Aires</em> fue su carencia de  astucia o complacencia, el desdén por la mal llamada &ldquo;vida literaria&rdquo;. De no  ser convicción íntegra, ¿cómo explicar que, a diferencia de tantos, Aguirre ni  pensó en obtener el más mínimo &ldquo;provecho&rdquo; exhibiendo su contacto con Char? ¿Cómo  no admirar que lo mantuvo celosamente oculto incluso para nosotros, sus íntimos?  En una carta de 1954, Raúl agradece a Char la lectura de sus poemas, que jamás  reveló.</p>
<p>Esa correspondencia honra sin duda a  ambos. Al gran poeta, porque lo confirma en su altura despojada, en su esencial  fraternidad. Al joven, porque lo desnuda en su fervor y discreción. Y un poco a  todos, si somos dignos de advertirlo. Y a la joven revista austral, libre y  rebelde como ellos. Y a la misma poesía, que los unió y nos une.</p>
<p>&nbsp;</p>
