<p>Con el foco puesto en la relación entre la estrella  de cine italiana Anna Magnani y el genial dramaturgo norteamericano Tennesse  Williams, <strong>Noches romanas</strong> rescata,  desde el fondo del lugar común y la banalidad, lo que puede entenderse como  conmovedor al momento de ver una obra de teatro; como efecto de lo que se  propone en el escenario y no como objetivo en sí mismo; sacudones que los  espectadores transitan con el placer de la experiencia estética. Ya en el  comienzo su autor, Franco D&rsquo;Alessandro, sienta los pilares conceptuales al  abrir su texto con las palabras con las que Tom, personaje-emisario de Williams  en <em>El Zoo de Cristal</em>, inaugura esa  obra de teatro inolvidable: &ldquo;Tengo trucos en el bolsillo y cosas bajo la manga,  pero soy todo lo contrario del prestidigitador común. Éste les brinda a ustedes  una linda ilusión con las apariencias de la verdad. Yo les doy la verdad con  las gratas apariencias de la ilusión.&rdquo; Unas palabras que resultan adecuadas al  devenir de <strong>Noches Romanas</strong>, donde la  reconstrucción de la intimidad de ambos personajes no son sino hilos  ficcionales que se entraman con el saber histórico, fragmentario y caprichoso,  de las noticias a través de las cuáles la privacidad de las figuras públicas  emerge a la superficie.</p>
<p>Ya en el primer encuentro, la tensión erótica está  presente para reencarnarse, a través de los años que en formas de escenas pasan  delante de los ojos del espectador, en distintos momentos de la vida de una  mujer estigmatizada como una voraz consumidora de hombres y un homosexual orgullosamente  declarado. Como imposibilidad, como un terreno que se propone ser explorado,  esa tensión explota en confesiones de parte y en consejos amistosos; en largas  noches que rondan el amor, las decepciones, los éxitos y los fracasos; en los  desvelos y la enfermedad de los familiares y de lo familiar; en recorridos por  fiestas interminables que solían terminar en las calles de Roma, alimentando a  los gatos callejeros que la Magnani adoptaba como propios.</p>
<p>A lo largo de los años, actriz y dramaturgo no sólo  forjaron una dupla artística que tuvo esplendores y reflujos, desencuentros  profundos y traiciones, sino que se constituyeron, uno para el otro, uno al  otro, en profundidades en las que se bucearon, descubrieron y redescubrieron.  Piezas (no tan) sueltas que en el relato de D&rsquo;Alessandro se ensamblan con  personajes que nunca subirán a escena: Luca, el hijo de Magnani postrado en una  silla de ruedas por una poliomielitis; Rose, la hermana de Williams, entregada  por su propia madre a una lobotomía que la dejó inútil de por vida; los amantes  cotidianos y anónimos de ambos; el tórrido, inolvidable y escandaloso amor de  Anna con Roberto Rosellini; el matrimonio de hecho entre Tennesse y Frank; los  periodistas, el público, los amigos…</p>
<p>Con todos estos elemento en una única escenografía  que representa tanto el departamento de Magnani sobre Roma, iluminado siempre  con una luz cálida, como el refugio neoyorquino del escritor, siempre iluminado  con colores fríos, Oscar Barney Finn construye una puesta contundente, con las  necesarias dosis de humor e ironía de las que sus protagonistas, en la vida  real, fueron capaces; cuerpos ficcionales a los cuales Virginia Inocentti y  Osmar Núnez reviven con la notable intensidad de quienes trazaron una amistad  tan profunda como el más intenso de los amores.</p>

<p><strong>Centro Cultural de la Cooperación</strong> <br />
  Av. Corrientes 1543 <br />
  CABA <br />
 5077-8000 - Interno 8313 <br />
</p>
