<p>Si durante mucho tiempo las legumbres, generalmente cocinadas en  pucheros y potajes, significaron pobreza y escasez, y fueron acusadas de  provocar pesadez y flatulencias, las cosas parecen hoy estar cambiando. El  ingente esfuerzo de algunos profesionales de la cocina y la nutrición por  recuperar este alimento tradicional y de origen remoto, componente destacado de  la tan venerada dieta mediterránea, sumado a la inclinación narcisista&nbsp;por  lo&nbsp;saludable&nbsp;que forma ya parte de nuestro tiempo, han instalado a  las <strong>legumbres</strong> (semillas de plantas  leguminosas) en uno de los podios de lo natural, lo conveniente, lo  recomendable. </p>
<p>Si a este buen crédito actual de las legumbres le sumamos la  erótica de lo exótico,&nbsp;su colorido y sencillez, elementos de un culto cada  día más mayoritario, podríamos encontrarnos ante uno de esos platos prefectos  capaz de convertirse en un&nbsp;boom. Y quizá algo así puede haber pasado con  el&nbsp;<em>hummus</em>: puré de garbanzos con  pasta de sésamo común en el norte de África y en el Medio Oriente que cada día  está más presente en las cartas de nuestros restaurantes más prometedores y  abiertos, esos que recuperando lo de siempre lo adornan y lo recomponen para  hacernos partícipes del privilegio de lo novedoso. </p>
<p>En origen, el <em>hummus</em> forma parte de los mezze o entremeses, conjunto de pequeños platos que  introducen la comida principal, pero puede también comerse como guarnición de  algunos platos de carne o pescado.</p>
<p><strong>La receta</strong></p>
<p>Ingredientes: 400 gramos de garbanzos cocidos, 2 dientes de ajo,  1 cucharada de pasta de sésamo, zumo de un limón, 1 cucharadita de comino,  aceite de oliva virgen, sal, pimentón y perejil.</p>
<ol>
  <li>Se colocan los garbanzos cocidos en el recipiente de la batidora  y se le añaden la pasta de sésamo, los ajos picados, el zumo de limón, el  comino, la sal y el aceite de oliva (inicialmente poco, para luego ir  corrigiendo la textura).</li>
  <li>Se bate hasta que se mezclen bien los ingredientes. Se va  añadiendo agua (o más aceite) si es necesario para obtener la textura deseada:  debe quedar consistente pero suelto.</li>
  <li>Se coloca sobre una bandeja o plato, se rocía con un chorro de  aceite de oliva, se espolvorea el pimentón, se adorna con una ramita de perejil  (o perejil picado) y se deja enfriar en la nevera.</li>
</ol>
<p>&nbsp;</p>
<p>La <strong>pasta de sésamo</strong> se  encuentra en el mercado con cierta facilidad con el nombre de Tahina, pero mi  recomendación es hacerla, ya que es muy sencillo y tendremos cierto control  sobre los ingredientes que usamos. Para prepararla se tuestan en una sartén  seca las semillas de sésamo sin dejar que se quemen, moviéndolas a menudo hasta  que empiecen a cambiar de color. En ese momento se pasan a un mortero, se añade  un hilo de aceite de oliva y un pelín de agua, y se machaca hasta que se forme  una pasta; la textura dependerá del trabajo de machacado, pero debería ser  similar a la de la mostaza con semillas.</p>
<p>Los garbanzos se cuecen, tras 12 o 14 horas en remojo, con agua  y sal como habitualmente. También podemos usar garbanzos cocidos de bote, y en  ese caso es recomendable lavarlos muy bien y escurrirlos por completo, para  eliminar en la medida de lo posible los sabores de la conserva. El comino puede  ser molido o en semillas, siendo en este último caso conveniente tostarlas en  seco y posteriormente machacarlas.</p>
