<p>Vivir en las inmediaciones del Barrio Chino,  inserto en el porteño barrio de Belgrano, no sólo ofrece la posibilidad de un  recorrido que puede tildarse con el lavado adjetivo de pintoresco ni de  disfrutar, en el mes de febrero, de la bulliciosa, colorida y zigzagueante  celebración del año nuevo chino. Es también un sitio en el que pueden comprarse  montones de bolurnos de la más diversa índole (bolas sonoras para meditación,  cremas mágicas para el resfrío, gatos de la suerte que mueven la manito,  rascadores de espaldas, mariposas de plástico, helados Melona, etc.), especias  de lo más orientales, fideos de arroz, arroces varios y cerdo, con una muy  fuerte presencia de pescados y frutos de mar, ofreciendo una gran variedad, con  algunas piezas difícil de encontrar, como el dorado, ostras frescas y pulpos  varios.</p>
<p>Entre los hallazgos en el supermercado Asia  Oriental está la bolsa de un kilogramo de langostinos crudos que se consigue a  mitad de precio de lo que las grandes cadenas de supermercados venden a pocas  cuadras de allí. Semejante abundancia hace que los horizontes gastronómicos  cercanos se pueblen de experimentaciones y nuevas ideas. O no tanto, sino  apenas una singular combinación de lo ya conocido. Los hemos hecho empanados,  los hemos transformado en gambas al ajillo. Y un día, de esos que no son como  los demás, el emprendimiento gastronómico se fue por el lado de cocinar los  langostinos con lo que hubiera en casa, a mano y sin necesidad de asomar la  nariz a la puerta de calle. De esa premisa salió este plato que lleva, para  cuatro porciones:</p>
<ul>
  <li>500   g de langostinos crudos</li>
  <li>2 cebollas de verdeo</li>
  <li>2 puerros </li>
  <li>1 cebolla pequeña</li>
  <li>3 dientes de ajo cortados en láminas</li>
  <li>3 zanahorias medianas ralladas gruesas</li>
  <li>Aceite de oliva</li>
  <li>Salsa de soja</li>
  <li>3 pocillos de arroz</li>
</ul>
<p>La cosa es sencilla. Por un lado va el arroz, con  las proporciones de agua y sal necesarias, para obtener la guarnición del  plato. Mientras el arroz se cuece, da el tiempo como para preparar el resto.  Importante: no está contada la limpieza fina de los langostinos a los fines de  sacarles los indeseables que pudieran tener. Volvemos: poner un wok con aceite  de oliva al fuego; agregar el ajo y sofreír. Antes de que el ajo se tueste,  incorporar las cebollas de verdeo, la cebolla blanca y los puerros. Cuando las  verduras empiecen a tomar consistencia de cocidas, agregar los langostinos y,  sobre éstos, la zanahoria rallada. Sazonar con salsa de soja y un chorrito de  aceite de oliva y mover sobre el fuego hasta que los langostinos hayan cambiado  de color y la zanahoria esté tierna. Durante la cocción revolver suavemente y  con movimientos envolventes. Servir los langostinos, sazonar con pimienta y  servir acompañado de arroz blanco. Si estás en este lado del Atlántico, te  recomendados el Blanc de Noir de bodegas Lagarde. ¡Bon appétit!</p>
