<p>1.<br />
  Hace  más o menos un año me pidieron un cuento para una antología sobre santos  populares. En aquel momento, me hubiera encantado escribir sobre Gilda. En  cambio, en la repartija me tocó hacer ficción con una santa jujeña de la cual  existían pocos datos en la web. Inventé todo y le di ritmo de <em>road movie</em>, con gente moribunda,  levitaciones, fiestas de carnaval y curanderos norteños. Recuerdo que, unos  meses antes, habíamos ido con mi novia a un ciclo de teatro <em>under</em> en el living de una casa de San  Telmo, barrio en el que vivo desde hace pocos meses. Vimos pequeños <em>sketchs</em>, un grupo de chacareras que  parodiaban el género con intensidad y buenas ideas, una pareja de colombianos  calentones y delirantes; comimos empanadas, tomamos vino en vasitos de plástico  y después fumamos en un pequeño patio, arrinconados por edificios altísimos. La  última escena del ciclo trataba sobre dos fanáticas de Gilda que, post mórtem,  aseguraban recibir mensajes desde el más allá. Discutían quién era la elegida  mientras escuchaban &ldquo;No me arrepiento de este amor&rdquo; en un casete que luego  rebobinaban con una birome. Hacia el final retumbaba la voz de Gilda, que les  aseguraba a ambas que eran sus sucesoras. Delirio místico, pulso bizarro, vinchas  y exceso de rímel barato. La escena tenía jugo. Ahora mismo, mientras escribo,  veo que alguien postea en Facebook la foto de un mural de Gilda, tomada en un  paredón de La Paternal: &ldquo;Desde ahora en adelante vivirás dentro de mí&rdquo;. Parece  una sirenita peronista atravesada por rayos blanquicelestes. Si escribiera un  cuento sobre Gilda, sería un cuento de resurrección gore, una historia de  terror sobre una mujer que vampiriza a sus fanáticos.</p>
<p>2.<br />
  El <em>raid</em> santo o mitológico, más allá de  ejes temáticos, la sistematización y los arquetipos de héroe y antihéroe que  traza la narratología permite el relato, a mí entender, a partir de tres  variables: el historicismo, la parodia –coqueteando en mayor o menor medida con  lo bizarro– y, finalmente, el trabajo dentro de la literatura de género:  ciencia ficción, terror, fantástico, etc. Pero esto es solo una estela. La  iluminación, que forma parte de la mistificación popular, es otra cosa. En  realidad, el problema es la iluminación por fuera de la mistificación. Lo  popular, de alguna manera, lateraliza el problema de la narración y la vuelve,  si no accesible, al menos posible. Mario Levrero ganó la Beca Guggenheim y  escribió <em>La novela luminosa</em>, es  decir, un diario sobre la imposibilidad de escribir la novela luminosa o, lo que  es lo mismo, la imposibilidad de narrar hechos luminosos y cotidianos.</p>
<p>3.<br />
  Levrero  escribe: &ldquo;Yo tenía razón: la tarea era y es imposible. Hay cosas que no se  puede narrar. Todo este libro es el testimonio de un gran fracaso. El sistema  de crear un entorno para cada hecho luminoso que quería narrar me llevó por  caminos más bien oscuros y aun tenebrosos. Viví en el proceso innumerables  catarsis, recuperé cantidad de fragmentos míos que se me habían enterrado en el  inconsciente, pude llorar algo de lo que habría debido llorar mucho tiempo  antes, y fue sin duda para mí una experiencia notable. Leer eso sigue siendo  para mí removedor y aun terapéutico. Pero los hechos luminosos, al ser  narrados, dejan de ser luminosos, decepcionan, suenan triviales. No son accesibles  a la literatura, o por lo menos a mi literatura&rdquo;.</p>
<p>4.<br />
  Y  antes, en el mismo prefacio: &ldquo;Lo creía imposible y lo sigo creyendo imposible.  Que fuera imposible no era un motivo suficiente para no hacerlo, y eso ya lo  sabía, pero me daba pereza intentar lo imposible&rdquo;. Cada estética, naturalmente,  brinda una solución a los problemas de la representación y de la imposibilidad  de lo narrable. En otras palabras: establece qué se puede narrar y de qué  manera, establece límites. La barrera de lo decible es un problema todavía más  hondo, pero el posmodernismo, al refuncionalizar mixturas, al devorar su propio  pasado y remixarlo, presenta en Levrero un problema, en algún punto, novedoso.  La imposibilidad supone también, más allá del hecho en sí –que prueba no ser narrable,  al menos para Levrero– un conjunto de elementos y estados de ánimo que tornan  posible la escritura, la cual, a su vez, pone en tensión la narratividad o no  de un suceso.</p>
<p><span class="image_cen1"><img src="images/301.jpg"></span>5.<br />
  Recuerdo  una nota de Juan Martini publicada en el blog de Eterna Cadencia. Contaba que  debía escribir sobre cierto tema y entregar el material equis día. Martini  estaba de vacaciones, caminaba por la playa y decía que, porque debía escribir,  &ldquo;leía&rdquo; el paisaje y el concepto de una manera particular. La necesidad de  escribir modifica las condiciones de legibilidad desde la propia concepción de  literatura de cada autor, que torna permeable o no determinados temas. Ignacio  Molina contaba algo parecido: en momentos de escritura, la cotidianidad cobraba  una potencia superior. No lo decía de esta manera, pero era más o menos la  idea. A Molina le gustaban esos momentos, como a todos los escritores, tal vez.  Molina, por su ritmo de publicación, parece que escribe mucho.</p>
<p>6.<br />
  Desde  hace años quiero escribir un cuento, pero no logro encontrar la manera de  narrarlo, a pesar de haberlo iniciado unas diez veces. Un hombre de unos 30  años viaja por una ruta provincial hacia la casa quinta de sus suegros, donde  se festeja un cumpleaños. En el camino, mientras conduce, llega a una  conclusión fascinante sobre la relación con su mujer. En ese momento, un ciervo  cruza la ruta y lo atropella. El hombre esconde el suceso, que corta su cadena  de pensamientos, pero el ciervo y el instante de lucidez le queda dando vueltas  durante semanas. Un mes después, ocurre algo parecido. Mientras maneja su auto,  vuelve a comprender un punto culminante de su vida, aparece un ciervo y lo  atropella. Hacia el final del relato, el hombre transita las rutas de Buenos  Aires, buscando un ciervo o cualquier otro animal, para volver a iluminarse. </p>
<p>7.<br />
  Cheever  se emborracha mal; Kerouac se inflaba de anfetaminas y alcohol; King tomaba  cerveza y aspiraba cocaína. Simon Reynolds, el gran crítico de rock, piensa que  la nueva fase <em>rocker</em>, a menos que el  rock, como género, continúe canibalizándose a sí mismo, podría llegar de la  mano de una nueva droga. Es decir: un estímulo artificial, por ahora  inexistente, que posibilite nuevos abordajes o estéticas.</p>
<p>8.<br />
  <em>La Pelusa</em> es una <em>nouvelle</em> fascinante y arrolladora de un joven escritor uruguayo  llamado Martín Arocena, editada por Fiordo a finales del 2013. En este texto,  la pelusa que cae de ciertos árboles que pululan en Montevideo funciona como  exteriorización de la crisis que estalla en el protagonista. Una crisis que,  menos que espacial, es temporal y va del pasado, que se acumula como una bola  de nieve hasta arrollar el presente. Esta deriva oceánica es generada por la  pelusa, que emite una extraña radiación que posibilita algo así como una  epifanía crítica. Se trata de una pelusa revolucionaria y desmitificadora. La  novela está narrada en una segunda persona sin concesiones, extremadamente  rítmica y lúcida, muy efectiva en la difícil misión de generar una marea de  lenguaje arrasadora. La iluminación se vuelve, entonces, una música que nos pone  en trance.</p>
