<p>El equinoccio de marzo nos ha dejado un florecimiento de novedades musicales que apenas si podemos abarcar. Como si de un telón se tratase, el comienzo de la primavera y el otoño (según en qué hemisferio tengamos los pies) abrió sus lienzos y nos dejó escuchar algunos de los lanzamientos más esperados del año. No están todos los que son, pero de los que están nos ocupamos con cariño y dedicación. 
  
</p>
<p><strong>John Frusciante: <em>Enclosure</em> (Record Collection, 2014)</strong><br />
  John Frusciante, por mucho o poco que le pese, será siempre el exguitarrista de Red Hot Chili Peppers. Y con las comparaciones que de ello deriven deberá convivir, a pesar de que su producción solista haya alcanzado ya un bagaje que ya quisiera más de uno. En Enclosure, su última producción, Frusciante multiplica su apuesta por la exploración hasta los límites de la disgregación sonora: secuencias, sintetizadores, samplers y, por supuesto, guitarras se superponen en cada tema formando capas musicales cuya incorporación requiere de más de una escucha. La exigencia al oyente es marca de la casa, y por eso los invitamos a no amilanarse ante este interesante collage de rock y electrónica, cuyo tema de promoción ("Scratch") condensa a la perfección las intenciones del álbum.
</p>
<iframe width="770" height="580" src="//www.youtube.com/embed/eMuRgPjGAcs?rel=0" frameborder="0" allowfullscreen></iframe>
<p>&nbsp;</p>
<p><strong>The  Black Keys:<em> Turn Blue</em> (Nonesuch,  2014)</strong><br />
Cuando en 2011 se publicó <em><a href="http://estonoesunarevista.com.ar/nro017/sonoridades.html#sonoridades03">El  Camino</a></em>, el dúo de Ohio supo dejar a la parroquia moviendo los pies y la  cabeza al ritmo de sus temas contundentes. Aquello fue, o pareció ser, la  consagración de Auerbach y Carney como nuevas estrellas del firmamento rock. En  ese lapso de tiempo hasta hoy, a menudo fuimos teniendo noticias de la  hiperactividad productora de Auerbach, mientras que del baterista solo nos  llegaba su silencio longilíneo. La espera hasta la nueva estación discográfica se  hizo larga. Y ahora, tras escuchar el nuevo <em>Turn  Blue</em>, muchos lamentamos haber perdido el tiempo y los pabilos poniendo  velas e intentando otros hechizos. La decepción es de tal calibre que vamos a  ahorrarnos los epítetos y cerrar con una paráfrasis: &ldquo;Billetera mata roquero&rdquo;.</p>
<iframe width="770" height="580" src="//www.youtube.com/embed/trk7P-9QDyc?rel=0" frameborder="0" allowfullscreen></iframe>
<p>&nbsp;</p>
<p><strong>Damon  Albarn: <em>Everyday Robots</em> (Parlophone,  Warner Bros, XL, 2014)</strong><br />
Damon Albarn es  aquel chico un poco difuminado que lideró Blur, la banda de britpop que surcó  con tanto éxito el cielo de los noventa. Después fundó Gorillaz, ese grupo  virtual que no existía sino en la animación de sus videoclips. La siguiente  noticia que tuvimos de él fue en 2007, cuando vio la luz el proyecto The Good,  The Bad &amp; The Queen, en el que Albarn se rodeó de chavales como Paul  Simonon o el productor Danger Mouse, para parir un disco inquietante y  cautivador. Siete años después, Albarn da el salto al proyecto solista con <em>Everyday Robots</em>, un conjunto de doce  canciones de cámara, obviamente melancólicas, necesariamente electroacústicas,  que dejan en el oyente un poso de esperanza triste. O de activa resignación,  como se quiera.</p>
<iframe width="770" height="580" src="//www.youtube.com/embed/rjbiUj-FD-o?rel=0" frameborder="0" allowfullscreen></iframe>
<p>&nbsp;</p>
<p><strong>Neneh  Cherry: <em>The Blank Project</em> (Smalltown  Supersound, 2014)</strong><br />
Fue decir que no  nos gustaban los discos de Neneh Cherry que la sueca comenzó a publicar discos  que nos gustaron. Este romance de madurez comenzó con <em><a href="http://estonoesunarevista.com.ar/nro022/sonoridades.html#sonoridades05">The  Cherry Thing</a></em>, una incursión a caballo entre el free-jazz y el funk que  nos deshizo de un plumazo todos los prejuicios. Ahora, la hijastra del gran Don  Cherry se descuelga con <em>The Blank Project</em>,  con el que demuestra que el paso de los años no es sinónimo de pérdida de  frescura o inquietud. Liderada la producción por Four Tet, hay una intención  marcada (y conseguida) de regresar a las líneas del trip-hop, que se cruza con  mantras a capella (&ldquo;Across the water&rdquo;), propuestas más pisteras (&ldquo;Dossier&rdquo;) o  ritmos taquicárdicos (&ldquo;Cynical&rdquo;). Lo que no sabemos es de dónde colgar la  bandera &ldquo;Perdón Neneh&rdquo;.</p>
<iframe width="770" height="580" src="//www.youtube.com/embed/ux34bQ2XAIo?rel=0" frameborder="0" allowfullscreen></iframe>
<p>&nbsp;</p>
<p><strong>Vetusta  Morla: <em>La deriva</em> (Pequeño Salto  Mortal, 2014)</strong><br />
España no es  solamente ese país de fracasos mundialistas, sucesiones regias y estafas  inmobiliarias. También es el vientre donde se crían bandas como la madrileña  Vetusta Morla. Tras el bombazo de su disco debut (<em>Un día en el mundo</em>, 2008) y el paso más sutil de su sucesor (<em>Mapas</em>, 2011), <em>La deriva </em>acierta en combinar la lírica que los hizo  peninsularmente célebres con una bajada a los infiernos de la calle. El  resultado es un álbum donde sus registros más intimistas conviven con una forma  de ver la realidad a la que la propia realidad parece haberlos empujado. Un  ejemplo de esto último es el adictivo &ldquo;Golpe maestro&rdquo;, cuya advertencia final invita  a los poderosos a mejorar su estado físico.</p>
<iframe width="770" height="580" src="//www.youtube.com/embed/l-RlhNUabZY?rel=0" frameborder="0" allowfullscreen></iframe>
<p>&nbsp;</p>
