<p>Pintor, curador y maestro de dibujo y  pintura, Alfredo Londaibere (Buenos Aires, 1955) inició su recorrido artístico en  la década del ochenta, exponiendo sus primeros trabajos en bares y discotecas.  Formó parte del grupo de artistas vinculados a la galería de artes visuales del  Centro Cultural Ricardo Rojas en sus inicios, en los primeros años noventa,  espacio del cual fue curador entre 1997 y 2002.</p>
<p>A lo largo de su extensa trayectoria realizó  numerosas exposiciones –individuales y colectivas– en diversos lugares del país  y en el exterior. Si bien se autodefine como pintor, sus incursiones creativas  atraviesan además el campo de la cerámica, el dibujo, la escultura y también la  danza y el movimiento corporal, asistiendo a diversos seminarios y talleres en  esos campos desde los años setenta. </p>
<p>&ldquo;Yo opté por delimitar mi territorio  como el de la pintura&rdquo; afirma Londaibere,  y su recorrido se consolida en un corpus de obra muy atrayente. El acto  pictórico como algo misterioso y conmovedor trasunta la concepción del artista,  que entiende la pintura como &ldquo;algo esotérico&rdquo; que no se puede explicar: &ldquo;Lo ves  o no lo ves&rdquo;. La pintura &ldquo;es mostración, muestra&rdquo;; el acto pictórico constituye  un fenómeno exógeno al plano intelectual. </p>
<p>Se pone en juego el carisma creador. La  figura del artista, inmersa en mundos distanciados de lo corriente, da cuerpo a  sus obras donde los elementos plásticos se conjugan de manera sensible. &ldquo;¿Por qué  atraemos, por qué la gente quiere ver cuadros? Es por eso, porque una  explicación no lo suplanta…&rdquo;, reflexiona el pintor.</p>
<p>Formas orgánicas y formas geométricas  plenas se articulan armoniosamente en el espacio plástico, donde el trabajo  minucioso y cuidado del artista compone imágenes de vibrante color. En su  paleta están presentes el azul, el verde, el rojo, el naranja y el amarillo, en  múltiples matices.</p>
<p>En la muestra reciente organizada en el  Salón Matiz del Alvear Art Hotel se exhibió  un conjunto de bellas pinturas con formas florales de gran riqueza cromática. La  composición del objeto toma su faz referencial y su deconstrucción geométrica,  propiciando la grata convivencia de estilos diversos.</p>
<p>La pincelada trasluce la gestualidad  del artista en el acto pictórico. La fuerte presencia matérica en sus telas, la  superposición de capas de color y los contrastes lumínicos transmiten la  presencia de lo táctil a partir de lo visual. Como expresa Laura Batkis en el  texto del material desplegable que acompaña la muestra, &ldquo;la obra de Alfredo  Londaibere hoy es necesaria&rdquo;. </p>
<p>Las varias décadas de trabajo que viene  desarrollando este artista argentino contemporáneo han cristalizado un modo  propio de hacer arte. &ldquo;La muestra de Londaibere se parece a todo lo que viene  haciendo desde siempre con un estilo que es el suyo&rdquo;, resume Batkis. </p>
<p>Para quien no haya podido asomarse al  mundo pictórico de Londaibere acercándose a la muestra mencionada, pueden visitar  la página del artista: www.londaibere.com</p>
<?
	include('londaibere/londaibere.html');
?>
<div id="ftn1"><br />
	Las  citas textuales de Alfredo Londaibere en este artículo corresponden a la  entrevista mantenida en su taller con la autora (21 de abril de 2014). 
</div>
