<p>Todo ocurrió rápidamente. Faltaba un minuto para terminar el partido. La mayoría estaba preparada ya para el inevitable alargue, lo cual abría la oscura posibilidad de que se nos escapara un partido que hasta el gol de Naninga había sido nuestro. Pero ni el ánimo ni las esperanzas (la fe rotunda a la que empuja el fútbol) habían decaído. Lo que se dice, el partido estaba terminado: vagaban por el césped esos segundos en los que los árbitros pecan por exceso de celo y prolongan reglamentariamente lo que a nadie le interesa reglamentar. Entonces apareció Rensenbrick, el holandés errante. Interpretando a la perfec-ción nuestros signos de sosiego, pidió la pelota. Volcado sobre la derecha, reci-bió, se volvió y acomodó el balón con un solo movimiento de cintura. Nadie lo vio. Cuando volvimos a saber de él, se encontraba dentro del área con el esférico dominado. Entonces levantó la cabeza y disparó lo más fuerte que pudo. Durante las décimas de segundo que transcurrieron hasta el rebote contra el primer palo, sé que muchos argentinos pensaron con seriedad en el suicidio. Pero mi padre y yo no pudimos participar del instante de pánico colectivo, porque precisamente en ese momento apareció por la puerta de casa, casi dos años después.
</p>
<p>Tenía el pelo más largo y tal vez hubiera adelgazado, y durante unos instantes (los mismos en los que la pelota corría hacia el poste) no lo reconocí, hasta que logré casar la imagen de mi padre con la de quien decía que era mi padre. Entonces supe que venía “Directo desde Bariloche” (alguna tarjeta postal ante-rior hablaba de Córdoba), dispuesto a ver el partido con nosotros, pero una avería del coche lo había retrasado fatalmente. “Venimos con la radio pegada a la oreja”, fue lo primero que dijo, sin especificar quiénes eran los que se amontonaban junto al transistor. Sin embargo, remarcó, había desistido de parar en la ruta a ver el partido para llegar lo antes posible. Recuerdo que entonces no entendí la necesidad de la prisa, después de dos años. Pensé, “Casi perdemos por tu culpa”.
</p>

<p>Al igual que en la despedida, mi padre se presentó con un regalo. Aún con-servo el coqueto estuche, y que recién abrí cuando Passarella levantaba la copa: el juego de monedas conmemorativas del XI campeonato mundial de fút-bol 1978. Un tesoro ayer preciado que hoy bien puede ser visto como símbolo de la lujuria patria entonces desatada.
</p>

<p>No voy a decir que mi hermano Hugo no se alegrara cuando mi padre regresó de su autoexilio (hoy breve, ayer eterno), pero, con cinco o seis años es poco lo que se puede exigir y mucho lo que debe explicarse. Estoy seguro de que mi madre mantuvo con mi hermano una tarde como la de mi padre y yo en la confitería acrílica, pero con los niños parece ser muy importante el factor tiempo, ya que la reparación, si llega, se posterga hasta la adultez. Quiero de-cir, si hubo aclaraciones fueron a destiempo. Ni siquiera contó Hugo con la posibilidad de ejercitar esa costumbre tan difundida entre los hijos de padres di-vorciados: odiar al nuevo cónyuge. Para contrarrestar la balanza, asumí con gusto la secreta planificación de atentados que dañaran a la nueva mujer de mi
padre. Llegué a tal punto de refinamiento en la imaginación de torturas que, a falta de consumación, debí extender la imaginación de castigos a la familia de esa mujer (esa mujer sin nombre), a su hijo de un anterior matrimonio (del que nunca fui amigo), incluso a sus padres. Desesperado, hasta llegué a pensar de qué manera podía envenenar a la señora que limpiaba su nueva casa. Tampoco compartí con Hugo la excitación que me producía imaginar estos asesinatos en potencia, ya que nuestra distancia comenzó a transformarse en insalvable, amoldados ambos en compartimentos estancos sin comunicación posible. Lo único que nos unía era el mar en el que nuestro barco zozobraba. No sólo nos desunían un reloj y las monedas del mundial. Para ese entonces mi hermano llamaba Héctor a su padre.
</p>

<p>A pesar de todo, impulsado por los primeros bocinazos y la promesa de un paseo en coche, Hugo se unió a nosotros en los festejos del campeonato. De la noche del 25 de junio de 1978 recuerdo demasiados rostros desconocidos y el profundo convencimiento de que mis motivos de celebración eran bien distintos de los del resto de mortales. Aún no entiendo qué festejaba Hugo, más allá de la algarabía en sí. Tampoco por qué nuestra madre soltó algunas lágrimas cuando salimos de casa. Me veo sentado sobre el techo de un coche, cuyo conductor tenía que ver con la familia de esa mujer, golpeando extasiado la chapa como un tambor. Sé que ninguno de nosotros llevaba banderas argen-tinas.
</p>

<p>En algún momento de la caravana (estábamos detenidos entre millones de co-ches), crucé mi mirada con la de una mujer, tal vez algo mayor para estar sentada sobre el techo de un coche, próximo al nuestro. La anciana, engalanada con la celeste y blanca, no cantaba ni reía, simplemente me observaba, con la mirada lánguida, inundada de tristeza, como si estuviera reconociendo a alguien que ella daba por perdido. Entonces levantó su mano en dirección a mí y extendió un pulgar, “Éxitos”. Contesté del mismo modo, algo aturdido, pero la mujer continuaba sin sonreír.
</p>

<p>Me sentí como nunca cercano a esa extraña que mixturaba la felicidad inmediata con la tristeza permanente. Recién entonces descubrí que para mí tampoco se trataba de un festejo integral. Me remordía la conciencia lo que hu-biera podido pasar si Rensenbrick hubiera acertado lo que en el último minuto el santo poste devolvió.
</p>
