<p><em>Los compañeros de la revista </em><strong>DIXI (He dicho)</strong><em> ocupan en este número la sección destinada a la presentación de publicaciones de las que nos gustaría ser amigos</em>.</p>
<p>Preguntar por los  porqués a menudo conlleva el peligro del aplazo –primero indefinido, después  definitivo– de iniciativas surgidas como reacciones violentas (e intuitivas) al <em>statu quo</em>. Si tenemos que sincerarnos, <strong>DIXI (He dicho)</strong> no fue el producto  de un plan concebido con nueve meses de anticipación. La publicación no procede  de un estudio de mercado, ni de un análisis sosegado y sensato de la  &ldquo;factibilidad del proyecto&rdquo;. Asumir lo contrario sería negar una historia que  nos enorgullece: DIXI (He dicho) nació en el peor momento de la última crisis  general del país con la única intención de ofrecer resistencia a un contexto de  pesimismo y desesperación.</p>
<p>Las fundadoras teníamos  20 años y, pese a que nos esforzábamos en parecer seguras, estábamos tan  desorientadas como nuestro entorno. ¿En qué momento se había ido todo al  diablo? ¿Debíamos buscar un futuro en el extranjero? ¿Cómo salir de la  parálisis? ¿Qué mensaje había oculto en la devaluación, el &ldquo;corralito&rdquo;  financiero, la sucesión de presidentes, los saqueos, los &ldquo;cacerolazos&rdquo; y las  muertes por desnutrición? Pero el interrogante que resume las inquietudes de  aquella época espantosa estaba vinculado a la sensación de fracaso del  materialismo que promovió la hoy denostada década de 1990. ¿Qué nos quedaba  cuando las seguridades económicas se habían esfumado por completo?</p>
<p>Vimos una respuesta en  la palabra y, en la cultura, un ámbito de contención espiritual al alcance de  nuestras manos. El Tucumán de diciembre de 2001 pedía a gritos un espacio de  expresión que se ocupase de contar las historias que pasaban inadvertidas en el  tumulto de la crisis.</p>
<p>DIXI (He dicho) fue un  acto de sensibilidad. Queríamos escribir y queríamos leernos. Queríamos  exponernos al diálogo. Queríamos una publicación abierta, plural, secular,  capaz de dar cobijo a las plumas nuevas y emergentes, y de divulgar los  fenómenos culturales con una perspectiva local. Queríamos que la revista  tuviese una distribución gratuita para que el dinero, ese bien escaso y esquivo  –cuya posesión coloca a la gente en los territorios enfrentados de marginación  e inclusión–, no fuese obstáculo para la lectura.</p>
<p>Nos miraron con la  condescendencia que se dispensa al adolescente rebelde que quiere cambiar el  mundo. No nos importó la incredulidad ajena. Nos aferramos a los que nos  tendieron la mano. En marzo de 2002, después de pasar por la inverosímil tarea  de vender los avisos publicitarios de una revista todavía inexistente, llegó la  primera DIXI (He dicho) con un concepto editorial empeñado en huir del  sectarismo y la endogamia que suelen condenar a las revistas culturales.</p>
<p>Cada edición fue  concebida como si fuese la última. Nunca nos propusimos perdurar 12 años ni  publicar 35 números (el 36 está en camino). Hemos atravesado por etapas de  zozobra sin caer al abismo. En algún momento, DIXI (He dicho) adquirió  autonomía y madurez.</p>
<p>Crecimos con cada  tropiezo, ganamos la preciada experiencia sosteniendo el pabellón de la  independencia –jamás recibimos financiación pública– y, número a número,  procuramos renovar el diseño (en blanco y negro, los colores de la crisis),  ampliar la circulación, y aprovechar los beneficios de las nuevas tecnologías  de la información y la comunicación. Jamás nos detuvimos en la búsqueda de un  contenido de calidad. Jamás cerramos la puerta abierta a nuevos colaboradores  de Tucumán, el país y el mundo; para muchos de ellos, DIXI (He dicho) ha  supuesto la posibilidad de publicar un texto por primera vez.</p>
<p>Nuestra revista es un  gesto de esperanza. Nada nos gobierna salvo el amor por la lengua de Jorge Luis  Borges y de Miguel de Cervantes. Parida en medio de la precariedad, DIXI (He  dicho) ha demostrado vocación por la continuidad. En esa insistencia tenaz, se  ha ganado un lugar digno en la divulgación de la cultura a la que pertenece. <br>
  Los autores (¡más de 100!) y lectores (más de 2.000 en la edición impresa y  hasta 5.000 en la digital) se han adueñado de ella. Y enhorabuena porque toda  publicación que aspire a influir en su comunidad de referencia vive, vibra,  suda y progresa en la dinámica de escritura y lectura que justifica su  existencia.</p>
<?
	include('dixi/dixi.html');
?>

