<p>Todos  los amigos y conocidos que tuvieron la suerte de recorrer el territorio  italiano coincidieron en algo: la gastronomía roza la categoría de inolvidable.  Habiendo hecho un paseo más rápido que el tiempo del deseo por las tierras de la  gran bota europea, nos sumamos, con gusto y agrado, a esas opiniones. Como es  muy difícil decidirse por algún sabor en particular, hicimos un breve racconto  de algunos de los lugares que nos dejaron un recuerdo imborrable en el paladar.</p>
<p>&nbsp;</p>
<p><span class="image_cen1"><img src="images/2801.jpg"></span><strong>Ristorante al 34</strong><br />
  Si  uno imagina un restaurante italiano enclavado en una de las zonas más bonitas  de Roma, tranquilamente puede encontrar en este sitio el reflejo de su  imaginación. Ecléctico en su decoración, atendido por su dueña, quien recorre  las mesas asegurándose de que los comensales reciban la atención que merecen,  ofrece una carta de comida típica italiana en la cual es muy difícil elegir.  Lasagnetta con pesca del día, espárragos y gruyere; lasagna a la bolognesa;  rissotos varios; paccheri con tinta de calamares o bombolotti con tomate y  panceta son un impecable recorte de opciones posibles en una carta amplísima,  rica y tentadora. Regadas con el recomendado Montepulciano de la casa, fueron  el portón de entrada a uno de los mejores tiramisú que puedan encontrarse. <br />
  Via  Mario de Fiori 34, Roma</p>
<p>&nbsp;</p>
<p><span class="image_cen1"><img src="images/2802.jpg"></span><strong>Biif Burger</strong><br />
  Cierto  es que la pasta y la pizza son los puntales de la comida italiana. Y que pocas  chances le daría uno a intentar cruzar las fronteras del molde en una ciudad  como Milán. Sin embargo, dejarse seducir por las hamburguesas de Biif es darle  al buen gusto la posibilidad de disfrutar de una de las mejores que hemos  probado en la vida. Es probable que haya que remontarse muy atrás en la memoria  para encontrar otros medallones de carne picada que le produzcan a quien los  prueba la satisfacción que Raffaele y los suyos pueden dar. Son recomendadísimas  las hamburguesas de chianina, esa raza vacuna que, desde los tiempos del Imperio  romano, hace las delicias de las inmediaciones de la Toscana y Umbría. <br />
  Via  San Vito 7, Milán</p>
<p>&nbsp;</p>
<p><span class="image_cen1"><img src="images/2803.jpg"></span><strong>Le Fonticine</strong><br />
  A  muy pocas cuadras de la estación de trenes Santa María de Novella, este  restaurante ofrece una atención de altísima calidez y calidad que va de la mano  con un menú en el que las exquisiteces asoman por doquier. Ideal para darse el  gusto de probar alguna variante poco habitual de pastas o ir a por las  recomendaciones del chef, invita a pensar en ir una y otra vez para cerciorarse  de lo que sin dudas será una gran experiencia gastronómica; sean linguine al  bacalao en salsa cremosa, tortelloni de ricota y espinacas con crema de queso y  trufas, o los superiores pici con pato. Especial atención al chianti Sinopie y  a los dulces de la casa. <br />
  Via  Nazionale 79, Florencia</p>
<p>&nbsp;</p>
<p><span class="image_cen1"><img src="images/2804.jpg"></span><strong>Mezzaluna</strong><br />
  Orvieto  es un lugar mágico. Y para una noche de cierre de viaje, nada mejor que una  auténtica trattoria en la que habitualmente se sientan a la mesa los locales,  quienes conviven armónicamente con algunos de los extranjeros que pasan por  allí. Cuestión de persistencia o suerte, no es fácil conseguir una mesa en el  local de Averino Baffo, quien desde hace cuarenta años sirve unos platos tan  abundantes como sabrosos. La carta indica, con un resaltado flúo hecho a mano,  la cúspide del sabor: spaghetti alla carbonara, la mejor del mundo según las  tan ciertas como poco modestas palabras del dueño. De una contundencia y una cantidad  extraordinarias que los hace parecer interminables, moteados de tremendos  trozos de panceta, proponen un difícil desafío: llegar al fondo de plato es  cosa seria. Por eso se hace necesario, de postre, entrarle a un siempre  digestivo helado de limón, servido en uno de esos medio limones tamaño gigante  que son habituales en Italia; para terminar con un ristreto que le da al cuerpo  el envión necesario para volver a esas calles de ensueño. <br />
  Via  Ripa Serancia 3, Orvieto</p>
<p>&nbsp;</p>
