<p>La coca recorre  buena parte del mediterráneo español. Las hay dulces, con sus rellenos de  crema, frutas confitadas, dátiles, piñones o cabello de ángel; y las hay  saladas, de rellenos muy variados en los que no suele faltar la cebolla. Hay  cocas abiertas, en las que los ingredientes se colocan sobre la masa extendida,  como en la pizza o la tosta, y cocas tapadas, donde dos capas de masa, como en  la empanada o la empanadilla, esconden el relleno y la hacen más adecuada para  el viaje o la travesía.</p>
<p>Coca, en su acepción  gastronómica, significa torta, es decir: masa de harina con otros ingredientes.  Visto así, podemos entenderla como una de las posibles variaciones del pan. Y  quien haya hecho una incursión culinaria en el mundo del pan quizá sepa que el  manejo de la levadura y el amasado, el reposado, el horneado y sus  circunstancias, y el resto del proceso encierran siempre un grado de  incertidumbre que a veces se transforma en fracaso. Por eso, el descubrimiento hace  apenas unas semanas de esta receta con aspecto de fórmula magistral –que además  proviene de la sabiduría que se esconde dentro de la experiencia de algunos de  nuestros mayores– me parece un verdadero hallazgo.</p>
<p><strong>La receta</strong></p>
<p>Ingredientes:</p>
<p><u>Para el relleno</u>: 1 cebolla grande, no demasiado seca; 1 lata (400 g) de tomate natural  troceado; 2 latas (unos 200 g)  de atún en aceite de oliva.</p>
<p><u>Para la masa</u>: ½ kg de harina de trigo; 1 vaso (200 mL) de aceite de girasol y otro  de gaseosa; sal.</p>
<p>Procedimiento:</p>
<p>Picamos la cebolla a gusto y la rehogamos en aceite de oliva o de  girasol a fuego medio unos 5 minutos.</p>
<p>Añadimos la lata de tomate troceado y continuamos rehogando el tiempo  necesario para que se fría, unos 20 o 25 minutos, subiendo y bajando el fuego y  removiendo y machacando un poco el tomate. Cuando está, lo retiramos y dejamos  que se enfríe.</p>
<p>Para hacer la masa, ponemos en un bol la harina y añadimos la sal, el  aceite y la gaseosa, removiendo con los dedos hasta que formemos la masa, que  se cuaja enseguida. La sacamos entonces a la encimera y la amasamos unos 5 o 10  minutos. La partimos en dos trozos iguales, formamos dos bolas y las dejamos  reposar 5 minutos.</p>
<p>Aplastamos y extendemos con el rodillo una de las bolas hasta formar la  base de la coca, generalmente en forma rectangular, pero siempre en función de  la bandeja o el recipiente para el horno.</p>
<p>Untamos bien de aceite de girasol la bandeja del horno (o el  recipiente) y extendemos la masa. Ponemos sobre ella el sofrito de cebolla y  tomate, cubriendo toda la superficie y esparcimos con las manos el atún (ya  escurrido de aceite) sobre el sofrito.</p>
<p>Con la ayuda del rodillo extendemos la otra bola de masa y tapamos la  coca, cerrando el borde.</p>
<p>La introducimos en el horno (caliente a unos 160º) y vigilamos su horneado  durante unos 40 minutos: los primeros 20 minutos a menos temperatura (160º), subiendo  en los minutos finales hasta 180º-200º.</p>
