<p>El gran dinero y la gran prensa  neoliberal intentaron apoderarse de <em>todo</em> Octavio Paz, el célebre escritor mexicano, distorsionando sus tempranas  críticas al terror estalinista y su redescubrimiento del verdadero liberalismo  para adjudicárselo, domesticado como a tantos otros conversos hacia la derecha.</p>
<p>Porque Paz, nacido en plena Revolución  mexicana (1914), era hijo de Octavio Paz Solórzano, fundador del Partido  Nacional Agrarista, asesor legal de Emiliano Zapata y su representante en Estados  Unidos, involucrado en la reforma agraria y en las transformaciones educativas  de José Vasconcelos. Él mismo, apenas recibido, en 1937 parte a Yucatán con las  misiones pedagógicas de Lázaro Cárdenas. Y también ese año integra la  delegación mexicana al célebre Congreso de Escritores Antifascistas convocado  en Valencia por los republicanos españoles, mientras arreciaba la guerra civil  desatada por el franquismo.</p>
<p>Comenzaba su tarea de escritor, cuyos  primeros títulos lo vuelven un hombre público. Polemista agudo, convencido  humanista, su figura crece como su influjo, entre admiraciones y rechazos. Pero  algo hay que reconocerle: en 1968, tras 24 años de diplomacia, renuncia como  rechazo a la feroz represión oficial que dejó muchos muertos y heridos, durante  la masacre de Tlatelolco, entre los estudiantes mexicanos.</p>
<p>Medio siglo después de aquel  legendario Congreso de Valencia, se invitó a los sobrevivientes. A Octavio Paz  eso le provocó un gran texto: &ldquo;El lugar de la prueba&rdquo;. Lo reprodujo <em>La Nación</em> el 8 de noviembre de 1987. Y en él descubrí una vertiente bien oculta. Dice: &ldquo;Porque  la libertad de expresión está en peligro siempre. La amenazan no sólo los  gobiernos totalitarios y las dictaduras militares, sino también, en las  democracias capitalistas, las fuerzas impersonales de la publicidad y el  mercado. Someter las artes y la literatura a las leyes que rigen la circulación  de mercancías es una forma de censura no menos nociva y bárbara que la censura  ideológica.&rdquo;</p>
<p>En su libro <em>La otra voz</em> / <em>Poesía y fin de  siglo</em>, de 1990, el año de su Premio Nobel, Octavio Paz reitera claramente:  &ldquo;Hoy las artes y la literatura se exponen a un peligro distinto: no las amenaza  una doctrina o un partido político omnisciente sino un proceso económico sin  rostro, sin alma y sin dirección. El mercado es circular, impersonal, imparcial  e inflexible&rdquo;.</p>
<p>Y en otro libro, <em>Al paso</em>, insiste: &ldquo;Pienso en la solapada dominación del dinero y el  comercio en el mundo del arte y la literatura. Las leyes del mercado no son  estrictamente aplicables a la literatura, al pensamiento y al arte. Las  potencias meramente comerciales, regidas por el criterio del éxito y la venta,  tienden a la uniformidad –máscara de la muerte–&rdquo;.</p>
<p>No era algo casual. El 25 de agosto de  1992 leo en <em>La Nación</em>: &ldquo;Es muy  grave que el relativismo social actual se convierta en un nuevo absolutismo  basado en esta idea: las cosas no tienen valor, tienen precio. Este es el  camino por el cual una sociedad se destruye&rdquo;. Y añade: &ldquo;Cuando yo era joven el gran  enemigo del arte eran los Estados autoritarios. Esta amenaza ha sido sustituida  por otra mucho más sutil: la amenaza del mercado, que lo relativiza todo. Estas  son las grandes amenazas modernas. El mecanismo del mercado no tiene ideología,  acepta todas, las usa todas, no respeta ninguna y se sirve de todas ellas&rdquo;.</p>
<p>Si fuera poco, en <em>Le Nouvel Observateur</em> poco antes de morir, en 1998 afirma Paz: &ldquo;Se  habló del desastre del autoritarismo, sería preciso hablar del desastre del  capitalismo liberal y democrático, en el dominio del pensamiento como en el de  la vida cotidiana; la idolatría del dinero, el mercado transformado en valor  único que expulsa a todos los otros&rdquo;.</p>
<p>Podría citar más, pero ya basta. Llegó  la hora de pensar a Octavio Paz en su complejidad, sin anteojeras. No quiero  decir que tal reiteración sea única. Pero siento que le debemos el considerarlo  íntegramente, desde nuestra propia perspectiva, sí, pero en toda su fecunda  riqueza. Así empezó a ocurrir lo que algunos no hubieran esperado: intelectuales  cubanos impulsaron un seminario de análisis a fondo para la entera obra de Paz.</p>
<p>Y hay más. En &ldquo;El lugar de la prueba&rdquo;,  cincuenta años después de aquel congreso antifascista, Octavio Paz sólo  recuerda esto: &ldquo;En fin, y ante todo, el trato con los soldados, los campesinos,  los obreros, los maestros de escuela, los periodistas, los muchachos y las  muchachas, los viejos y las viejas. Con ellos y por ellos aprendí que la  palabra fraternidad no es menos preciosa que la palabra libertad: es el pan de  los hombres, el pan compartido. Esto que digo no es una figura literaria. Una  noche tuve que refugiarme con algunos amigos en una aldea vecina a Valencia  mientras la aviación enemiga, detenida por las baterías antiaéreas, descargaba  sus bombas en la carretera. El campesino que nos dio albergue, al enterarse de  que yo venía de México, un país que ayudaba a los republicanos, salió a su  huerta a pesar del bombardeo, cortó un melón y, con un pedazo de pan y un jarro  de vino, lo compartió con nosotros&rdquo;.</p>
<p>¿Alguien capaz de expresar eso no  merece que volvamos a pensarlo de nuevo? </p>
