<p>Un hombre anciano frente a la  cazuela de barro toma su alimento, se lleva la cuchara a la boca en un gesto  cotidiano y sencillo. Solo, sentado a la mesa de aspecto rústico, abstraído en  sus pensamientos con el entrecejo fruncido. ¿Qué rumbo tomarán sus reflexiones,  qué aconteceres de su pasado y su presente dan cuerpo a sus cavilaciones? El  ambiente austero, y la pequeña mesa de madera que sostiene la básica  subsistencia se recorta en esa habitación humilde. Un trozo de pan, junto al  recipiente nutricio; un par de lentes y un vaso de agua que sostiene un libro  ajado y algo destartalado<em>. I Giusti</em> es su título, que aparece borroneado por el paso del tiempo, implacable con la materialidad  del mundo, transfigura los objetos cotidianos. <br />
  <br />
  <em>I Giusti,</em> un título significativo que a su vez da nombre a esta  pintura de pequeño formato (óleo sobre madera, 38 cm por 48,5 cm) realizada en  1912, la cual forma parte de la exhibición permanente del Museo Nacional de  Bellas Artes; pasó a integrar la colección del Museo en 2004, donada por León Ferrari.<br />
  <br />
Será que se avizora el tiempo de <em>Los Justos</em>, o tal vez Augusto César  Ferrari alude a una existencia alejada de lujos y excentricidades, vivir con <em>lo justo</em>. El interior del recinto que da  marco a la figura principal del cuadro, denota la condición de existencia de  ese sujeto frente al alimento esencial, urgido por el carácter de lo  indispensable. Lo justo, lo necesario en su expresión más elemental. El gesto  adusto, calmo y reflexivo de ese hombre entrado en años, trasunta un recorrido  arduo y dilatado en diversos avatares insondables. Alimento orgánico y alimento  intelectual, el pan y el libro en tanto significantes primordiales de la  condición humana encuadran la imagen.<br />
<br />
La mesa se recorta en la escena y  se dibuja en un triángulo que se extiende hacia un ángulo interior del  ambiente. Allí arriba, apoyado sobre una viga de tronco, reposa un plato de  latón roído por el tiempo. Un estante de madera con algunos cacharros en la  pared lateral, donde cuelgan dos recipientes de barro completa el cuadro.<br />
<br />
El pincel del artista compone un  relato donde pueblan los tierras y ocres, con zonas  de pincelada a modo de mancha, que iluminan en  tenue claroscuro el conjunto planteado. Es una escena verosímil, palpable, que  nos remonta a los ancestros de inmigrantes europeos de posguerra que buscaron  nuevos destinos alejados de lo insoportable; hambre y muerte nunca son signos  propiciatorios de un porvenir posible.<br />
<br />
Augusto César Ferrari nació el 31  de agosto de 1871 en la localidad de San Possidonio, provincia de Módena,  Italia. Respondiendo al mandato paterno completa sus estudios de arquitectura en  1892, en la Universidad Génova, y posteriormente se radica en Turín donde se interioriza  en el arte de la pintura. Realizó sus estudios en la Academia Albertina y el  estudio de Estilos Antiguos y Modernos en el Museo Industrial. Llega a Buenos  Aires en 1914, poco antes de la primera Guerra Mundial y luego de unos años  retorna a su tierra natal donde se dedicó primordialmente a la pintura. Nuevamente  viaja para instalarse en Argentina a partir de 1927. Reside en Córdoba un  prolongado período y concreta varios desarrollos arquitectónicos en el país,  donde permanece hasta su fallecimiento, a los 98 años.</p>
<p>Arquitecto y pintor, integró en  su labor la combinación de ambas disciplinas junto con la fotografía. Al igual  que Antonio Berni, realizaba registros fotográficos de sujetos de diverso  linaje, incluyendo a sus propios familiares, también a obreros, tomándolos como  modelos que luego volcaría en imágenes para construir sus pinturas murales. En  su rol de arquitecto se especializó en el diseño y construcción de iglesias,  muchas de las cuales se erigen en Córdoba y Buenos Aires. En pintura desarrolló  -además de otros temas y soportes- el formato de <em>panoramas</em>, narrativas pictóricas de grandes dimensiones, frisos  montados en bastidores.<br />
  <br />
  Una muestra de su obra se realizó  en 2002 en el Centro Cultural Recoleta de la ciudad de Buenos Aires, organizada  por su hijo León, ya octogenario, quien pergeñó la exposición en homenaje a su  padre, para visibilizar su producción en tanto partícipe del desarrollo del  arte argentino en el siglo XX. La iniciativa estuvo acompañada por el libro <em>Augusto C. Ferrari 1871-1970; cuadros,  panoramas, iglesias y fotografías</em> en el año 2003, publicado en 2003 por la  editorial Licopodio. <br />
  <br />
  León Ferrari fue el mentor y  curador de aquella exposición desarrollada en memoria de su padre artista, con  vistas a la puesta en valor de su valiosa trayectoria. Esta pequeña pieza titulada <em>I Giusti </em>da cuenta de la talla de  Augusto César y porta una marca de origen.</p>
