<p>Las  herramientas utilizadas para crear una narrativa, una visión o un concepto en  el cine son, prácticamente, ilimitadas. Desde la iluminación hasta los más  mínimos detalles en el set de filmación las películas utilizan enormes  cantidades de recursos para contar una historia y presentar una narrativa  combinada con elementos audiovisuales y la sutileza del arte escrito. Algunos  de estos elementos se presentan ante el espectador de manera explícita; podemos  absórbelos de forma instantánea mientras la cinta corre el tiempo de su  duración, sin embargo hay algunos elementos que pasan desapercibidos ante  tantas capas de complejidad que un filme puede presentarnos. Otros trucos y  técnicas requieren un ojo más crítico o una formación en la apreciación del  arte subida a otra escala, haciendo que lo complejo este oculto ante los ojos  del espectador común. Incluso, con todos estos componentes muchos filmes  necesitan una mirada detallista que los repase varias veces para poder entender  y apreciar en grandes escalas la completa intensidad que compone una obra del  séptimo arte.<br />
  <br />
  A diferencia de otros medios artísticos el cine es el que integra a sus seis  antecesores. Compuesto por el teatro (la actuación), la arquitectura (el armado  de sets y locaciones), la pintura (la compleja creación artística de una  escena), la música (la integración de esta y la utilización del sonido),  incluso la danza en muchos casos dada su expresión corporal y utilización de la  misma como un recurso fílmico&nbsp; y finalmente la literatura, como ese arte  que genera la estructura inicial de cualquier historia y dialogo presentado en  un filme. Esta complejidad de elementos pone al cine entre uno de los más  complejos en su clase y estira sus horizontes a varias formas de apreciación  del mismo. Como consecuencia muchas veces es difícil poder absorber todos los  elementos en una sola mirada. El cine para muchos es considerado el arte de la  distracción, y dentro de esta calificación hay mucha verdad. El cine está  creado para esconder sus grandes hazañas. Muchas veces no apreciaremos la  genialidad de algo que está escondido bajo capas de tecnicismos y expresiones  lejanas a la interpretación del ojo crítico. Uno de estos grandes secretos y  gemas ocultas del arte cinematográfico es el de la edición.<br />
  Según los estándares  de Hollywood una buena edición es aquella que no puede ser percibida por el ojo  del espectador promedio. Claramente esto no define que los cortes en la edición  no sean visibles, si no que en el proceso de utilizar estos cortes la mente del  espectador continué el entramado de la película de una manera correlativa al  cuadro anterior. Podemos percibir los cuadros, pero si todo esta hecho  concretamente entonces nuestra mente se perderá y se centrará en otros  elementos que rodean el arte cinematográfico.&nbsp;<br />
  <br />
  La edición muchas veces puede decir más de lo que a simples rasgos podemos  entender. Si bien hay técnicas de edición que son básicas para contextualizar y  narrar una escena, hay otras que van a niveles más profundos. Con la edición  podemos entender el contexto de una charla, quien se mira con quien, cual es la  orientación general de la escena y el tiempo en el que dos sucesos pueden estar  sucediendo tanto al mismo tiempo como en grandes saltos temporales.<br />
  Lo grandioso de este arte contenido dentro del arte cinematográfico es la  utilización del mismo para generar mucho más que simples conexiones, ya sea  lograr contar algo o narrar algo, al igual que lo hacen los otros elementos del  mismo arte, como la banda sonora, el guion o la fotografía.<br />
  Para dar un ejemplo  de la complejidad y el paralelismo entre lo que un director puede hacer con la  imagen y un editor puede hacer con la edición me gustaría citar a uno de los  casos que, personalmente, me han dejado más deslumbrado en cuanto a los  diversos recursos que un editor puede utilizar para acompañar la visión de un  director.<br />
  <br />
  Wes Anderson es conocido, entre tantas cosas, por su visión simétrica a la hora  de filmar las escenas. Sus cuadros son reconocidos por estar centrados  simétricamente, con el decorado y los actores en un punto medio de la pantalla,  creando una imagen de simetría en la mayoría de sus tomas. Lo que pocos saben  es que la simetría de Anderson en sus filmes llega más allá de lo presentado en  los recuadros de sus películas. La edición de Anderson en muchos casos es  también simétrica. Esto quiere decir que el director juega tanto con planos y  contraplanos como con la edición general de cuantas veces usa un recuadro a la  hora de crear la narrativa fílmica. Un hermoso ejemplo de este arte es una  escena de su película &quot;The Grand Hotel Budapest&quot;, donde dos de sus  personajes principales se encuentran en un vagón de tren y les son solicitados  sus papeles. Al ver la escena podemos apreciar cómo cada corte termina en una  posición similar al anterior. Finalmente, ubicando en columna todos los cortes  de esta escena particular podemos ver algo como esto:</p>
<img src="images/2101.jpg">
<p>Pero  este es solo uno de los pequeños gustos y genialidades que pueden realizarse  con el arte de la edición. Muchos de los grandes directores de antaño y nuestra  actualidad han logrado innovar y seguir creando nuevas formas para utilizar un  recurso tan invisible para la vista de alguien completamente envuelto en un  filme, pero que sin embargo es un elemento crucial para la calidad del producto  final.</p>
<p>  Observar en el  cine, a fin de cuentas, es un arte aparte. Poder absorber cada pedazo, cada  pequeña obra de arte contenida dentro de un panorama mayor hace que el cine sea  hasta el día de hoy una de aquellas formas de entretenimiento que puede seguir  renovándose y encontrando cada vez mejores formas de expresarse a sí mismo.</p>
<p>&nbsp;</p>
