<p>  Mucho se ha escrito acerca de la función del hombre dentro  del sistema capitalista. Ubicado ya en un extremo de la línea que atraviesa las  relaciones de poder como el otrora señor feudal, ya en el otro, como el  trabajador asalariado que vende su fuerza de trabajo, el hombre no es sino un  eslabón de una intrincada cadena.<br />
  <br />
  Un reciente film francés,&nbsp;<em>El precio de un hombre</em>&nbsp;(<em>La loi du marché</em><em>&nbsp;</em>de Stéphane Brizé), expone esta cuestión de manera  diáfana, sin pretensiones de moralidad, sin recurrir al golpe bajo. A través de  logradas secuencias en las que la cámara apenas se desplaza entre un personaje  y otro, y con el&nbsp;<em>tempo </em>característico del (buen) cine  francés donde cada detalle, cada gesto, cada parlamento discurre sin el apuro  del efectismo ni la necesidad imperiosa de la elipsis -característicos del cine  de tono hollywoodense-, la historia de un cincuentón desempleado que busca  denodadamente re-insertarse en el sistema laboral ilustra magistralmente esta&nbsp;<em>canibalización</em>&nbsp;a la que los sujetos son sometidos  una vez dentro de éste.<br />
  <br />
  Enfrentado al hecho de tener que cumplir  estrictamente con las obligaciones y deberes propios del hombre de clase media,  proveedor, cabeza de familia, casado y padre de un adolescente discapacitado,  tal la situación del personaje principal, éste debe (¿debe?) ser sometido a  toda clase de humillaciones: una entrevista vía skype donde el reclutador de  personal de una empresa ofrece reducirle considerablemente el salario anterior  aunque dejándole en claro que de todos modos las posibilidades de obtener el  puesto son muy escasas, una reunión con una joven y prolija empleada del banco  que le sugiere, primero, hipotecar su casa y, luego, sacar un seguro de vida  para &ldquo;dejarle algo a su familia&rdquo;, y finalmente una especie de juicio cuyo  tribunal está integrado por un pequeño grupo de nóveles aspirantes a selectores  de personal que, de un modo notablemente irreverente, le critican su postura  corporal, el tono de su voz y su aspecto físico durante una entrevista.<br />
  <br />
  Así las cosas, y ya harto consciente de que  conforme pasa el tiempo las posibilidades de formar parte de ese cuerpo  mancomunado de explotadores y explotados van reduciéndose considerablemente, el  hombre consigue su lugar: un puesto de encargado de vigilancia en un  hipermercado. Allí, las órdenes que no tardará en recibir son bien claras: el  dueño del lugar necesita reducir personal, por lo tanto su labor será &ldquo;detectar  hasta el más mínimo detalle&rdquo; -excusa- para sancionar -echar- al personal,  específicamente de la línea de cajas del local. No obstante, primero deberá  vigilar, a través de las cámaras, a los clientes, quienes, en caso de que se  los descubra en alguna actitud sospechosa, serán llevados a una sala apartada  en la que nuestro hombre participará -ya como testigo, ya como juez-&nbsp; de  un cruel interrogatorio que culminará con el castigo del detenido -mención  aparte para la escena en la que un hombre de unos 80 años es sorprendido por  colocar entre sus ropas dos bandejas de carne que, como consecuencia de la  vejación a la que es sometido en el interrogatorio, confesará que robó porque  ni el dinero que lleva encima ni el que tiene en su casa le alcanzaban para  pagarlas-.<br />
  <br />
  Pero de los clientes, sujetos anónimos a quienes  no lo une ninguna relación, pasará a tener que señalar a sus propios  compañeros, aquellos que como él -ahora lo sabe perfectamente- deben cuidar con  uñas y dientes su trabajo. Y es justo en este momento donde el sintagma que  titula el film cobra un valor insondable: &ldquo;el precio del hombre&rdquo;. ¿No debería  ser la empresa, en este caso, quien pague un precio por el trabajo del hombre?  ¿Por qué es el hombre quien debe pagar un precio? ¿Qué precio debe pagar un  hombre y para qué? Todos estos interrogantes son – y de ahí el valor inestimable  de esta narración cinematográfica– acabadamente respondidos por esta obra  maestra que no tiene precio.</p>
