<p>En 1961, una empresa constructora de Fairbanks (una pequeña  ciudad de Alaska) obtuvo un contrato para construir una carretera en un bosque.  Esta empresa compró tres colectivos &nbsp;viejos, destinados a desguace, que  habían pertenecido al servicio de transporte público de la ciudad. Esos típicos  colectivos estadounidenses, como el que maneja el personaje de Robert de Niro  en&nbsp;<em>Una luz en el infierno</em>. La idea era que en ellos se alojaran los peones que  construirían la carretera. Se refaccionaron con una estufa cilíndrica a leña y  un catre. En 1963 la empresa retiró dos de los colectivos. Dejaron uno solo  como favor para los cazadores de osos. Esos maricas que cazan osos, como el  cantante de Metallica.&nbsp;<br />
  <br />
  En ese colectivo que aún quedaba, en 1992, fue  encontrado el cuerpo de Christopher McCandless, después de haber estado solo  durante casi cuatro meses, en medio de la tundra de Alaska, con escasa comida y  equipo. Fue el final para un viaje que había durado casi dos años.<br />
  <br />
  Un libro recoge su hazaña y pormenoriza su vida.&nbsp;<em>Into the wild</em>, de Jon Krakauer, publicado en 1996. &nbsp;Curiosamente,  debemos a este experto en alpinismo la única investigación sobre la vida de  McCandless.&nbsp;<br />
  <br />
  La historia que nos cuenta Krakauer es romántica y  lleva la impronta de la epopeya. Convierte el&nbsp;<em>tour de force</em>&nbsp;de McCandless en un culto, y al mismo  McCandless en un símbolo. Su libro es una biografía pero también –como los  libros que leía McCandless cuando emprendió su travesía- es una iniciación. Por  fuera de los testimonios de sus padres, el mito &ldquo;supertramp&rdquo; está edificado  sobre&nbsp;<em>Into the wild</em>, que en español se ha traducido como&nbsp;<em>Hacia rutas salvajes</em>. La traducción, creo, no fue gratis y se quedó con parte de  la fuerza que en inglés tiene la palabra&nbsp;<em>into</em>.&nbsp;<br />
  <br />
  Cristopher McCandless había nacido en Virginia en  1969. Cuando murió en ese colectivo era un joven de veinticuatro años con todo  por delante. Pero al parecer, todo lo que tenía por delante lo asustaba desde  su adolescencia. Empezó por sentir que no quería vivir la misma vida que sus  padres. Graduado en la universidad con excelentes notas en historia y  antropología, pateó el tablero y se fue de su casa. Haciendo dedo, con una  mochila donde llevaba lo necesario y que se fue vaciando a medida que el viaje  se convertía en una suerte de peregrinación, llegó a Alaska. Sólo conservó un  rifle y una cámara fotográfica. En el camino, trabajó por aquí y por allá.  Conoció gente que brindó después algún testimonio. &nbsp;A medida que  McCandless se adentraba en la naturaleza, su piel y sus cosas se iban  desprendiendo de él. También los kilos y la salud, aunque esto no lo tenía  previsto. Su modo de encarar la naturaleza fue por momentos –igual que el libro  de Krakauer- romántico. Se cambió el nombre y se puso un seudónimo –Alexander  Supertramp- con el que fue dejando, por los lugares donde pasaba, distintas  notas y mensajes. Su última nota –donde nos deja entrever que ya le estaba  viendo la cara a la muerte- lleva su nombre verdadero.&nbsp;<br />
  <br />
  Cansado de su tradicional familia, de las imposiciones  sociales, de las normas y las instituciones de la cultura, soñó con volver a  esa extraña forma de paraíso que es el primitivismo. Una película de 2007,  dirigida por Sean Penn y también llamada como el libro, exagera la relación  difícil de Cristopher con sus padres, lo que ayuda a establecer un poco el mito  y de paso definir al héroe.&nbsp;<br />
  <br />
  Al comienzo de la película, los padres de  Cristopher lo esperan en un restaurante para celebrar su graduación. Para  demostrarnos que se trata de un chico rebelde, Penn comete el infantilismo de  hacerlo saltar al escenario cuando sube a recibir el diploma, en claro  contraste con los otros, que habían subido caminando despacio.<br />
  <br />
  -Me asustaste saltando de esa forma sobre el  escenario –le dice la madre cuando se levanta a recibirlo. Es una mezcla de  boluda alegre con pobre mujer sometida por el marido que vive de las  apariencias y trata de contemporizar la mala relación entre padre e hijo.&nbsp;<br />
  <br />
  El padre es un tipo al que le tiraríamos la sopa  caliente encima fingiendo un descuido. Es intolerante, machista, xenófobo,  homofóbico, patriarcal, déspota. Ya vemos en la mesa que su hijo lo  desilusiona. Ni bien se sienta lo reprende por un hecho en el que no hemos  reparado, porque no somos como él. Cristopher tiene un viejo Datsun amarillo.  Cuando llegan al restaurante con su hermana, es ella la que maneja. Entonces el  viejo le dice que no debería dejar que una mujer conduzca. Esa observación –una  buena para Penn- alcanza para pintarlo de cuerpo entero. Para peor, quieren  regalarle a Cristopher un auto nuevo y éste se enoja, culpando a sus padres de  ser materialistas y preocuparse todo el tiempo por cosas y más cosas. &nbsp;<br />
  <br />
  Algunos detalles circunstanciales son inevitables  –sino la historia caería en el abstracto- pero Penn tiene la costumbre de  contarlos a la manera de un estereotipo. En la línea del chico rebelde que  salta al escenario en vez de caminar cuando recibe su diploma, vemos que  Cristopher rompe todas sus tarjetas y documentación; más tarde, lo vemos  prender fuego a unos pocos dólares en lugar de regalarlos. Cualquier alma  sensible –y McCandless la tenía- saber que tirar pan o quemar dinero son  impiedades. Salvando estas cuestiones –que tampoco incomodan demasiado- la  fotografía y los escenarios son muy buenos. Capítulo aparte –ensayo que de  seguro jamás escribiré- merecen las hermosas canciones que compuso Eddie Vedder  para la película, como por ejemplo&nbsp;<em>Society</em><em>&nbsp;</em>o&nbsp;<em>Big hard sun</em>. Finalmente, tanto el libro como la película  basada en el libro&nbsp;<em>Into the wild</em>&nbsp;hacen pensar en el verdadero muchacho  que, disconforme con todo –disconformidad general cuya síntesis eran sus  padres-, decidió salir a buscar algo, acaso entrevisto, tal vez imaginado. La  experiencia McCandless ha tenido muchos detractores. Afortunadamente, esas  abyecciones no recaen en su protagonista. Critican lo que él hizo para que no  lo hagan otros –los imitadores son inevitables- pero son benevolentes con él.  Tal vez porque vemos que tuvo el coraje de hacer lo que nosotros no. Como dice  la canción de MGMT,&nbsp;<em>it's overwhelming, but what else can we do. Get  jobs in offices, and wake up for the morning commute.</em><em>&nbsp;</em><br />
  <br />
  Miles de veces en toda mi vida me he preguntado  para qué estamos todos aquí. ¿Para pasar la mayor parte de los años que  viviremos yendo a trabajar para ganar una suma de dinero de la cual, una parte,  será gastada en nafta o colectivos o trenes para ir cada mañana a ese mismo  trabajo? &nbsp;Creo que esa sensación nos hermana a todos con McCandless. Decir  que es un boludo que se buscó la muerte es perfectamente asimilable también a  un tipo que abandonó el colegio o se casó con cualquier mujer sin pensarlo.  ¿Cuántas formas de buscarnos la muerte hay en las que no necesariamente hay que  ir a Alaska? Ese colectivo abandonado en la tundra, ¿no es acaso también un  monoambiente en el centro cuya única ventana da al pulmón interno? Acaso nos  confunde una cuestión de tiempos. O simples velocidades. Lo rápido que murió  McCandless nos hace pensar que nuestra dilatada sequía espiritual es una forma  de eternidad. McCandless hizo lo que Kurt Cobain escribiría en la última línea  de su carta suicida un par de años más tarde: mejor arder de golpe que  consumirse lentamente.&nbsp;<br />
  <br />
  Sé que no tenía ganas de morir. Que cuando se fue  de su casa, con una mochila, sin mapas, y con las lecturas de Jack London en la  cabeza, quería vivir. Vivir plenamente, sacarse el hastío. No se conformó como  la mayoría. &nbsp;Salió a buscarse. A ver cuál era su lugar en el mundo.  Encontró la muerte por inanición, por descuidado, por desconocer la geografía a  la que había llegado, ok. Pero quería vivir. Así lo expresan sus últimas  palabras escritas. Sabemos por ellas, sin embargo, que murió feliz. Nos dejó su  bendición. Su alma no estará en un lugar peor que la de un banquero.</p>
<span class="image_cen1"><img src="images/2301.jpg"></span>
