<p>Cuando Alexander Sokurov realizó el <em>Arca Rusa</em>, una de las obras del arte cinematográfico en que la  técnica tiene un lugar central, la dirección de la cámara recorría la historia  y el arte de Rusia en una única toma, un largo plano secuencia. Seguramente ese  enorme trabajo de producción tenía una intencionalidad: un continuo, un flujo  unidireccional, una corriente que transcurría y así capturaba nuestra atención  en una tensión de una sola cuerda, el espectador era parte de las escenas, era  convocado como un elemento más por este recurso, se lo refería explícitamente  para que se incluyera en la misma, toda la belleza del Hermitage que el  director ponía ante sus ojos estaba toda presentada ante él, sólo había que  dejarse llevar por el viaje.<br />
  <br />
  La maestría de Sokurov recurre a nuevas  herramientas y esta vez produce un film sin una linealidad. Con <strong>Francofonía</strong> nos propone el trabajo de  terminar de construir la película, al modo en que los pintores cubistas nos  ponen a trabajar cuando nos enfrentan a la simultaneidad de sus diferentes  planos. No hay una linealidad, un punto de fuga en el que confluye la obra, hay  que poner de uno para armarla.&nbsp;<br />
  <br />
  <strong>Francofonía</strong> es una  propuesta en la que varios planos se presentan sucesivamente, varios planos que  abordan un tema central desde varios ángulos, mezclados, pero todos presentes;  sólo que el elemento temporal del cine presenta los puntos de vista  sucesivamente y no simultáneamente, aun así, el espectador tiene que leer los  planos y ponerse a construir el tema central de la película a través de un  episodio de la Segunda Guerra Mundial en el que dos hombres de bandos  diferentes: el conde Franziskus Graf von Wolff Metternich a cargo de la  protección de las obras de arte del Rhineland y la Francia ocupada por el ejército  nazi y Jacques Jaujard director de los Museos Nacionales de Francia se  interesan por lo mismo: las obras de arte alojadas en el Louvre. ¿Las paradojas  de la historia de la humanidad? ¿La nobleza y la miseria del hombre?<br />
  <br />
  Sokurov superpone muchas líneas de abordaje: la  humanidad como un barco en una tormenta, la guerra como mar embravecido en el  que un barco con su carga de arte es conducido por un capitán que no puede  responder por cómo va a terminar la travesía, lo azaroso que mete la cola en el  destino de lo que atesoramos, el orgullo, la soberbia, la estupidez pero también,  la templanza, el manso coraje y la decencia. ¿Qué dirían Tolstoi y Chejov de  todo esto, convocados en retratos fugaces? Sokurov mismo aparecería como un  personaje preocupado, expectante, un Velázquez pero de hoy. El y nosotros somos  testigos de la historia de Francia: la República y el Imperio, los ideales de  una nación, lo que hace su grandeza, su valor cuando las papas queman. Qué  queda cuando el mar se calma. Como en la vida.<br />
  <br />
  Una invitación de Sokurov que vale la pena aceptar.</p>
