<p>Una alternativa a las <a href="http://estonoesunarevista.com.ar/nro026/sabores.html">verduras asadas</a> es el <strong>tumbet</strong>, platillo de origen mallorquín que mantiene el afán mediterráneo y añade a la mezcla de verduras y hortalizas la patata, generalmente ausente de las verduras asadas. Esta receta me la dieron por teléfono, directamente leída del recorte de la receta aparecida, a finales de los años sesenta, en una de las cabeceras decanas de la &ldquo;prensa femenina&rdquo; española, llamada así entonces. La gastronomía no tenía en aquella época la dimensión que tiene hoy, y la sección se limitaba a tres o cuatro tiras con otras tantas recetas y sus correspondientes fotografías. La hicimos varias veces y siempre funcionó muy bien. He adaptado el lenguaje para entendernos mejor.</p>
<p><strong>Ingredientes</strong>: Dos patatas grandes, un pimiento verde y uno rojo (mejor ambos rectangulares, de carne gruesa, como la variedad lamuyo), una berenjena, una cebolla grande, tres tomates maduros (o una lata pequeña de tomate pelado y entero), aceite de oliva virgen, sal y pimienta.</p>
<p>1.- Se cortan las patatas como para tortilla pero algo más gruesas (alrededor de medio centímetro de grosor), se salan y se fríen sin que terminen (que queden blandas pero sin color), se escurren bien de aceite y se colocan en una fuente de horno más bien plana, cubriendo todo el fondo.</p>
<p>  2.- En la misma sartén, añadiendo algo de aceite si es necesario, se fríe cebolla cortada en rodajas de medio centímetro de grosor y cuando está transparente, se saca, escurre bien de aceite y se coloca sobre las patatas en el recipiente de horno.</p>
<p>  3.- Se fríe la berenjena, con o sin piel, cortada en rodajas de aproximadamente medio centímetro de grosor y salada. Cuando está blanda se saca, se escurre bien de aceite y se coloca encima de lo anterior en el recipiente de horno.</p>
<p>  4.- Finalmente se fríen los pimientos, limpios de semillas y cortados en tiras, se escurren bien y se van colocando sobre lo anterior.</p>
<p>  5.- Encima de todo ello se pone el tomate, que puede estar ya frito o en crudo, partido en rodajas.</p>
<p> 6.- Se muele pimienta por cima y se mete al horno, a unos 160 grados unos diez minutos.</p>
<p>La mayor precaución al cocinar este plato es evitar que esté demasiado grasiento, para lo cual es conveniente escurrir muy bien cada una de las hortalizas que freímos, depositándolas en un escurridor, antes de colocarlas en el recipiente. También hay que ser cuidadosos con la sal: es mejor salar cada una de las verduras por su parte al freírlas, pero sin perder de vista la cantidad total de sal que vamos añadiendo. Una vez colocadas las verduras en el recipiente, además de pimienta, puede añadirse alguna hierba aromática, orégano, tomillo, romero, etc.</p>
<p>El tumbet puede comerse recién salido del horno, templado pasadas unas horas o incluso al día siguiente, a la temperatura del tiempo.</p>

<span class="image_cen1"><img src="images/3001.jpg"></span>
