<p>Casi como si supiera que más de cien años después una revista  digital le iba a dedicar un número a la lluvia, Freud le envía una carta a su  mujer para describir unas de esas tormentas que no se olvidan con facilidad.  Aquí pues se lo agradecemos y la compartimos:</p>
<p><em>1894, Viena</em><br />
  <br />
  <em>Amada mía:</em><br />
  <br />
  <em>Ayer, por la tarde,  hizo un calor insoportable. Por la mañana, me he despertado a las seis, he  visto que ya entraba luz en la habitación; he pensado para mí que este raro  acontecimiento de despertarse tan temprano debería aprovecharse para algo útil;  he llamado a la puerta de Marie, pidiéndole que me preparara el baño, y después  me he acostado de nuevo. Media hora más tarde volví a despertarme; hallé la  habitación tan oscura, que ni siquiera pude mirar la hora; deseché la idea de  que quizá me hubiera quedado ciego; me precipité a la ventana y vi un retazo de  ennegrecido firmamento. Minutos después se oía el resonar del trueno. A poco,  la calle estaba completamente blanca; los caballos se desbocaban, y grandes  granizos, de fantástico tamaño, comenzaron a arremeter contra las ventanas. Fui  corriendo a la parte posterior de la casa y encontré la ventana del despacho ya  rota en tres lugares, con mi mesa de escribir cubierta de agua y, como es  lógico, las contraventanas abiertas de par en par. La terraza tenía un  aspecto que caso pudiéramos denominar grandioso. Las puertas se habían abierto  también, impulsadas por el vendaval, y había entrado el granizo, llegando hasta  el aparador. La tormenta duró media hora. Los estragos que ha producido en la  ciudad son espantosos. En una de las fachadas de casi toda la calle (la de enfrente,  en Berggasse) la mayoría de los cristales está roto, especialmente en los pisos  superiores. Hay casas enteras en las que no ha quedado ni un solo cristal sano, como si los niños se hubieran dedicado a apedrearlos. En las esquinas y en las  ventanas que no habían sido protegidas con molduras, el resultado resulta  formidable. Una mujer que vino a la consulta esta mañana tenía razón al afirmar  que las ventanas parecían arcos circenses después de haber saltado los perros a  través de ellos. En otras calles se ven menos destrozos. Los que más han salido  perdiendo son los árboles. En nuestro jardín hay más hojas en el suelo que en  las ramas, y el pobre árbol se ha quedado desnudo y zurrado. Parece que le han  flagelado con látigos y que los gusanos se han devorado luego lo que quedaba.  Todo lo que se pareciera a un jardín debe de estar ahora en un estado  lamentable. Me han dicho que el arreglo de las ventanas –en nuestro caso, solo  una- corre de cuenta del casero. Estoy deseando también saber si hubo tormenta  donde tú estás, pues hubiera sido horroroso. Espero que no y que se haya  limitado a descargar sobre esta ciudad.</em><br />
  <br />
  <em>No tengo más noticias  que darte. Ayer te escribí por la tarde, y hoy espero hacerlo otra vez.  Hablando de negocios, hoy hubiera sido más provechoso ser cristalero que  médico.</em><br />
  <em><br />
  Afectuosos saludos.  <br />
  <br />
  Tuyo,</em><br />
<em>Sigmund</em></p>
