<p align="right"><em>&quot;El arte  es confesión; es un secreto revelado&quot;</em> <br />
  <strong>Thornton Wilder</strong></p>
<p>&quot;Pero el arte no es sólo el deseo  de revelar el secreto de uno mismo; es el deseo de revelarlo y esconderlo al  mismo tiempo&quot;, continúa Wilder. ¿Qué es el arte? Un par de cosas que no  necesitan etiquetas; esa necesidad humana de rotular lo que somos y lo que  hacemos, en la que no se considera que para expandirnos con los otros y en los  otros, conviene olvidar las definiciones.</p>
<p>Entre las primeras preguntas que  hacemos cuando conocemos a alguien está la de &ldquo;a qué se dedica&rdquo;. &ldquo;Dedicar&rdquo;viene  del latín <em>dicare</em>: &lsquo;consagrar, destinar algo en justicia&rsquo;. Tanto el verbo <em>dicare</em> como el verbo <em>dicere</em> tienen origen en la raíz indoeuropea <em>deik</em> que significa &lsquo;indicar&rsquo;, &lsquo;mostrar&rsquo;. Porque desde siempre, los seres humanos  indican, levantan el dedo y toman fragmentos de la realidad; catalogarlos;  convertirlos en pequeños mundos con reglas propias. Pero, como bien dijo un  autor irlandés, todo lo que define termina limitando.</p>
<p>Definir, entonces, lo que es y lo que  no es &ldquo;arte&rdquo; es una tarea compleja y, por lo demás, inútil. Tal vez podríamos  hablar de múltiples puntos de vista, de múltiples acercamientos a lo que el  arte representa para cada individuo. Para Thornton Wilder la cuestión iba por el  lado del secreto y de la revelación; para Nietzsche le tenemos al arte &ldquo;para no  morir de la verdad&rdquo;; para Ernesto Sábato es &ldquo;lo que mágicamente nos permite  evadirnos de la dura realidad cotidiana&rdquo;.</p>
<p>Los secretos que todos los seres  humanos escondemos; los que la realidad comparte y esconde al mismo tiempo, se  hacen arte. Hay una sensación de plena profundidad en lo que hacemos en ese  sentido, por más nimio que nos parezca, por más acosado que esté por el cariz  de lo doméstico; un universo doméstico que nos han enseñado a desdeñar por  insignificante, y donde también se esconde y se revela la magia que los seres  humanos sabemos producir. Así, rotular(nos), encajarnos en etiquetas que nos  definan le roban sentido a esa magia. No estoy a favor de la famosa frase &ldquo;eres  lo que haces&rdquo;. ¿Qué hay de la gente marginada del cruel sistema que es este  mundo? ¿Cómo pueden expandirse si no tienen los medios para hacerlo?</p>
<p>¿Significa eso que sólo son lo que hacen, es  decir, lo que son empujados a hacer por las leyes de un sistema desequilibrado?</p>
<p>Creo que, en definitiva, somos muchas  cosas todo el tiempo; quizá seamos lo que imaginamos que somos, o hemos sido o  seremos. Si la mente humana parece no tener límites, ¿por qué cometeríamos el  despiste de crearlos de la nada? Hasta el entramado de la realidad física se ha  suspendido en un gran interrogante en estos últimos tiempos.</p>
<p>Por eso abogo por un aullido amplio de  voces que se levanten desde el arte: el arte de todos los días; el que se  esconde y se revela en todos los rincones, el doméstico, el más simple (y el  más complejo), el que debemos reaprender a rescatar de la miseria catalogadora.  Pensar en jerarquías resulta una cuestión un poco triste y, también, fútil. <em>Mostrarnos </em>al otro, <em>indicarnos </em>al otro debería ser una tarea nacida a partir de  la constante búsqueda de los instantes, de los pequeños momentos, domésticos,  de todos los días. Y si el arte, como dice Wilder, es confesión, encontrémosla  en todas partes y confesemos.</p>
