<p>La mayoría  del tiempo me lo paso dudando. Comienzo el día dudando sobre lo que soñé y,  cuando el insomnio ya es remordimiento, dudo entre leer o bajar a la heladera a  comer queso. La duda es una hermana boba (no sé si mayor o menor) que me tironea  de la correa día y noche.</p>
<p>Ayer  me vi obligado a convencerla de que teníamos que ir al cumpleaños de la hija de  mi mejor amigo. Al principio se negó, pero ante la insistencia –de mi amigo–  partimos hacia la calle 14 de Julio, en Villa Ortúzar. El viaje en subte fue un  martirio, cualquier cosa que la hermana haga a regañadientes se transforma en  un fusilamiento intelectual.</p>
<p>Dudé  entre caminar el camino del cementerio o el de la vía, con la ilusión de  perderme, pero tres globos violetas y dos rojos pegados con cinta en un portón  de madera me desinflaron la coartada. Toqué timbre y al abrir la puerta, era la  foto de una pesadilla recurrente. Caminé por un pasillo bastante ancho, donde repartí  las sonrisas que pude y algún saludo automático que se repitió un par de veces.  Por una hendija entre cochecitos 4 x 4 y bandejas con alfajorcitos de maicena,  divisé mi amarra para capear la tormenta social, la última plaza libre de un sillón  de tres cuerpos. Como era del lado del apoyabrazos y contra una pared, me  protegía del ejército infante y cubría el flanco derecho de cualquier cuestionario  acerca de mi eterno estado de soltería.</p>
<p>Apuramos  el último paso y, desde aquel rincón, entre la chocotorta y el café, armamos el  panóptico ideal para resistir, según mis cálculos más optimistas, al menos dos  horas. </p>
<p>Intenté  en vano permanecer neutral, pero tantas cornetas y guirnaldas eran cocaína para  mi indecisa compañera. Las mujeres, por un lado, hablaban al mismo tiempo de  temas recurrentes. ¿Se ponen de acuerdo en el temario cíclico –niñera, obra  social, jardín de infantes–? ¿Cuál habla y cuál escucha cuando hablan todas a  la vez? Pensé que, quizás, cada tanto hubiera un intervalo de descanso en el  que respiran y ordenan la información antes de empezar de nuevo. Los padres se atrincheran  alejados en tríos o pares dobles. No hablan tanto, o más bien se alternan entre  hablar y asentir con gesto resignado en el sentido inverso de las agujas de la  felicidad. No pude escuchar bien porque hablan en una frecuencia inferior a la  femenina, pero por la gravedad del talante supongo que política, la muerte del  sexo o alguna otra crisis dominaban el temario.</p>
<p>El  mundo de los niños nos resultó mucho más difícil de codificar. Casi no tenemos  experiencia en el asunto y como no manejan los rituales de la cortesía es  difícil indagarlos. ¿Dónde aprenden esas canciones de intérpretes que ni sé quiénes  son? ¿Cómo recuerdan las letras y, sobre todo, por qué las cantan a los gritos?  ¿Este mismo infierno se repite en cada hogar día tras día? ¿Será que el antídoto  contra la duda marital es el ruido constante? ¿Cuánto cuesta organizar esta  jodita? ¿Y la ropa canchera de estos enanos? ¿Y los juguetes? El que regala  juguetes más caros, ¿se gana el favor de los nenes o el de sus padres?</p>
<p>¿Cómo  sostienen estas parejas la idea de verse las caras para siempre? ¿Sueñan  despiertos con la luz al final del túnel? ¿Cuando sus hijos sean grandes y  ellos jubilados? ¿O será que la ley de lo urgente disuelve toda duda? ¿Dudan  los demás? Me vi en un espejo y pensé que mientras yo titubeo, a los demás se  le caen certezas como a mí se me cae el pelo.</p>
<p>Cuando  me quise acordar mis dudas ya habían tejido una red de la cual no sabía cómo  salir y empecé a hundirme en las incertidumbres más profundas. Los envidié a  todos, por su coraje, su inconsciencia o lo que sea que los anima. Y entonces me  sentí malo. Muy mala persona. </p>
<p>Y  no me gustó nada, porque a nadie le gusta saberse malo, y me esforcé por  fantasear ideas positivas para acallar los caprichos de mi hermana. Como una  rebeldía para invertir la carga. Me imaginé que podía ser sociable, que tenía  muchos amigos en todas partes del mundo. Que no me daba pereza llamar por teléfono  a mi madre o invitar a comer a mis vecinos, para estrechar los lazos. Me  inventé que no quería salir corriendo para volver a casa, a mis libros, a la  comida en la cama mirando televisión, volver a mi rabia, a mi odio, mi  frustración, mi desasosiego, mi página en blanco, mi remordimiento, mi  insomnio. Y si hacía un esfuerzo más podía imaginar que ser pelado no es tan  malo y que cumplir cuarenta puede ser un momento muy feliz.</p>
<p>A  pesar de que me costaba creerlo, me ilusioné y se ve que lo hice bien porque me  encontré con que el sol había caído, y que quedaba poca gente. Con un optimismo  creciente, busqué mi abrigo, agradecí, saludé y me fui. Pude sentir en el cruce  de miradas con mi amigo un alivio cómplice.</p>
<p>Caminé  en silencio para no despertar a mi hermana y seguí con mi ejercicio para dejar  de ser malo. </p>
<p>Fantaseé  con que puedo ser feliz con lo que la vida me dio, que no envidio el fútbol  brasileño y que no deseo que River vuelva a la B. Bajé a saltitos la  escalera del subte mientras imaginaba que me apasiona la música clásica, que  puedo pasarme la tarde entera tirado en el sillón escuchando un disco de jazz  (o dos, no tengo idea de cuánto duran) y que podía mantener la cocina limpia y  la ropa en el placard.</p>
<p>Me  senté en el asiento de felpa sintética roja, y mi castillo de bondad pareció  temblar cuando arrancó el coche. Hice un esfuerzo y volví al tema de la sociabilidad,  que era por donde había empezado. Repetí que no tenía por qué aburrirme en  compañía de los demás ni volver a preguntarme &ldquo;qué carajo hago yo acá&rdquo;. Mi  hermana parecía espabilar para interrumpirme, pero antes de que hablara la  primereé. </p>
<p>–Nos  tenemos que dejar de renegar con la vida.</p>
<p>–¿Qué  decís? –me resopló.</p>
<p>–Eso,  que hay que ser bueno, que la ironía no lleva a nada. Hay que ser buena gente.</p>
<p>Ácida  como una pila alcalina, me contestó:</p>
<p>–No  existe la &ldquo;gente buena&rdquo;, cuando lo clavaron a Jesús se acabó eso. Pavote.</p>
<p>–No  me refiero al sentido idiota de &ldquo;gente buena&rdquo;.</p>
<p>–¿Entonces,  genio de la autoayuda? –me dijo con los ojos cerrados.</p>
<p>–No  sé, quizás un concepto nuevo, uno que no se haya inventado todavía –le dije  entusiasmado.</p>
<p>–Tenés  más dudas que yo. Despertame en Congreso –dijo. Bostezó y se acomodó para  seguir durmiendo.</p>
<p>Casi  caigo nocaut, pero tomé impulso contra las sogas y contraataqué pensando que  acaso, para ser bueno, haya que ser un poco malo. Un poco yo, y un poco ella, especulé.</p>
<p>No  lo sé porque no creo que yo sea bueno del todo, pero tampoco tan malo. Pensándolo  mejor, hasta los más malos son en el fondo un poco buenos, los domingos, o en Navidad  quizás.</p>
<p>Salí  de estas cavilaciones cuando noté que un señor en jogging, sentado al lado mío,  me veía gesticular en silencio. Me dio tanta vergüenza que mi hermana se  despertó de golpe y me arrasó con una estampida de pensamientos horribles sobre  todo el mundo (y también sobre mí mismo).</p>
<p>Faltaban  dos paradas para llegar a dondequiera que me llevaran esos túneles de ideas,  cuando el hombre del jogging me preguntó si el coche iba para el centro. Con  algo de pena le dije que iba en la dirección contraria. El tipo se quedó en  silencio unos segundos y al final me dijo:</p>
<p>–Bueno,  qué importa. Llego a la terminal y vuelvo.</p>
<p>Quedé  congelado por la simpleza con que tomó la novedad y supe que ahí había algo de sabiduría,  incluso de heroísmo.</p>
<p>Al  otro día me propuse viajar sin saber adónde, pero cuando quise sacar el boleto,  mi hermana se adelantó y compró boletos de ida y vuelta para los dos.</p>
<p>No  es fácil ser bueno.</p>
