<p>Cuando en <a href="http://bit.ly/Qdwrn8" style="color:#c1272e">el  número dedicado al revólver</a> hablamos de la mítica Chaka Khan, se nos  ocurrió enfrentarla a la bastante joven y no menos orgullosa <strong>Janelle Monáe</strong>. Y  lo hacíamos con cierto dejo de petulancia, pues si aquella cosechó Grammys y  conquistó pistas de baile, la recién llegada apenas si debutaba en esto de los  LP. Ahora, Monáe se celebra a sí misma con un segundo disco, <em>The electric lady</em>, que es cosa única y a  la vez, continuación de lo anterior. En él, de la mano de cachorros como Erykah  Badu, Esperanza Spalding o su &ldquo;padrino&rdquo; Prince, promete seguir avanzándonos el  futuro a golpe de ritmos de funk. Alabadas sean las androides.</p>
<iframe width="350" height="197"  src="//www.youtube.com/embed/tEddixS-UoU" frameborder="0" allowfullscreen style="margin-left:175px;"></iframe>
<p>
<p>&nbsp;</p>
<p><a href="http://bit.ly/X9BWZa" style="color:#c1272e">Algunos números  atrás</a> recogimos la aventura de <strong>Bunbury</strong> por el cancionero popular  latinoamericano. Confesábamos, no sin cierta desazón, que aquel <em>Licenciado Cantinas</em> nos había dejado un  poco igual que antes de entrar al bar, despojado el oyente de la pluma original  del zaragozano y obligado a servirse de canciones que, bien o mal, no eran  originales. El anuncio del próximo lanzamiento de <em>Palosanto</em> nos devuelve el alma al cuerpo. Las ya clásicas quince  canciones (estas sí de su autoría), un disco dividido en dos partes y la  promesa de un sonido &ldquo;mezcla de muchas cosas&rdquo; nos invita desde el vamos a  abrirnos cualquier botella de algo.</p>
<iframe width="350" height="197"  src="//www.youtube.com/embed/TrBkmupwcQk?list=PL98D87573ECD61E72" frameborder="0" allowfullscreen style="margin-left:175px;"></iframe>
<p>&nbsp;</p>
<p>Otro que promete adornar la temporada con  nuevo trabajo discográfico es ese ínclito neoyorquino conocido como <strong>Moby</strong>. Dos  años después del lanzamiento de <em>Destroyed</em>,  <strong>Moby</strong> tiene cocinado su <em>Innocents</em>, que  según sus palabras es uno de los mejores de su trayectoria. La visita del grave  Mark Lanegan y el concurso del productor de Madonna y Muse dejan el anuncio de  este disco equidistante entre las aguas del riesgo y lo ya consabido. Lo cual,  en manos de <strong>Moby</strong>, no puede sino ser sinónimo de éxito comercial. Preparen sus arpones.</p>
<iframe width="350" height="197"  src="//www.youtube.com/embed/4SO0qSfxqyk" frameborder="0" allowfullscreen style="margin-left:175px;"></iframe>
<p>&nbsp;</p>