<p>Los momentos de la historia del jazz pueden ser los mojones  de la historia de la sociedad estadounidense y de cómo los norteamericanos  blancos se relacionaron (y se relacionan) con los norteamericanos negros. Desde  los inicios en los que el rechazo a esta música de clara impronta afroamericana  era liso y llano, pasando por la aceptación y la admiración, sin perder nunca  la desconfianza y el recelo con aquellos que desde el avant-garde metieron el  dedo de la subversión de las formas en las llagas del &ldquo;buen gusto&rdquo;. <strong>Black Music – Free Jazz y conciencia negra  – 1959-1967</strong>, la recopilación de textos de LeRoi Jones editada por Caja  Negra, tiene, en esa posible lectura, un gran valor. Lejos en el tiempo de las  figuras que suavizaron las fronteras sonoras del jazz en el swing, como Louis  Armstrong, Count Basie o Duke Ellington, se ubica en un momento en el tiempo en  que ya estaba consolidada la vanguardia de los grandes titanes del bebop y el  hardbop (Dizzie Gillespie, Charlie Parker, John Coltrane, Miles Davis,  Thelonious Monk, Sonny Rollins ed altri) y el surgimiento de lo que el poeta,  periodista y activista negro bautizó <em>avant-garde  del jazz</em>, hasta el bautizo llamada &ldquo;la nueva cosa&rdquo;. </p>
<p> No es un relato sobre la secuencia histórica sino una  bitácora de lo vivido en las entrañas mismas de esos años en los que Ornette  Coleman, Charlie Haden, Wayne Shorter, Archie Shepp, Billy Higgins, Cecil  Taylor e innumerables más, que en un momento de inflexión no se arrimaron a la <em>tercera corriente</em> que proponía un camino  mixturado con la música clásica y que pusieron el sonido al servicio de la  ruptura gramática del jazz, desordenando los tantos en función del baile y los  grandes públicos, para volver a la esencia más profunda de los clubes;  alineados, queriendo o no, con el surgimiento de los movimientos de los norteamericanos  negros en busca de una equidad social que, aún hoy, no han conseguido respecto  de sus pares blancos.</p>
<p style="margin-left: 50px; margin-right:50px">
  <em>Queríamos un cambio. Nos inspiraba la  realidad de la gente que luchaba por progresos reales en todo el mundo. Y por  la lucha que se había desatado en los Estados Unidos contra el racismo y la  opresión nacional luego del asesinato de Malcom X. Una de las razones por las  que dejé de escribir para la publicación más mainstream del jazz fue que en  1969 la Down Beat preguntó: &ldquo;¿Es LeRoi jones racista?&rdquo;, haciendo referencia,  exageradamente, debo suponer, al nacionalismo negro que envolvía mis palabras  luego de lo de Malcom.</em></p>
<p>
  La escritura urgente y lúcida de LeRoi Jones se constituye  en varias vías formales dentro de la compilación. Los <em>Apple Cores</em> que escribió para <em>Down  Beat </em>y <em>Wild Dog</em>; las <em>Presentaciones</em>, en las que se encarga de  perfilar a sujetos del porte de Wayne Shorter, Bobby Bradford, Cecil Taylor,  Don Cherry y Archie Shepp; las lúcidas y complejas críticas de discos; y  ensayos sueltos entre los que se destacan el breve <em>La oscura dama de los sonetos: Billie Holiday</em> y el inaugural <em>El jazz y la crítica blanca</em>, donde ya se  ven los brotes de las palabras sembradas por LeRoi Jones que marcan, desde el  primer párrafo, el rumbo esencial de su pluma: </p>
<p style="margin-left: 50px; margin-right:50px">
  <em>La mayoría de los críticos de jazz han sido americanos blancos,  mientras que los músicos más importantes, no. Esto puede parecerle a mucha  gente una realidad más o menos simple, o al menos una realidad perfectamente  explicable en términos de la historia social y cultural de la sociedad  norteamericana (…).<br />
  Como me dijo una vez un profesor de la Howard University cuando era estudiante:  &ldquo;¡Es increíble la cantidad de mal gusto que hay en el blues!&rdquo;. Pero es  justamente este &ldquo;mal gusto&rdquo; del que hablaba este señor lo que ha salvado a la  mejor música negra de patinar de manera estéril en la caja de resonancia de la  cultura media norteamericana. </em></p>
<p>
  <strong>Black Music</strong> es un  libro indispensable para sumergirse en los años agitados en los que el <em>free jazz</em>, con todas las resonancias que  tiene la palabra <em>free</em> en los  habitantes del gran hermano del norte, abría una brecha estética e ideológica  en la superficie del arte contemporáneo; de primera mano y en palabras de uno  de los activistas negros más filosos. Aquel que tras el asesinato de Malcom X  se convirtió a la <em>Nación del Islam</em>, y  trocó su nombre por el de Amiri Baraka. El mismo que acuñó el concepto de la <em>americanización</em> de la música negra desde  el momento en que los norteamericanos blancos aprendieron a tocarla. El  provocador que en 2009, cinco años antes de su muerte, revisó la edición de  estos textos y concluyó: </p>
<p style="margin-left: 50px; margin-right:50px">
  <em>A pesar de la matriz cultural reaccionaria  que ocultó gran parte de esta música durante los años de Reagan y Bush, y que  produjo la hegemonía del retraso cultural y artístico del jazz fusión y de  &ldquo;Kenny Elevator&rdquo;, del rock superficial y del rap más vacío –y que hizo que muchas  veces, incluso en Nueva York, pasáramos semanas enteras sin ver a ninguno de  los nuevos– hay en estos días algunos signos de que otra nueva ola viene en  camino.</em></p>
