<p>Nuestra pequeña colaboradora, se trepó a la biblioteca y eligió estos títulos para recomendar a sus pares. Empecinada en llenar esta página con sus propias palabras y cuestionando los decires que no reflejan lo que ha experimentado en sus lecturas, nos pusimos manos a la obra y conseguimos este resultado con el que dice haber quedado satisfecha.<br />
</p>
<p><span class="image_cen3"><img src="images/501.jpg"></span><strong>La casa del árbol </strong>y<strong> La isla</strong>, de Marije y Ronald Tolman<br />
  Adriana Hidalgo - Pípala - 2014<br />
  <br />
  Libros sin texto, producción de padre e hija Tolman, son ideales para que los niños puedan imaginar las historias que allí se cuentan. En secuencias de dibujos que dicen por sí solos, la historia se va armando a partir de las mezclas de las ilustraciones. Un oso polar es el protagonista de distintas aventuras en las que participan muchos animales, incluyendo a un oso perezoso, pavos reales, flamencos, zorros (uno de ellos toca el violín), pingüinos, rinocerontes, cigüeñas, osos panda, hipopótamos, búhos y hasta un extinto dodo. En uno de estos libros, no revelaremos en cual, el oso polar encuentra una osa parda que, según nuestra pequeña colaboradora, le resulta muy buena compañía.</p>
<p>&nbsp;</p>
<p><span class="image_cen3"><img src="images/502.jpg"></span><strong>Julián en el espejo</strong>, de Félix Bruzzone - Ilustrado por Pablo Derka<br />
  Adriana Hidalgo - Pípala - 2014</p>
<p>Este libro cuenta la historia de un niño, su mamá, su papá, su perro y un espejo mágico. Una tarde, cuando los papás se van de su casa,  Julián descubre  el espejo de la bisabuela en el patio, tapado por una manta verde. Cuando se mira ve a un niño igual a él pero que tiene su propia vida en el espejo. Julián rebota la pelota contra el espejo y el niño se la devuelve, cosa que puso muy celoso a su perro. En un momento la pelota no regresa y Julián decide entrar al espejo a buscarla...  ¿Podrá salir? Esa pregunta, como otras que los pequeños lectores se harán cuando lean este libro, le agrega suspenso a este lindo cuento de Félix Bruzzone.</p>
<p>&nbsp;</p>
<p><span class="image_cen3"><img src="images/503.jpg"></span><strong>El pájaro del alma</strong>, de Mijal Snunit - Ilustrado por Francisco Nava Bouchain<br />
  Fondo de Cultura Económica - 2013</p>
<p>El cuento de Mijal Snunit transcurre en un lugar muy especial: el alma. Allí habita un pájaro que tiene todos nuestros sentimientos guardados en muchos cajoncitos. Nuestro pájaro del alma puede elegir, entonces, qué sentimientos liberar: penas, amores, sonidos, voces, alegrías y tristezas; envidias y esperanzas. Así, cada persona es distinta pues el pájaro de su alma es diferente. Escrito con la fuerza y la delicadeza de los poemas, este libro recopila una extensa lista de los cajones que cada pájaro puede abrir, obediente o no; dejando al final de su lectura la sensación conmovedora de las más lindas palabras que lo habitan.</p>