<p>El mundo musical de <strong>Andrew Bird</strong> es tan amplio como diverso,  sin que ello signifique perder el sello, la marca en el orillo que nos hace dar  cuenta de estar escuchando uno de sus discos; ficha que caerá track antes,  track después, una vez que uno se haya sumergido en esas aguas. Aunque bien  pensada, la metáfora no aplica pues si hay algo alejado de lo acuático es la  música de este norteamericano oriundo de la ciudad Chicago: un mix de música  folk, rock &amp; roll y swing que cada dos por tres pone al frente un sonido  con cadencia de trote; apoyado en su particular ejecución del violín,  instrumento que lo acompaña desde su más tierna infancia, con y sin arco, que  puede tener aires del Lejano Oeste tanto como rasgos de una sonoridad única,  pizzicato de por medio.<br />
  <br />
  Contando sus discos en solitario, sus colaboraciones con  otras bandas y los que compartió con su proyecto paralelo Bowl of Fire, hasta  la actualidad <strong>Andrew Bird</strong> ha dejado en su historia más de una docena de discos. Todos  ellos, con sus particularidades y su apuesta estética, con la irregularidad que  todo tránsito supone, son no sólo piezas que pueden ser disfrutadas sino que  son parte de un todo que se arma con las escuchas sucesivas, en serie o a los  saltos como en la rayuela.<br />
  <br />
  A fines del mes de febrero de este año, contactamos con <strong>Bird</strong> quien nos respondió algunas preguntas que, impulsadas por la curiosidad que nos  produjeron sus distintos discos,  le  hicimos llegar vía mail, gracias a la atenta gestión de Andrea Troolin y Justin  Becker. Y para después de la entrevista, a modo de bonus track, van un par de  temas seleccionados de los discos que, creemos, son a la vez imperdibles y  posibles puerta de entrada a la obra de un músico que por muchas razones se  destaca de la mass media musical.</p>
<p><strong>¿Cuáles  son los paisajes y los sonidos de tu infancia que encontrás en tu música?</strong><br />
<strong></strong>Como queda muy bien demostrado en las bandas sonoras, la música puede influir sobre nuestra forma de ver; así como el ambiente, el entorno puede influir sobre la música que escuchamos. Puede hacer que el tiempo  transcurra más despacio, lo cual es un muy buen truco. Aprendí esto cuando  tenía 14 años y estaba sentado en una azotea en Rocky Mountains, escuchando un  trío de piano de Schubert mientras veía las hojas de Aspen brillar en el  viento.</p>
<p><strong>¿Qué música  escuchabas cuando eras niño y qué escuchás ahora?</strong><br />
<strong></strong>Mi madre escuchaba música clásica y a mi padre le gustaba la música country y  la del Lejano Oeste. Ahora escucho mucha música del África Oriental, desde Mali  hasta Angola. Country blues, Townes Van Zandt, John Prine, The Staples Singers  y demás…</p>
<p><strong>¿Cuál  fue tu educación musical, más allá de estudiar: influencias, gustos, encuentros  inesperados, sorpresas musicales…?</strong><br />
 Lleva bastante tiempo encontrar buenas cosas. Exploré mucho las bateas de  discos, sin ninguna guía, y solamente escuchaba… Mis profesores solían decirme:  &ldquo;Necesitás tocar escalas y practicar 6 horas por día&rdquo;, pero mis mayores saltos  los hice agarrando el instrumento y escuchando, con una saludable cantidad de  silencio también. Así es como todo se filtra en tus huesos.</p>
<p> <strong>Estudiaste violín desde los 4 años, ¿cuándo te lo apropiaste realmente?</strong><br />
 Alrededor de los 15 años cuando todo es romántico y se torna cuestión de vida o  muerte. Pero lo hice completamente mío a los 26, cuando dejé de escuchar únicamente  para empezar a escribir.</p>
<p><strong>Luego  llegaron otros instrumentos. ¿Cuál es el que más te sorprendió?</strong><br />
<strong></strong>Soy autodidacta en la guitarra. Es simplemente un instrumento intrínsecamente  sexy. A veces, cuando toco un acorde, siento estar tocando una sartén al rojo  vivo. Un sacudón que atraviesa mi cuerpo entero.</p>
<p><strong>Tu  música es ecléctica y ha mutado con el tiempo. ¿Qué elementos de tus primeras  composiciones persisten en las actuales?</strong><br />
   Mis primeros discos fueron locamente ambiciosos y sin descanso; y al día de hoy  no me gusta mucho descansar en un mismo lugar por mucho tiempo. Supongo que ahora  estoy más enfocado y también más paciente. No todas las canciones tienen que  reinventar la rueda. Todas mis canciones son verdaderas instantáneas de mi modo  de pensar. Tangencial y plenamente; fatalista y esperanzado. Por sobre todo,  espero que sean divertidas. Hay una seria falta de humor en la mayoría de la  música.</p>
<p><strong>¿Qué  tipos de discos podemos esperar en el futuro cercano?</strong><br />
   He estado un rato andando por un período antiguo en los últimos discos pero ya  me he rascado ese picor y ahora estoy listo para hacer un nuevo tipo de  registro musical. Excéntrico y brutal, espero.</p>
<p><strong>¿Qué  pensás acerca del mundo de los negocios musicales en la era de Internet y de la  libre circulación de la música entre los oyentes?</strong><br />
Mi negocio estuvo siempre enfocado en hacer shows en vivo porque es algo  absolutamente concreto. Nunca conté con la venta de discos para pagar mi  alquiler.  El quid de la cuestión es que hay mucha menos circulación de dinero en la  música y que los músicos se llevan la peor parte. Los acuerdos sobre <em>streaming</em> que se hicieron en las  trastiendas son un muy mal negocio. Los músicos  ya no pueden culpar más a los grandes sellos de oprimirlos en su creatividad.  Aquellos días parecen lujosos comparados con los de ahora. Los músicos tienen  que ser más inteligentes. Los éxitos de la noche a la mañana son un cuento de  hadas fabricado por los programas de televisión. La cultura real todavía está  en las calles.</p>


<?
	include('birdPlayer.php');
?>
