<p>El estudio de Sami Abadi está en un piso 17 y desde la ventana  se ve un cielo despejado que ilumina el barrio de Balvanera. Al entrar se pueden  ver muchos instrumentos musicales y el metal de los equipos en contraste con ese  fondo celeste intenso. El cielo también parece haberse metido en su música  usando como puerta de entrada los sintetizadores, los secuenciadores y los multiefectos  que ahora baña de luz. Su último disco se llama <em>La espuma del amanecer hace estallar lentamente su polen de fuego</em> y Abadi  explica por qué eligió ese título: &ldquo;Quise contar lo que veo en la  música, nubes explotando, por eso lo de la espuma del amanecer. Nubes  coloreadas de rojo a la mañana. Es lo que imaginé y está expresado como en una  poesía japonesa&rdquo;. El disco se editó en cassette, el año pasado, pero este año  saldrá la edición digital.</p>
<p>  Para describir el universo del multiinstrumentista hay que  mencionar al <em>ambient</em>, la música electrónica, <em>loops</em> en tiempo real, música clásica,  étnica, improvisación, instrumentos de juguete <br />
  y experimentación. &ldquo;Empecé probando con pedales, enchufando el violín a un  pedal de guitarra, estaban ahí las cosas yo solamente las junté —explica Abadi—.<em> A</em>hí está la influencia de Robert Fripp  y Brian Eno que trabajaron juntos. Vieron que el pedal no era un condimento  sino que también era el instrumento; un sistema formado por el violín, en mi  caso, y la cadena de procesamiento&rdquo;. </p>
<p>  La variedad de elementos que tiene la música de Sami Abadi ha  multiplicado sus posibilidades artísticas desde que salió su primer disco, <em>Lejos o leve,</em> en 1998. Compuso música  para teatro, cine, danza, colaboró sumando su violín al trabajo de DJ de <em>house</em> y <em>drum´n´bass</em>, fue uno de los fundadores de  Haiku e integra la banda Ultratango. También colaboró con Babasónicos, Daniel  Melero, Kabusacki, Gaby Kerpel y Divididos, entre otros.</p>
<p><strong>¿Por qué elegís la música electrónica  experimental y no la canción tradicional?</strong><br />
  Aunque todavía no edité un disco de canciones, tengo varias  que están esperando su día para ser editadas. No sería raro que mi disco tuviera  una combinación donde lo experimental entra en la canción con detalles  orquestales, electrónicos y algunas cosas contemporáneas. No lo hice todavía  porque tengo cierto compromiso con la poética del sonido, donde no hay una  palabra que te dice para dónde tenés que imaginar. El sonido te condiciona en  una dirección pero no hay una palabra que ancle. Tengo un compromiso con la  poética del sonido.</p>
<p><strong>¿Cómo creés que van a  ir evolucionando los shows de música electrónica en vivo ahora que hay tantas  herramientas tecnológicas nuevas? Me refiero, por ejemplo, a elementos como los  guantes </strong><strong>Mi.Mu que  producen sonidos a partir de gestos. </strong><br />
  Herramientas han aparecido muchas, sin embargo la cuestión clave  sigue siendo dónde está el artista que con eso puede hacer algo valioso. La  pregunta es: ¿Y ahora qué hacemos con esto? El gran tema de la música  electrónica en el escenario es lo performático. Todo lo que se maneja desde una  computadora carece de atractivo visual. El chiste es &ldquo;parece que estás enviando  mails&rdquo;. Entonces el gran desafío de la música electrónica en el escenario es  poder contarle a la gente qué es lo que se está ejecutando, ahí es donde estas  herramientas son buenísimas. </p>
<p><strong>¿Qué diferencia  encontrás entre tocar solo y tocar en una banda? </strong><br />
  Tocar solo es como pintar un lienzo, como si tuviera todos  los colores y pinceles. Los instrumentos electrónicos tienen una dimensión con  tantas posibilidades que termino siendo como una pequeña orquesta o, por lo  menos, juego a hacerlo. Es bueno también para crear música en el momento porque  uno sabe hasta dónde va a llegar, aunque también tengo un dúo donde hago música  en el momento con el pianista Leo Clerici. <strong></strong></p>
<p><strong>¿Cuáles son tus  proyectos actuales?</strong><br />
  Estoy trabajando en dos piezas nuevas que van a ir en dos  compilados del sello Fuga. Y el 27 de marzo me presento en Oro Club Arte, a las  21:00 h (sólo con reservas o enviando un mensaje a <a href="mailto:oroclubdearte@hotmail.com">oroclubdearte@hotmail.com</a>). </p>
