<p>¿<em>Midnight Marauders</em> o <em>The Low End Theory</em>? Esa pregunta parece  resonar en la cabeza de los oyentes del grupo neoyorquino de hip hop  alternativo A Tribe Called Quest (ATCQ). Y finalmente termina siendo una  pregunta bastante legítima. Si bien ATCQ ha sido foco de atención durante el período  de los tardíos ochenta y los tempranos noventa, terminó estableciendo un legado  que sigue haciendo eco en la historia del movimiento musical del hip hop. </p>
<p>  El  concepto es simple pero ingenioso. Contrario a las corrientes más comerciales y  de la rivalidad entre la costa este (<em>eastside</em>)  y la costa oeste (<em>westside</em>), el grupo  decidió tomar raíces provenientes de otras inspiraciones, logrando una fusión  de géneros junto a una calidad de sonido y producción muy particular que  generaría un efecto dominó, desencadenando así incontables inspiraciones que  surgirían tanto en tiempos contemporáneos como en el recorrido de los años que  formaron lo que ahora llamaríamos el hip hop moderno. El rapero Q-Tip encabezaría  la formación junto a Phife Dawg, Ali Shaheed Muhammad y Jerobi White, que en  una sincronía de ideas harían una elección musical que los transformaría en una  banda de culto. </p>
<p>  ATCQ  mezcla los elementos del hip hop más clásico y dobla su apuesta con los incontables <em>samples</em> e inspiraciones que toman del  jazz, R&amp;B, blues, soul, entre otros géneros, creando una fusión  revolucionaria que daría un gusto picante a sus canciones y agregarían una  sutileza muy específica a sus sonidos. No es solo la idea, sino su ejecución,  teniendo en sus canciones <em>samples</em> de  artistas como Weldon Irivine, Raphael Saadiq, Freddie Hubbard, Ziggy Modeliste,  entre muchos otros. Fusionado con la producción de sus álbumes encabezada por  Q-Tip, aclamado por varios conocedores del género como uno de los mejores  productores de hip hop que haya habido.</p>
<p>  Teniendo  en cuenta el contexto de la banda podemos volver a la pregunta que abrió este  texto. Tratar de responderla es una simple cuestión de gusto y apreciación,  pero como dije antes es necesario mencionarla como correcta, ya que ambos  discos son claramente los exponentes mayores a los cuales llegó el grupo.  Mostrando un contenido más sólido y más seductor que sus previas y posteriores  obras. Si bien la carrera discográfica de la banda no es extensa, es posible  apreciar una gama de distintos estilos y la constante búsqueda de un sonido  fresco y original, que no está ligado a sus obras anteriores.</p>
<p>  Logrando  crear una burbuja a su alrededor, ATCQ, se mantuvo independiente del movimiento  musical en ese momento contemporáneo, concentrándose en la creación de su  propio contenido individual; involucrando solamente a varios exponentes  artísticos que seguían activos en la época.</p>
<p>  La  paleta de las voces que colaboran en cada canción da un toque refrescante a  cada una de ellas, teniendo una rotativa entre Q-Tip y Phife Dawg, agregando  algunos invitados a la mezcla que crearían algunas de las canciones más  pegadizas del hip hop de los noventa. Con un estilo certero y con la  composición musical que introduce varias capas de sonidos para sumar un cierto  ingenio al género, ATCQ es y será por largo tiempo una de esas bandas que  cualquier amante del hip hop debería escuchar y una de los mejores puntos de  incursión para explorar el género desde un punto de vista más artístico y con más  carga musical.</p>
<p>&nbsp;</p>
<?

	include('ATCQPlayer.php');

?>
