<p>El viaje es lo que se escribe de él. Las imágenes, los  sonidos, aromas, lo que queda en el tamiz de la memoria cuando el agua de lo  vivido ha pasado por el colador del tiempo. Podría cualquier lector remontarse  hasta los inicios mismos de la literatura para encontrar en sus piedras basales  la travesía que se convierte en viaje; evocando el primigenio, el fundacional,  aquel que hizo del homínido un hombre; la expansión en el mundo, las conquistas  de tierras lejanas; siglos de acumulación de saberes, pruebas y efectos, fallos  fatales y saltos tecnológicos. Detrás de las peripecias épicas de Gilgamesh, en  el poema que lo narra, el más antiguo del que se tenga registro, el héroe  abreva en la sabiduría de Utnapishtim quien sobrevivió al diluvio mesopotámico;  el viaje dentro del viaje. Lejos de la epopeya pero atravesados por lo que  hemos dado en llamar la experiencia, lo que modifica al sujeto, los viajes  traducidos a texto de Hebe Uhart y Esteban López Brusa aportan perspectivas muy  distintas que confluyen en la palabra que dice sobre aquello que alguna vez fue  presente y que se renueva al momento de ser escrita, para volver a renovarse en  cada lectura.</p>

<p> &nbsp; </p>

<p><span class="image_cen2"><img src="images/101.jpg"></span><strong>De la Patagonia a México</strong><br />
  Hebe Uhart<br />
  Adriana Hidalgo ¬ 2015<br />
  Las crónicas de viaje de Hebe Uhart se inscriben en el borde  de lo documental y lo ficcional. Lo que registra de lo que le sucede en donde  se encuentre tiene una respiración personal que hacen de las crónicas textos  que son casi cuentos; sumado a los ribetes de lo cotidiano, el inesperado salto  del relato de terceros, las epifanías. Sean lugares diminutos en los que  escarbar con el ojo preciso los convierte en un mundo que se abre frente al  lector; sean extensiones abiertas, inabarcables de los aires de una provincia;  ciudades o pueblos; la inquieta curiosidad de la autora estará dispuesta, desde  la mesa de un café o tras el humo azulado del cigarrillo que pide ser fumado, a  recuperar en decires lo que acontezca en ese fragmento de tiempo. Diversa como  los lugares que narra es la topología de estas crónicas en las que la  preferencia de la autora por los pueblos pequeños, como los de su propio  origen, resulta en textos compactos y jugosos, con una profundidad muchas veces  disfrazada de sencillez. A gusto de quien escribe, ese decir tiene su punto más  alto en el entramado entre literatura, realidad y ficción de <em>General Villegas</em>, el pueblo de Manuel  Puig. La particular naturaleza narrativa del escritor y su pueblo, el infierno  grande de haber narrado la intimidad de las familias que aún hoy viven allí, el  sacar los trapitos al sol, son un caldo de cultivo que Uhart aprovecha de punta  a punta, hablando con taxistas o haciendo el recorrido turístico armado  alrededor del más célebre personaje del lugar; yendo más allá, armando el  presente del lugar que no puede evitar vivir en su propio pasado. Un collage  apropiado, profundo, denso y ligero. Bariloche, Almagro, Corrientes, Asunción  del Paraguay o el DF mexicano son algunos de los puntos geográficos a descubrir  a través de estas crónicas; una buena excusa para poder proyectar palabras  propias cuando el deseo del lector de conocer esos paisajes coincide con la  pluma literaria de Hebe Uhart.</p>
  
<p> &nbsp; </p>
<p><span class="image_cen2"><img src="images/102.jpg"></span><strong>Guanaco</strong><br />
  Esteban López Brusa<br />
  Mardulce ¬ 2015<br />
  El noroeste argentino tiene una identidad tan potente que resulta  difícil narrarlo si, de algún modo, no se lo lleva muy profundamente consigo.  Sea por pertenencia desde el nacimiento, sea por adopción del terruño, sea por  uno de esos viajes que se instalan para siempre en la vida del viajero. Todas  posibilidades que el escritor platense usa para tejer una novela en la que el  desierto de la construcción literaria linda con la exuberancia –no con excesos–  de la palabra. El foco inicial de <strong>Guanaco</strong> está puesto en la apertura del <em>Huemes</em>,  un almacén devenido en bar que articula la vida de las amigas que lo  (re)fundaron; vidas que abren el arco narrativo en caminos propios y vuelven a  estrecharse en el nudo de la amistad, de compartir un lugar común, un proyecto;  relaciones donde borrascas y tormentas también hacen lo suyo. La Quebrada de  Humahuaca, sus colores, sus formas están omnipresentes, así como los guanacos,  su crianza y todas su cuestiones, el comercio ilegal de animales y, en  interesante resonancia, cierta disputa con los otros camélidos del lugar. Los  personajes se multiplican con los habitantes de Las Pirquitas y la coralidad,  la miríada de sucesos, crean una atmósfera que transmite una forma de sopor,  como los efluvios etílicos que sobrevuelan el aire. En algún momento, la novela  vira, más en su forma que en su esencia. Un cambio de perspectiva, el paso de la  voz del narrador omnisciente a la primera persona, inyectan en la novela la  dimensión de los viajes. El protagonista ya ha estado allí, muchos años ha, y  vuelve, en otras circunstancias, con otro bagaje a recorrer aquello que suponía  iba a saberle a pasado. La sorpresa será un acierto: la novedad está ahí más  que lo ya vivido. La precisión en las descripciones, los ritmos, los personajes  y sus modos de entender la vida, la moral, las costumbres nos dicen que López  Brusa también estuvo allí.</p>
