<p>Fue asesinado el 2 de noviembre de 1975. Ya han  pasado cuatro décadas y, sin embargo, su memoria continúa tibia, encendida. Si  tuviéramos que preguntarnos por lo que mantiene aún hechas brasa a sus cenizas,  no tendríamos sino que acudir a una de sus propias palabras recurrentes, la que  utilizó incluso en alguno de sus títulos: pasión. Y aunque causáramos todavía  la extrañeza de algún que otro extraviado en la tramoya de los géneros, esos  mismos a quienes, de vivir él, hoy, no ahorraría ninguno de aquellos urticantes  epigramas suyos con nombre y apellido, esa pasión encontró su fuego y su fondo  y su forma en la poesía.</p>
<p>Es verdad que el ensayo, la novela, el cine, la  polémica, la crítica, el panfleto, la ironía y la injuria fueron algunas de las  muchas apariencias que adoptó su insobornable pasión poética, pero ¿cuál de  esos textos-imágenes o imágenes-textos puede alcanzar, por ejemplo, la densidad  cabal, la grave hondura, la dolorosa belleza de sus indelebles versos &ldquo;A las campanas  de Orvieto&rdquo;?</p>
<p>No se negó a experiencia alguna, ni desechó ningún  combate. Heredero poco complaciente de una gran literatura y de una envidiable  conciencia civil, devolvió al mejor neorrealismo su contacto con las nuevas  asperezas en <em>Accatone</em> o <em>Mamma Roma</em>, despabiló a no pocos  clericales con su <em>Ruiseñor de la Iglesia</em><strong> </strong><em>Católica</em> pero también reintegró un profundo sentido místico y humano al mejor  cristianismo con <em>El Evangelio según San  Mateo</em>; supo recuperar la saludable rugosidad primitiva de los clásicos  griegos en su sabroso <em>Edipo Rey</em>,  teorizó siempre entre <em>Pasión e</em><strong> </strong><em>ideología</em>,  fue capaz de inquietar a un comunismo ya tan poco dogmático como el italiano  dialogando fecunda y libremente con <em>Las</em><strong> </strong><em>cenizas  de Gramsci</em>. No dejó insulto, ofensa o diatriba sin devolver. Y se sentía  fieramente orgulloso de que su propio rostro, de agudos planos cortados a pico  con sólida prestancia francamente popular, le diera un parecido con Sekú Turé,  entonces presidente de Guinea.</p>
<p>Vio la luz en Boloña, pero sus raíces estaban en el  viento. En el viento de Italia, que es África en el sur y Europa en el norte; en  el viento del cambio y del nomadismo con que obligaron a su infancia los  oficios de su padre. Nació en 1922, el año de <em>Trilce</em> y del modernismo brasileño. El año de <em>Ulises</em> y de <em>Tierra Baldía</em>,  el año de la muerte de Proust. Pero también el año que siguió a la represión  del Ejército Rojo contra los obreros revolucionarios de Kronstadt, o el año de la Marcha sobre Roma, aquella  caminata ostentosa que dio pie a los veinte años siniestros del fascismo. Su  estrella aparecía entonces indisolublemente ligada con la historia, vivida ya  no desde las bases sino desde el subsuelo, el humus mismo y a la vez fecundo  pero también contradictorio de una inestable y tornadiza frontera entre lo  proletario y lumpen, que conocería de primera agua al tener que volver a  &ldquo;adaptarse&rdquo;, en 1949, a  las violentas barriadas plebeyas de Roma, donde vuelve a envolverlo un  dialecto, esta vez urbano y de avería. Porque en su sangre venían bullendo los  jugos agridulces, macerados, fermentados, de la lengua friulana, heredada de su  madre, nacida en aquella Casarsa donde él también tuvo que refugiarse, en 1943,  durante la guerra.</p>
<p>Y ya desde entonces, desde 1940, antes aún de los  primeros pasos en una universidad, el joven Pasolini no sólo escribe en  friulano, sino que ésta es directamente la lengua de sus primeros libros, y  suya es la intentona de una <em>Academiuta da  Lenga Furlana</em>. Si alguno llega a preguntarse de qué se habla cuando alguien  hace referencia a la lengua materna, he aquí una respuesta. Y por eso la vida y  la obra de Pier Paolo Pasolini están indisolublemente ligadas con la poesía.  Mejor dicho, con esa encarnación de una lengua viva que es la poesía lograda.</p>
<p>Porque, a la vez, qué es lo que llaman un dialecto sino  la irrupción visceral, orgánica, no controlada ni regimentada, no socializada  administrativamente aún, de una comunidad sumergida junto con su lengua. Lo que  ello arrastra, hecho luego teoría, aunque en verso, claro, sigue y seguirá  siendo para Pasolini una verdad primaria, elemental, en el mejor sentido, tan  bellamente bárbara como sanamente fecunda: &ldquo;Todos juran ser puros: / puros en  la lengua... naturalmente: / señal de que está sucia el alma&rdquo;. Y también,  magníficamente: &ldquo;¡La Lengua  es oscura / no límpida -- y la   Razón es límpida, / no oscura!&rdquo;. Y más aún: &ldquo;Son infinitos  los dialectos, las jergas, / el pronunciar, porque es infinita / la forma de la  vida: / no hay que hacerlos callar, hay que poseerlos...&rdquo;.</p>
<p>Asesinado  en 1975, lo que mantiene vivas, todavía hoy, como decíamos, las cenizas de Pier  Paolo Pasolini es lo mismo que lo volvió ineludiblemente poeta: la conciencia  visceral, empática, de que la lengua es un organismo vivo, en combustión,  activo, que gasta y que consume, que vive y muere, hecho a la vez de  sublimaciones y detritus, pura y feroz materia nunca inerte, como la vida  misma, gran mar nutricio y a la vez devorador, matriz y forma inevitable de lo  humano, lengua viva en los hombres, de los hombres, por los hombres. </p>
<p>&nbsp;</p>
<p align="center"><strong>*</strong></p>
<p>&nbsp;</p>
<p>EL  CIELO TRANSPARENTA...</p>
<p>El cielo transparenta un  leve signo<br />
  sobre mí... Sólo es cándida  sombra,<br />
  una nube. (Reconozco esa  sombra,<br />
  la no dicha palabra... la  herida...<br />
  Ah, mi conciencia sola como  el cielo).<br />
  El henil y las losas me  devuelven<br />
  el claro azul de la luna en  los ojos.<br />
  ¿Quién me pone de frente con  mi vida?<br />
  y ya un aire celeste de lo  alto<br />
  ha alejado las nubes: ni una  sombra<br />
  en el cielo desnudo.</p>
<p>&nbsp;</p>
<p><strong>Pier Paolo Pasolini</strong></p>
<p>Traducción de Rodolfo Alonso</p>
<p>&nbsp;</p>
