<p>Un escritorio, una máquina de escribir sobre  él; el marco de una puerta que conecta dos espacios vacíos; un piso con paneles  que se articulan. Ante este escenario despojado e inquietante se sitúa el  espectador de <em>Cactus orquídea</em>, deseoso  por dejarse llevar y a la vez atento ante la resolución del oxímoron que plantea  el título de la tercera producción de El Ensamble Orgánico, escrita y dirigida  por Cecilia Meijide. Lo que no se tardará en descubrir es que el desenredo de  la madeja no se ofrece de forma lineal, pues la invitación es a situarse en las  entrañas de una obra poliédrica, donde un actor no es uno sino muchos, y a la  vez se convierten en tramoyistas que deambulan invisibles entre los decorados y  al mismo tiempo se incorporan con naturalidad a los recorridos actorales.</p>
<p>En consonancia con esta propuesta múltiple, el  tronco argumental de <em>Cactus orquídea</em> es en realidad un cúmulo de historias entrelazadas que se suceden prácticamente  sin solución de continuidad. Ello dota al espectáculo de una versatilidad que  no es sino la prolongación de una propuesta escenográfica sorprendente y que  constituye el hecho diferencial de una obra que se acerca al cosmos de los  desencuentros humanos con cierto tono humorístico, abrazado más a la ternura que  al desamparo.</p>
<p>Entre los hallazgos del texto destaca su  osadía a la hora de ejercer el intervencionismo que toda obra exige de su guion  y que a menudo queda empañada tras un ejercicio de &ldquo;sobredirección&rdquo;. No es el  caso. Los juegos entre la primera y la tercera personas, la corrección mutua a  la que se someten guionista y personajes, y varios y deliciosos juegos de  metalenguaje componen una suerte de rayuela que el espectador acaba recorriendo  a la vez que accede a su lógica interna. No obstante estos aciertos, el  conjunto argumental queda algo desleído por su empeño de demostrar la  universalidad de los valores del ser humano, un ejercicio transversal que puede  hacer fútiles las intenciones de algunos personajes por profundizar en sus  problemáticas. Todo ello encolumnado tras la metáfora del cactus orquídea, que  florece una única noche al año.</p>
<p>La valoración del espectáculo se completa con  un elenco convincente encabezado por Laia Duschatzky, bien secundada por Lucas  Avigliano, María Estanciero, Gastón Filgueira y Nacho Bozzolo. El paso de un  personaje a otro los obliga a mutar de forma permanente, sin que se trasluzcan  discontinuidades o registros forzados. Lo cual se produce también gracias a la  sólida dirección de Cecilia Meijide, quien se maneja con soltura y  profesionalidad en el siempre embravecido mar de las historias babélicas. </p>
<p>&nbsp;</p>



<?
	include('volykhine/index.php');
?>
