<p align="right"><em>Mal  que me pese, debo tener, o debo ambicionar tener, </em><br />
  <em>algo  de la violenta impunidad de Boogie.</em><br />
  Roberto Fontanarrosa</p>
<p>No es ninguna novedad: en &ldquo;Boogie, el Aceitoso&rdquo; se cuecen todos los  excesos, todas las aberraciones sociales contemporáneas: racista, homofóbico,  macho golpeador de mujeres, ultraderechista, mercenario, descorazonado, asesino  rabioso y de sangre fría, ex máquina de matar en nombre del Imperio Americano y  una extensa lista más. La pluma de Roberto Fontanarrosa encontró el punto justo  en el que el humor negro, tan negro como su toque policial, crea una particular  empatía en los lectores. Podría conjeturarse que inocula los virus de lo peor  del capitalismo y lo devuelve convertido en mueca; en un gesto de resistencia  minimal ante el avasallamiento económico y social de que los Boogie serían  capaces. </p>
<p>En 1972, cuando la revista <em>Hortensia</em> puso en circulación las primeras tiras de la serie, las implicancias sociales y  judiciales de algunas de las cuestiones enumeradas arriba distaban mucho de la  realidad de hoy. Mucha agua, mucho fuego, mucha lucha ha transitado la sociedad  para que los parámetros de la normalidad, la justicia social y equidad sean,  sino mucho mejores, el reconocimiento de algunos que durante décadas, acaso  siglos, lograron exasperar hasta el punto del exterminio a lo peor de lo peor que  ha dado la humanidad. La risa u otra forma de expresión que logre el humor, le han  servido y servirán a muchos para limar las asperezas a veces insoportables de  saber que se convive con muertes, ajusticiamientos, torturas, persecuciones,  mutilaciones, encierros…</p>
<p>Hay muchos caminos para la relectura de los primeros capítulos de la  serie. Uno de los más ásperos es poner el foco ya no en el porqué de su  violencia sin medida sino en los objetivos de ella. Es en su desprecio por la  súplica de una mujer golpeada en la que se expone, sin pellejos, una de las  tantas formas de violencia familiar que azotan a nuestras sociedades. Es en el  placer adicional al ejecutar a un negro, un latino, un judío, un puto, según el  catálogo Boogie, cuando se reencarna el nazismo que recrudece globalizado y  algunas otras formas de violencia más cotidiana para nosotros como el gatillo  fácil y su impunidad. La lista de sus manifestaciones violentas y su superficie  de contacto con nuestro cotidiano podría ser extensa y más rico para quien la  recorra con ganas de hacerlo. El riesgo no es menor: aún hoy, a más de cuarenta  años de haber comenzado sus tropelías, Boogie se manifiesta como una crítica  ácida a la sociedad occidental y el summum de su hediondez puesto en un  mercenario norteamericano; y preguntará, ácido, muy ácido, si hay algo de su saña  en nuestros corazones. </p>

<?
	include('boogie/index.php');
?>