<div class="img_cen1" style="
    background: url('images/701.jpg') repeat-x;
    width: 60px;
    height: 2240px;
    float: left;
    background-repeat: repeat-y;">
</div>
<p><strong>Introducción</strong> <br />
Gerard Genette (París, 1930) es  un crítico literario y profesor de la Universidad de la Sorbona que escribió,  entre muchas otras, la obra <em>Palimpsestos.</em> En ella desarrolla una serie  de conceptos a través de los cuales cualquier texto establece relaciones  consigo mismo y con otros que le preceden. Llama a este fenómeno transtextualidad  y lo divide en cinco categorías: la intertextualidad, la paratextualidad, la  hipertextualidad, la metatextualidad y la architextualidad.</p>
<p>En el cuento que nos convoca,  &ldquo;La Hormiga&rdquo; (Marco Denevi, <em>Falsificaciones</em>, 1966), encontramos algunos  de estos procedimientos, en especial dos de ellos —el hipertexto y el paratexto—  a los que nos avocaremos en este breve ensayo.</p>
<p>Genette define a la  hipertextualidad como &ldquo;la relación que liga determinado texto (hipotexto) a uno  ya existente (hipertexto)&rdquo;, de manera que el primero no podría existir de no  ser por su antecesor y del cual nace, ya por transformación, ya por imitación  (…). Este hipotexto puede que no mencione directamente al texto original, ni  mucho menos que lo cite, pero surge de aquél mediante una especie de  transformación que puede ser más simple o directa o más compleja y, por lo  tanto, más indirecta.</p>
<p><strong>El Gran  Hormiguero o la caverna subterránea</strong> <br />
  A quienes hemos leído la  alegoría de la caverna, que aparece en el libro VII de <em>La República</em> de  Platón, nos resultaría sino imposible, al menos sospechoso, que Denevi no hubiera  leído, detenidamente, la obra citada antes de escribir &ldquo;La hormiga&rdquo;. </p>
<p>En este breve relato, una  cantidad cada vez más creciente de hormigas viven en un gran hormiguero, del  cual, gracias a la creación de un vegetal artificial que les sirve de alimento,  no tienen necesidad —ni autorización— de salir ni de asomarse a la superficie  para no tener que enfrentarse a los peligros del mundo real: el fuego, el  veneno, las nubes insecticidas...</p>
<p>Pero un día, una hormiga (&ldquo;La Hormiga&rdquo;, tal el título del  cuento) distingue a través de un corredor en ruinas una luz lejana y, a través  de una salida cuya clausura se ha desmoronado, sale a la superficie de la  tierra y entra en contacto con la verdadera naturaleza (el Bien platónico,  aquella Verdad a la que se accede a través de la experiencia de la educación): &ldquo;Ve una mañana. Ve un jardín. Ve tallos,  hojas, yemas, brotes, pétalos, estambres, rocío (...)&rdquo;. Este hecho  &ldquo;casual&rdquo; despierta en ella todos sus instintos y, luego de darse un atracón,  desciende nuevamente al Gran Hormiguero (la caverna) e intenta, de la manera  que puede, contarle a sus compañeras (los prisioneros de la caverna platónica)  lo que ha visto, pero ellas, pensando que está loca, deciden matarla, tal como  Sócrates dijo a Glaucón que pasaría si uno de los prisioneros retornara a la  oscuridad (mundo visible) y contara que estuvo en contacto con la superficie  (mundo inteligible).</p>
<p>Aquí mismo podría concluir este  breve ejercicio de las relaciones transtextuales —que operan en la mayoría de  los textos—. Sin embargo, es dable mencionar una especie de nota al pie, que  figura debajo del texto analizado, y que nos abre, a través de la  paratextualidad, la posibilidad de emprender un nuevo recorrido sobre el cuento  de Denevi. La cita apócrifa —que se encuentra entre paréntesis— acusa: &ldquo;Escrito por Pavel Vodnik un día antes de  suicidarse. El texto de la fábula apareció en el número 12 de la revista  Szpilki y le valió a su director, Jerzy Kott, una multa de cien znacks&rdquo;. </p>
<p>Volviendo a Genette, la &ldquo;paratextualidad&rdquo;  es el procedimiento por el cual los elementos que rodean al hipotexto (títulos,  epígrafes, notas al pie, etc.) brindan información clara y relevante sobre él.  ¿Cuál es la importancia que tiene esta nota? Ella nos habla del castigo —el suicidio—  al que fue sometido el supuesto autor del texto, Pavel Vodnik, primero, y el  dueño de la revista que lo publicó —la multa—, después. Es decir, este elemento  paratextual refuerza la idea del castigo que sufre el integrante de una  sociedad organizada (la Hormiga) y <em>normalizada</em>, cuando viola las leyes  que allí imperan.</p>
<p>Esto nos da paso al siguiente  apartado en el que se ofrecerá un paralelo —o relación hipertextual nuevamente—  con la obra de Michel Foucault, <em>Vigilar y  castigar</em> (1975).</p>

<!--<span class="image_cen1"><img src="images/7.jpg"></span>-->

<p><strong>Vigilancia y  castigo</strong><br />
  En <em>Vigilar y castigar</em>, Foucault desarrolla el tema de las sociedades  de control, partiendo de un estudio minucioso sobre la evolución de las  variadas formas de castigo imperantes en distintos momentos históricos. Allí,  nombra dos ejemplos contrastantes de lo que llama &quot;tecnologías de  castigo&quot;. La primera, la tecnología de castigo 'monárquica' que consiste  en la represión de la población mediante ejecuciones públicas y tortura, y la  segunda, el &quot;castigo disciplinario&quot; que, según dice, es la forma de  castigo practicada hoy día. Estas nuevas tecnologías están formadas por un conjunto de procedimientos para dividir en zonas,  controlar, medir, encauzar a los individuos y hacerlos a la vez &ldquo;dóciles y  útiles&rdquo;. </p>
<p>No obstante, para este autor, el poder no puede ser localizado en una  institución —por ejemplo, en el Estado—, sino que está determinado por el juego  de saberes que respaldan la dominación de unos individuos sobre otros al  interior de estas estructuras. Por lo tanto, el poder, al ser relación, está en  todas partes: el sujeto está atravesado por relaciones de poder, no puede ser  considerado independientemente de ellas. Es así que la clave del poder no es la  disciplina sino la normalización, y para que esta pueda llevarse a cabo es  necesario que la disciplina opere ante todo en la distribución de los  individuos en el espacio. Para ello, emplea varias técnicas: puede, por ejemplo,  exigir la clausura, la especificación de un lugar heterogéneo a todos los demás  y cerrado sobre sí mismo; en palabras de Foucault: &ldquo;El espacio disciplinario tiende a dividirse en tantas parcelas como  cuerpos o elementos que repartir hay. Es preciso anular los efectos de las  distribuciones indecisas, la desaparición incontrolada de los individuos, su  circulación difusa. Se trata de establecer las presencias y las ausencias, de  saber dónde y cómo encontrar a los individuos, instaurar las comunicaciones  útiles, interrumpir las que no lo son, poder en cada instante vigilar la  conducta de cada cual, apreciarla, sancionarla (...)&rdquo;.</p>
<p>Uno de los tópicos de su obra es el panóptico de Bentham, una figura  arquitectónica en cuya periferia hay una construcción en forma de anillo; en el  centro, una torre con anchas ventanas que se abren en la cara interior del  anillo. La construcción está dividida en celdas, cada una de las cuales  atraviesa toda la anchura de la construcción. Estas tienen dos ventanas, una  que da al interior, correspondiente a las ventanas de la torre, y la otra, que  da al exterior, y que permite que la luz atraviese la celda de una parte a  otra. Por el efecto de la contraluz, se pueden percibir desde la torre,  recortándose perfectamente sobre la luz, las pequeñas siluetas cautivas en las  celdas. Su efecto mayor es, sin dudas, inducir en el detenido un estado  consciente y permanente de visibilidad que garantiza el funcionamiento  automático del poder. </p>
<p>Volviendo al cuento de Denevi, es otra vez innegable que éste establece  una relación hipertextual —esta vez mucho más solapada, sin dudas, que en el  caso de la alegoría de la caverna— con los postulados que Foucault propone en  la obra citada anteriormente. Este Gran Hormiguero, que se encuentra bajo la  dirección de la Gran Hormiga, fue diseñado de manera tal que, por medio de la  clausura de todas las posibles vías de acceso al exterior, sus límites no  pudieran ser franqueados (&ldquo;Estos  &quot;observatorios&quot; tienen un modelo casi ideal: el campamento militar.  Es la ciudad apresurada y artificial, que se construye y remodela casi a  voluntad...&rdquo;, en palabras de Foucault). Por otro lado, sus habitantes,  al poseer alimento suficiente —el vegetal artificial creado por estos mismos  &ldquo;cuerpos dóciles&rdquo; en la terminología foucaultiana— son perfectamente  controlados, o mejor dicho, &ldquo;normalizados&rdquo; de modo que no es necesario  explicitar cuál es la regla y, en consecuencia, cuál es el castigo ante la  violación de la misma —atravesar los límites impuestos y descubrir que el Gran  Hormiguero no es el Gran Universo como están &ldquo;obligadas&rdquo; a creer— ni designar  una entidad para que se encargue de las ejecuciones (el rey en las sociedades  monárquicas), dado que el mismo grupo social está ya sometido y disciplinado  por el sistema en el que habita. De ahí que sean las mismas hormigas (y no la  Gran Hormiga) quien castigue-mate a la hormiga transgresora, del mismo modo que  el falso autor de la fábula (Pavel Vodnik, en la cita apócrifa del cuento) no  es ejecutado por ninguna autoridad sino que se suicida a sabiendas de lo que  podría ocurrirle. </p>
<!--<span class="image_cen1"><img src="images/7.jpg"></span>-->
<p><strong>A modo de cierre</strong> <br />
  &ldquo;La Hormiga&rdquo;, de Denevi, en una  clasificación estrictamente literaria, podría ubicarse dentro del género  fábula: sus personajes son animales personificados, tiene una estructura  narrativa sencilla, es contada por un narrador testigo en tercera persona y  tiene, claro está, una moraleja. </p>
<p>Esta narración, lejos de querer  imponernos una enseñanza —el elemento más importante en todo texto de este tipo—  explícita y redundante, nos deja una sensación de espacio en blanco para  completar. No nos explicita un precepto a seguir, como en las fábulas  tradicionales, sino que la deja en estado latente, por llamarlo de alguna  forma. ¿De qué modo lo logra? Lo logra a través de un uso particular del tiempo  verbal presente. Recordemos que, de acuerdo con cualquier gramática del  español, los tiempos verbales utilizados en la narración son los del pasado  (una combinación entre los pretéritos perfecto, imperfecto y pluscuamperfecto),  restringiendo el uso del presente ya para los diálogos de los personajes, si  los hubiere, ya para los comentarios del narrador. </p>
<p>Sin embargo, &ldquo;La Hormiga&rdquo; no  posee diálogos directos ni comentarios del narrador —excepto la cita apócrifa  que mencionáramos anteriormente—, pero está escrito íntegramente en presente.  Esto se debe a un procedimiento narrativo por el cual se usa un presente que  varias gramáticas suelen llamar &ldquo;gnómico, atemporal o intemporal&rdquo; durante todo  el relato, con un valor de sentencia, afirmación, etc., que es el que podemos  ver en los refranes, los proverbios, las sentencias y las leyes.</p>
<p>Por esto es que —más allá de  todo lo expuesto hasta aquí— confirmamos lo antedicho: Denevi, en su texto, en  este intento de moraleja entrelíneas, hace uso de este tiempo de un modo en  absoluto casual sino con la intención de darle a su cuento un profundo carácter  alegórico.</p>