<p>El libro tiene 544 páginas y en el medio  de su tapa blanca hay un escudo dorado que recrea al de la República Argentina.  El sol corona un marco de laureles que encierra un apretón de manos. En el  centro, un mango de guitarra hace las veces de gorro frigio. La iconografía tan  nacional y el gran volumen del ejemplar, que recorre las cinco décadas de la  historia del rock en nuestro país, hacen que el libro resalte en las mesas de  novedades de las librerías y parezca un manual, una biblia, una enciclopedia,  un ejemplar de referencia; un libro que cuenta una historia larga, apasionante  y llena de personajes. Al leerlo se comprueba que efectivamente es todo eso junto,  una obra monumental, detallada e impecable, escrita por un periodista  apasionado que mantuvo la adrenalina de contar intacta desde que tenía 19 años  hasta ahora. A esa edad, en el año 1983, comenzó a escribir la primera parte,  cuando la historia de nuestros músicos de rock casi no había sido contada. Ese  interés sanamente obsesivo ha mantenido a Marcelo Fernández Bitar  reconstruyendo y escribiendo las andanzas de pioneros y nuevas bandas durante  más de 20 años para distintos medios. Cuando se le pregunta cómo hizo para  recopilar los datos que volcó en <em>50 años  de rock en Argentina</em> (editorial Sudamericana) contesta que &ldquo;la información  andaba dando vueltas&rdquo;, en las entrevistas, las publicaciones, los recitales, los  discos y los balances musicales del año que ha escrito durante toda su carrera. </p>
<p>&quot;Este libro intenta registrar la  historia de las ediciones y apariciones en escena de los músicos y sus discos,  lo que compone al rock nacional. Esta titánica tarea es una edición que  conmemora 50 años de rock&quot; escribe Adrián Dárgelos, el vocalista de  Babasónicos en el prólogo. </p>
<p>Además de viajar a través de cinco décadas  de música, el libro incluye un catálogo de 32 páginas con fotos a cargo de Nora  Lezano, y el inventario de los discos que se publicaron año a año en el país. </p>
<p><strong>¿Cómo fue que a los 19 años decidís  escribir una historia que casi no había sido contada?</strong> <br />
  Me había devorado &ldquo;Cómo vino la mano&rdquo; de  Miguel Ginberg que llegaba hasta el 76 pero no incluía la escena que yo estaba  viendo en vivo en ese momento. Buscaba material y no encontraba. Comencé a  comprar discos en el año 80 y en el 83, empecé a escribir porque me apasionaba  todo el tema. Ya había hecho unos reportajes con algunos músicos para una  revista del colegio y empecé a reconstruir un poco la línea de tiempo hablando  con los protagonistas de fines de los 60. Busqué información, recopilé material  y le di forma de historia año a año. Tres años después contacté una editorial  que estaba empezando a publicar libros de rock (Distal) y el mío salió en el  87. Con la misma caradurez y locura encaré a Spinetta y le pedí una  introducción. </p>
<p><strong>¿Cómo fue ese pedido?</strong> <br />
  A medida que fui haciendo notas para el  libro me fui contactando con periodistas y empecé a escribir en revistas o sea  que ya a esa altura, en el 86, lo había entrevistado un par de veces. Lo llamé  a la casa, saqué el número de la guía telefónica. Me dijo que vaya al estudio y  la introducción salió mientras él estaba grabando <em>La la la</em> con Fito Páez. Me acerqué con un manuscrito del libro y él  escribió un texto. </p>
<p><strong>¿En qué revistas escribías?</strong> <br />
  Casi en simultáneo en <em>Cerdos &amp; Peces</em> que todavía era un suplemento dentro de la  revista <em>El Porteño</em>, y en <em>Canta Rock</em>. Agarré justo un pequeño  recambio generacional de críticos de rock que empezamos casi al mismo tiempo.  Sergio Marchi y Eduardo de la Puente hacían una revista under llamada <em>Tren de carga</em> y con Eduardo Berti  empezamos en <em>Canta Rock</em>. Fuimos los  primeros periodistas más allá de la camada del <em>Expreso Imaginario</em>. Los músicos nos veían periódicamente y había  tres o cuatro encuentros por año con cada uno. Hoy parece una locura  encontrarse tantas veces con Luca Prodan, Federico Moura, Miguel Abuelo pero  era el poco espacio que había. No existían las radios FM ni los suplementos  jóvenes, así que era ese pequeño reducto de hacer notas para <em>Pelo</em> o <em>Canta Rock</em>. </p>
<p><strong>¿Por qué elegiste a Adrián Dárgelos para  el prólogo de esta edición?</strong> <br />
  Quería agregar algo nuevo, algo especial y  me pareció que era bueno buscar a alguien perteneciente a una generación más  joven que la de Spinetta. Dárgelos en las entrevistas es siempre muy  articulado, tiene ideas y teorías. Se embarcó a hacerlo por más que no suele  escribir prosa. Entregó un manuscrito de puño y letra. </p>
<p><strong>¿Qué le agregaste a la primera parte?</strong> <br />
  Prácticamente los testimonios que hay, en  esa primera versión y en las reediciones que hubo después, se limitaban a los  protagonistas con alguna declaración de Pipo Lernoud, Pedro Pujó del sello  Mandioca o de Grinberg. Ahora agregué declaraciones y frases de todos los  reportajes que hice en estos más de 20 años y los fui insertando en el lugar  correspondiente. Por ejemplo si entrevistaba a Litto Nebbia y me hablaba de Los  Gatos, usaba ese párrafo y lo ponía en el año correspondiente y así con todas las  notas. </p>
<p><strong>¿Cuál es la diferencia del rock nacional  de los inicios y el de ahora?</strong> <br />
  Es raro porque al entrevistar a los  grupos, verlos en vivo o ir a un ensayo sigo encontrando ese mismo espíritu que  en los comienzos. Obviamente ya está construida alrededor de la música toda una  industria que no existía a finales de los ´60 pero me parece que la gran  mayoría de los músicos no parten de eso. Si bien son conscientes de que hay  dinero en juego en la recaudación de un show, no es el origen o el motivo de la  mayoría de las bandas. Hasta en los ensayos de grupos grandes los ves como  chiquilines armando canciones y haciendo bromas. Realmente hay una frescura,  pasión y mística que no sé si encontrás en Inglaterra o Estados Unidos. </p>
<p><strong>¿Tenés algún otro libro proyectado?</strong>    <br />
  Tengo un par de ideas de alguna cosa nueva  pero nunca se dio reeditar la biografía de Soda Stereo que hice en el 89. Eso  es una asignatura pendiente porque desde ese año en adelante entrevisté a Soda  con cada disco, y también a cada uno de ellos por separado en su etapa solista  así que a toda esa información la tengo dando vueltas. </p>
